### ISSUE TITLE
What Is This "DateLike" Black Magic?

### ISSUE THREAD

**Issue by JimLynchCodes** [chronotope/chrono#1005]
Hi! First let me say thanks for making this nice library. 👍

I just wanted to point out a weird thing that tripped me up.

Consider this code:
```rust
use chrono::{NaiveDate, Local};

fn main() {
    let d = Local::now().naive_local().date();
    println!("{}", d.num_days_from_ce());
}
```

This fails to compile with the strange error, "no method named `num_days_from_ce` found for struct `NaiveDate` in the current scope".

what?? no method name? it's right there in the documentation!!?

Took me a while to figure out I needed to add`Datelike` to the things I'm using from chrono. So my question is, why? Why force the consumers to have to import dependencies manually that we aren't using directly?

Maybe there is something about Rust that I am not understanding here, or maybe there is something that can be changed about this library so that consumers don't need to use `DateLike` in this situation.

I hope someone can help me understand this better. thanks!

**Comment by djc** [comment]
It's called a trait. Maybe read the documentation:

https://doc.rust-lang.org/book/ch10-02-traits.html

**Comment by JimLynchCodes** [comment]
Can the compiler then recommend to bring in the proper Trait instead of just shrugging and saying, "idk that function doesn't exist".

Thanks for linking to the section on Traits in general, but I don't see how the consumer of this `chrono` library (and any Rust library, in general) is supposed to know that they need to bring in these phantom Traits created by the library author, especially when the compiler gives this unhelpful error message.

**Comment by JimLynchCodes** [comment]
Another issue with this syntax is that it produces a compiler warning that these necessary phantom imports are unused. Thus, there is no possible way for my code to compile cleanly... 😔

```
warning: unused imports: `Datelike`, `NaiveDate`, `Weekday`
  --> src/bin/foo/bar.rs:25:18
   |
25 |     use chrono::{Datelike, Duration, Local, NaiveDate, Weekday};
   |                  ^^^^^^^^                   ^^^^^^^^^  ^^^^^^^
```

**Comment by djc** [comment]
I'm sorry, but I don't have the bandwidth to teach you the Rust language.

**Comment by jtmoon79** [comment]
This Issue should be Closed @JimLynchCodes
