### ISSUE TITLE
Why no From<NaiveDateTime> for NaiveDate?

### ISSUE THREAD

**Issue by pezcore** [chronotope/chrono#1006]
Looks like the canonical way to convert a `NaiveDateTime` into a `NaiveDate` is with [`NaiveDateTime::date`](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDateTime.html#method.date). But I wonder, why is this conversion only implemented as a method on `NaiveDateTime`, and not as an implementation of `From<NaiveDateTime> for NaiveDate`? It seems to me that in general, the standard place to look for infallible type conversions is [`trait From`](https://doc.rust-lang.org/std/convert/trait.From.html), not in the from-type's regular methods. 

Is there a reason why there is no `impl From<NaiveDateTime> for NaiveDate`?

**Comment by jtmoon79** [comment]
My _guess_ is it was a design oversight from when this crate was new and the developers were newish to Rust.

My own opinion is that adding that `trait From` capability and leaving the `date` function in-place would be okay and you could submit a PR. However, I'm new to this project. You may want to wait until @esheppa or @djc chime in.

**Comment by djc** [comment]
Adding a `From` impl would make sense to me, please submit a PR!
