### ISSUE TITLE
Example in docs

### ISSUE THREAD

**Issue by c-git** [chronotope/chrono#1008]
Hi quick question.

Is the example used in the docs a valid time or should it be updated (it shows a time with 60 seconds)?

![image](https://user-images.githubusercontent.com/43485962/229304478-da65bea0-933b-4215-a56d-f53634f3b451.png)

Can do the pull request but not sure if it's actually a valid time.

**Comment by djc** [comment]
It's valid due to the support for leap seconds.

**Comment by c-git** [comment]
I see thank you for explaining
