### ISSUE TITLE
Latest release `0.4.24` uses `time:0.1.45` which has some vulnerabilities

### ISSUE THREAD

**Issue by josecelano** [chronotope/chrono#1015]
Hello.

Vulnerabilities: https://github.com/advisories/GHSA-wcg3-cvx6-7396
Latest version: https://crates.io/crates/chrono (0.4.24)
Time 0.1.45 is deprecated: https://crates.io/crates/time/0.1.45

Are you planning to release a patch updating the `time` dependency? Maybe `0.4.25`?

Upgrading Time to `0.2.23` should be enough.

**Comment by djc** [comment]
See #602.
