### ISSUE TITLE
How to create local date time with zero hour/minute/second

### ISSUE THREAD

**Issue by DoumanAsh** [chronotope/chrono#1022]
Due to tons of unecessary deprecations it became impossible to use this library for our use case which is:

1. Get local date ('chrono::Local::today()`)
2. Set hour/minute/second to 0:0:0 (`and_hms(0, 0, 0)`)

There is no need to deprecate useful things unless you have alternative for their usage?

`chrono::Local::today` cannot be replaced with `chrono::Local::now` as it is.
It returns two completely different things

Something simple as creating midnight timestamp should be error-less, yet you force user unwrapping all these infallible operations because you cannot even provide const constructors

**Comment by pitdicker** [comment]
Ai, I can understand your frustration. That was non-trivial.

```rust
use chrono::{Local, TimeZone};

fn main() {
    let today_date_naive = Local::now().date_naive();
    let midnight_naive = today_date_naive.and_hms_opt(0, 0, 0).unwrap();
    let midnight_local = Local.from_local_datetime(&midnight_naive).unwrap();
    println!("{:?}", midnight_local);
}
```

The deprecation of methods that are infallible as long as you pass values that are in range (like `and_hms`) is something that I as a user also don't really like, but that is another issue.

It is maybe interesting to know if you wanted a time 1 minute after midnight today this program could have panicked in some locales, because it is not uncommon to have a DST transition at midnight. Than that time wouldn't exist.

I wonder if a `set_time` method on `DateTime` would be possible. Than maybe something like `Local::now().set_time(time)` could work.

**Comment by DoumanAsh** [comment]
> It is maybe interesting to know that if you wanted a time 1 minute after midnight today this program could have panicked in some locales, because it is not uncommon to have a DST transition at midnight. Than that time wouldn't exist.

I'm not sure how is that possible?
Just because DST exist, doesn't make `00:01` impossible time I think.
Every timezone exists within range of 0 to 24 hours etc

**Comment by pitdicker** [comment]
Just for fun, may I suggest you run the following code on a Unix system with the date and timezone set to 2022-03-25 Damascus, Syria (to pick an example)?
```rust
use chrono::{Local, TimeZone};

fn main() {
    let today_date_naive = Local::now().date_naive();
    let midnight_naive = today_date_naive.and_hms_opt(0, 0, 1).unwrap();
    let midnight_local = Local.from_local_datetime(&midnight_naive).unwrap();
    println!("{:?}", midnight_local);
}
```

That will fail with:
```
thread 'main' panicked at 'No such local time', /home/pitdicker/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.24/src/offset/mod.rs:186:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The local time jumps from 0:00:00 to 1:00:00, making the day 23 hours long.

On the other hand, one second after midnight can exist (it will just be at 1:00:01):
```rust
use chrono::{Duration, Local, TimeZone};

fn main() {
    let today_date_naive = Local::now().date_naive();
    let midnight_naive = today_date_naive.and_hms_opt(0, 0, 0).unwrap();
    let midnight_local = Local.from_local_datetime(&midnight_naive).unwrap();
    println!("{:?}", midnight_local + Duration::seconds(1));
}
```

Result:
```
2022-03-25T01:00:01+03:00
```

**Comment by DoumanAsh** [comment]
I don't understand why it should fail? and how second would matter.
Is `0:00:00` not valid time all of the sudden?

**Comment by iwinux** [comment]
Got bitten by this when upgrading deps. I decide to pin `chrono`  at 0.4.20 until things get better :(

**Comment by pitdicker** [comment]
@iwinux Don't you think it is better to just use the line `Local::now().date_naive().and_time(NaiveTime::MIN).and_local_timezone(Local)` as suggested above, and update to recent versions?

**Comment by 0xpr03** [comment]
> Don't you think it is better to just use the line

Thanks for all the work. I suggest adding this issue to the docs. Just started upgrading an old running project from chrono 0.4.19 where I have some arcane Date<Local> code to get (for example) the same local time in +- X days. Took me a bit of searching around to find this issue.
