### ISSUE TITLE
Why RUSTSEC-2020-0071 after RUSTSEC-2020-0159 solved?

### ISSUE THREAD

**Issue by damccull** [chronotope/chrono#1045]
Why are we suddenly seeing RUSTSEC-2020-0071 pop up (even with default features off and required features re-enabled)? It seems to be the same error as RUSTSEC-2020-0159. I threw it in my audit.toml ignore list for now, but I'm curious why this old RUSTSEC is suddenly popping up.

**Comment by pitdicker** [comment]
It is probably obvious to others but not to me: where are you "suddenly seeing RUSTSEC-2020-0071 pop up"?
Is it some cargo command, GitHub notification, ...?

**Comment by djc** [comment]
There was a GitHub notification, probably due some sync happening between GHSA and the RustSec advisory database.

**Comment by damccull** [comment]
I saw it in cargo audit and cargo deny, both from the rustaec website.

**Comment by jtmoon79** [comment]
- https://rustsec.org/advisories/RUSTSEC-2020-0159.html
- https://rustsec.org/advisories/RUSTSEC-2020-0071.html

**Comment by dreaminghk** [comment]
Also hitting the same alert.

Crate:     time
Version:   0.1.45
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Severity:  6.2 (medium)
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.45
└── chrono 0.4.26
    └── ...

**Comment by markdespain** [comment]
I also encountered the same alert yesterday.

Crate:     time
Version:   0.1.45
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Severity:  6.2 (medium)
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.45
└── chrono 0.4.26

**Comment by djc** [comment]
See #602.
