### ISSUE TITLE
Pre-Parse strftime string

### ISSUE THREAD

**Issue by Kixiron** [chronotope/chrono#1057]
A way to pre-parse a format/parse string would be really nice, I call `DateTime::parse_from_str` in a hot loop and I'd like not to re-parse the format string in every iteration

**Comment by Kixiron** [comment]
I guess `StrftimeItems` lazily parses the string and then allows you to later reuse it? I don't see any sort of `.reset()` method on it, how do you restore it to a state that allows you to call `parse()` with it again?

**Comment by pitdicker** [comment]
Ai, it doesn't even allow reuse?
Is it for you an option to manually create an array with formatting items (again, pretty much undocumented)? https://docs.rs/chrono/latest/chrono/format/enum.Item.html

In `Numeric` and `Literal` you can find the items that would make up the fields of the format string. `parse` can accept an iterator over such an array.

**Comment by pitdicker** [comment]
Collecting the elements of the `StrftimeItems` iterator should also get you that array.

**Comment by jtmoon79** [comment]
@Kixiron if you figure it out, would you please repost the reduced recipe here?

**Comment by Kixiron** [comment]
You just do what pitdicker said, `StrftimeItems::new("%Y-%m-%d").collect::<Vec<_>>()`

**Comment by djc** [comment]
@Kixiron thanks for following up!
