### ISSUE TITLE
Different Serializations depending on Serde or Rust-Serialize

### ISSUE THREAD

**Issue by cetra3** [chronotope/chrono#107]
Not sure why this is the case, but the serialization is different between the two libraries.

With serde, we get mostly js compatible date strings:

```
{
"date": "2016-07-08T09:10:48.090"
}
```

With rustc-serialize we get this weird json object:

```
{
"date" : {"date":{"ymdf":16518115},"time":{"secs":33048,"frac":90000000}}
}
```

It would be nice if the default serialization format for rustc-serialize was at least at parity with serde.

**Comment by lifthrasiir** [comment]
This is kept for the historical compatibility and will be changed in 0.3. (I intend to support the older format at the best effort though.)

**Comment by cetra3** [comment]
I've worked around it by implementing a trait on my on type.

I'm wondering if there is a way to supply the format you want, and give the option to the user.

**Comment by lifthrasiir** [comment]
I forgot to close this issue after 0.3.0! This is all gone by now. :smile:

**Comment by cetra3** [comment]
Haha! Good stuff!
