### ISSUE TITLE
Old num-integer version

### ISSUE THREAD

**Issue by rakanalh** [chronotope/chrono#1084]
I am using a chrono along with other libraries that depend on num-integer. The `num-integer` crate used by chrono is at 0.1.36 while other crates expect a newer version.

Would you consider making a 0.4.25 release that includes a more recent `num-integer`? I realize that the `0.5.0` release is upcoming but since the release date is unknown, an intermediate release can be beneficial in this case.

**Comment by pitdicker** [comment]
`num-integer` was recently removed as a dependency in the 0.4.x branch, so the question here is: when is a good time to release 0.4.25?

**Comment by djc** [comment]
My usual policy is something like, when someone asks. I like to wait for important PRs to be merged but  there are too many to wait for all of them and among the open ones I can't think of any that stand out as something we should block on.

So, I guess it's good to put a release out soon.

**Comment by rakanalh** [comment]
That would be great... looking forward to it
