### ISSUE TITLE
parse just TimeZone/Offset

### ISSUE THREAD

**Issue by Benjscho** [chronotope/chrono#1108]
Currently (if I'm reading the docs right) there's no way to parse just a TimeZone/Offset using the formats described in [`format::strftime`](https://docs.rs/chrono/latest/chrono/format/strftime/index.html#specifiers). 

I have a use case to parse an Offset, e.g., `"UTC-0700"` and return a DateTime object at midnight of the current day at that offset, essentially replicating the behaviour of `date -d "UTC-0700"`. I have a workaround to have a default datetime string, and append the offset to be parsed to it, and then use `DateTime::parse_from_str` - is that the only way to do this at the moment? 

Obviously no obligation to consider this as a feature, just wondering if there were any other standard ways for parsing Timezones/Offsets at the moment, or if it was on anyone's mind.

**Comment by pitdicker** [comment]
With https://github.com/chronotope/chrono/pull/1157 `FixedOffset` implements `FromStr`.
