### ISSUE TITLE
Remove incorrect claims from README

### ISSUE THREAD

**Issue by jhpratt** [chronotope/chrono#1110]
There are multiple claims that are simply not true. Namely:

- feature-complete superset of time
  This has not been the case since December 2019 when `time` 0.2 was released. Even before then, there are large number of items in `time` 0.1 that are not present in `chrono` in any way, let alone in a manner that could reasonably be claimed to be a superset.
- strict adherence to ISO 8601
  I don't know if you have a copy of ISO 8601-1:2019, which is the latest version of the specification, but I can trivially find a discrepancy just by looking at definitions. I have not thoroughly checked `chrono` against the specification, as I found one so quickly. If you have a copy of this, I am happy to indicate the exact section number of the discrepancy I quickly found. If you don't have a copy, that should be sufficient reason by itself to demonstrate that you're unable to uphold the guarantee of strict adherence.
- space-optimal
  The simplest example here is `FixedOffset`, which is four bytes. It can trivially be represented by three bytes by storing the hours, minutes, and seconds of the offset, all as `i8`.

**Comment by pitdicker** [comment]
The outdated README was starting to bug me too.

- You know like no one else the features `time` has. I wonder if "feature-complete superset" was true 8 or 10 years ago. But it seems better to me to now just list some features of chrono instead.
- "strict adherence to ISO 8601". I suppose at some point a maintainer had it? It did influence some design choices of chrono. @djc Is this something we still care about and want to advertise? Mentioning a pay-walled standard seems like something that is pretty meaningless to 99% of the users.
- "space-optimal". I'll give you that `FixedOffset` only requires 18 bits. But I do think storing a wide range of dates in a `u32` is optimal and worth calling out. Same for storing a time or nanoseconds in a `u32`. Or the `Utc` offset which is a ZST.

**Comment by jhpratt** [comment]
Yeah, I have no doubt that at some point it was a superset, but that hasn't been the case for many years at a minimum.

For sizes, definitely call things out! I've no issue with that, of course. I just feel that saying "space optimal" is not _quite_ true.

**Comment by pitdicker** [comment]
Then we agree. I have tried to make some changes in https://github.com/chronotope/chrono/pull/1111, do you see any errors remaining?

**Comment by jhpratt** [comment]
Closing as completed by #1111.
