### ISSUE TITLE
Formatting timestamp with %#z panics

### ISSUE THREAD

**Issue by domodwyer** [chronotope/chrono#1139]
When attempting to format a timestamp with a strftime format string containing `%#z` it panics:

https://github.com/chronotope/chrono/blob/088b69372e93e64f144183fb3324cdb079736f8b/src/format/mod.rs#L673

This specifier is documented as being "parsing only" [here](https://docs.rs/chrono/latest/chrono/format/strftime/index.html), but we accept format strings from users (limited/validated) who may put `%#z` in the formatting sequence. 

All other invalid cases (that I can see!) result in `Err(std::fmt::Error)` being returned:

https://github.com/chronotope/chrono/blob/088b69372e93e64f144183fb3324cdb079736f8b/src/format/mod.rs#L571

This has the benefit of allowing the caller to handle the error when the timestamp formatter is invalid (as long as you're not using the infallible `to_string()`). This is one way we validate a user-provided strftime formatter - try and use it, catching any errors - but obviously this doesn't work for `%#z`  because it immediately panics! Thsi was unexpected - we only discovered it through fuzz testing.

Is there a reason `%#z` panics over returning an error? I'd be happy to PR the change to return the error & test.

**Comment by djc** [comment]
Yeah, happy to review a PR for this!

**Comment by pitdicker** [comment]
@domodwyer It just so happens that we are looking at this code the last couple of days. In https://github.com/chronotope/chrono/issues/1127 we try to come up with a way to not panic but find a good place to report en errors.

**Comment by pitdicker** [comment]
If it spares some work, the last commit here has the change and a test: https://github.com/chronotope/chrono/pull/1121
