### ISSUE TITLE
Is it possible to make JSON serialization JavaScript-friendly?

### ISSUE THREAD

**Issue by golddranks** [chronotope/chrono#115]
At the moment, the DateTime values are serialized with the internal representation which is difficult to parse outside of Rust-chrono. This is a bit counterproductive, since often serialization is used to pass values between different systems and programming languages. This is troublesome especially when one wants to serialize a big struct that contains a DateTime value, since one can't simply call `to_rfc3339()` but need to re-implement encoding for the whole struct.

I'm passing values as JSON between web front- and backend at the moment, and struggle to de-serialize them to `Date()` objects in the frontend. I know that there might not exist one-size-fits-for-all encoding scheme, but if specialization in the future allows, I think it makes sense to specialize the serialization formats for different Encoders.

For example, when encoding to JSON, it makes sense to emit a format that is commonly supported in the JavaScript ecosystem, so using `to_rfc3339()` to serialize would be ideal in that case. Once specialization allows it, do you think it will be worthwhile to support this?

That still leaves us with the question: is the current default serialization scheme good enough? I think it's not, but maybe there is a reason to it, or is it what it is just because of inertia?

**Comment by Boscop** [comment]
+1, I'm also interested in this, also for the reasons of dealing with js.

**Comment by iamsebastian** [comment]
Have a look here, @golddranks @Boscop: https://github.com/lifthrasiir/rust-chrono/issues/83
That's how I implemented it for my JSON-output that will be responded to Ember.js frontend.

**Comment by quodlibetor** [comment]
I believe that this has been fixed since 0.3, and 0.4 added support for serializing/deserializing to/from timestamps.

**Comment by quodlibetor** [comment]
This works correctly now, re-open if I've missed something.
