### ISSUE TITLE
[bug] chrono does not print FixedOffset seconds

### ISSUE THREAD

**Issue by grantslatton** [chronotope/chrono#1154]
This code

```
let offset = FixedOffset::east_opt(1).unwrap();
let dt = NaiveDate::from_ymd(2021, 1, 1).and_hms(0, 0, 0);
let dt = DateTime::<FixedOffset>::from_local(dt, offset);
dbg!(dt.offset());
dbg!(dt.to_rfc3339());
```

Prints:

```
dt.offset() = +00:00:01
dt.to_rfc3339() = "2021-01-01T00:00:00+00:00"
```

Note that the RFC3339 only has `+HH:MM`, `+00:00` but should be `+00:00:01`.

This is because the code delegates to [write_local_minus_utc](https://github.com/chronotope/chrono/blob/38b19bbe4e21c402f81edfa2932a43831e679a35/src/format/mod.rs#L709C1-L709C1) which explicitly ignores seconds.

This bug makes chrono out of compliance with RFC3339.

**Comment by pitdicker** [comment]
It is unclear to me what you consider the issue.

But an offset with seconds is indeed difficult, as encoding it is not supported by RFC 3339, ISO 8601 or RFC 2822.
You can format it with `%::z`.

**Comment by grantslatton** [comment]
Ah, I discovered this by comparing the result of `chrono::DateTime::to_rfc3339` to Python's `datetime.datetime.isoformat` which claims to be 8601, but I guess it is Python that is out of compliance here by showing the second-level offsets.
