### ISSUE TITLE
Possible typo in the documentation (leap seconds)

### ISSUE THREAD

**Issue by kamadorueda** [chronotope/chrono#1174]
The current documentation (https://docs.rs/chrono/0.4.26/chrono/naive/struct.NaiveTime.html#date-and-time-arithmetics) lists the following examples for the handling of leap seconds:

```
Time + Duration (short for [NaiveTime::overflowing_add_signed](https://docs.rs/chrono/0.4.26/chrono/naive/struct.NaiveTime.html#method.overflowing_add_signed)):

03:00:00 + 1s = 03:00:01.
03:00:59 + 60s = 03:02:00.
03:00:59 + 1s = 03:01:00.
03:00:60 + 1s = 03:01:00. Note that the sum is identical to the previous.
03:00:60 + 60s = 03:01:59.
03:00:60 + 61s = 03:02:00.
03:00:60.1 + 0.8s = 03:00:60.9.
```

All examples make sense, except `03:00:59 + 60s = 03:02:00.` which, given that no operand is a leap second, should be `03:01:59`, and in fact, that's what's reported in the playground:

![image](https://github.com/chronotope/chrono/assets/47480384/6364f61a-18da-4a47-8d09-3e968761a8fc)

Happy to follow up with a PR if this is a true positive

**Comment by pitdicker** [comment]
I agree, that doesn't make sense. Looking forward to a PR :+1:

**Comment by kamadorueda** [comment]
Oh, wait, I just noticed it's been:
- solved in 0.4.x: https://github.com/chronotope/chrono/blob/0.4.x/src/naive/time/mod.rs#L103
- not solved in 0.5-alpha: https://github.com/chronotope/chrono/blob/0.5-alpha/src/naive/time/mod.rs#L98
- not solved in main: https://github.com/chronotope/chrono/blob/main/src/naive/time/mod.rs#L99

What would be the best course of action?

**Comment by pitdicker** [comment]
Haha, I didn't even notice https://github.com/chronotope/chrono/pull/1146. Then it will make it to main soon in https://github.com/chronotope/chrono/pull/1169.

**Comment by kamadorueda** [comment]
Cool, I'll close it then! Thank you
