### ISSUE TITLE
Parsing a `Date<Local>` from a string

### ISSUE THREAD

**Issue by JoeyAcc** [chronotope/chrono#119]
I've found the canonical way to parse a `DateTime` from a string, but no such operation seems to exist for `Date<Local>`. At least, if it *is* possible, I have yet to discover how. 

Could an easy-to-use API be added if it doesn't exist yet?
Or if it does, how can I access it?

**Comment by Boscop** [comment]
Also, how to parse a UTC Date using `%F` ?

**Comment by quodlibetor** [comment]
Do you really mean `Date<Local>` and not `DateTime<Local>`? `Local` is not a well-specified timezone, you probably shouldn't be trusting that over the wire, but if you really need to you should parse into a `NaiveDateTime` and then adding the local timezone.

`%F` should just work? [link](https://play.rust-lang.org/?gist=b636a400c1daba0f32da114c70037f54&version=stable)

```rust
extern crate chrono;
use chrono::naive::NaiveDate;

fn main() {
    let date = NaiveDate::parse_from_str("2018-03-01", "%F");
    assert_eq!(date, Ok(NaiveDate::from_ymd(2018, 3, 1)));
}
```

You should not be using timezones with dates, they don't really make sense.
