### ISSUE TITLE
parse_from_str is not able to parse a single four digit string with %Y into a NaiveDate

### ISSUE THREAD

**Issue by ElektroVirus** [chronotope/chrono#1197]
Hi, I'm trying to parse an year into a NaiveDate using parse_from_str, however it doesn't seem to work. I also tried %G from this list (https://docs.rs/chrono/latest/chrono/format/strftime/index.html) but it didn't work any better.

```
let testdate1 = NaiveDate::parse_from_str("2023", "%Y");
println!("Testdate: {:?}", testdate1);
```

Output: 
```
Testdate: Err(ParseError(NotEnough))
```

**Comment by ElektroVirus** [comment]
Ok I think I misunderstood this, it probably works as intended since without a month and a date it's not really a date, its only a year. 
So that's why the parsing fails. Have a nice day :D

**Comment by pitdicker** [comment]
Yes, that is the issue :+1:.
