### ISSUE TITLE
`to_rfc2822` can panic

### ISSUE THREAD

**Issue by leontoeides** [chronotope/chrono#1225]
`to_rfc2822` panics if I provide a `MAX_UTC` or `MIN_UTC` date/time. Maybe the date/time could be saturated to what RFC2822 can express? Return a `Result`? Add an `_opt` equivalent and deprecate the panicking one? Also, maybe provide `MIN_RFC2822_UTC` and `MAX_RFC2822_UTC` type constants?

```
cause = "writing rfc2822 datetime to string should never fail: Error"
method = "Panic"
```

**Comment by pitdicker** [comment]
Should get fixed with https://github.com/chronotope/chrono/pull/1144.

**Comment by leontoeides** [comment]
Good news! Thank you sir. I swear, I searched for an existing issue first :-)
