### ISSUE TITLE
Calling and_hms_milli with 1000 ms on a Local date panics

### ISSUE THREAD

**Issue by matt2xu** [chronotope/chrono#123]
Hi,

I don't know if this is expected or not: calling `and_hms_milli` with 1000 ms or more on a Local date panics with the message `assertion failed: nsec >= 0 && nsec < NSEC_PER_SEC`. This works fine with a UTC date. I'm not sure what behavior is expected, the documentation states that you can have 1000 ms and more to model leap seconds.

Code:

```rust
#[cfg(test)]
mod tests {
    use chrono;

    #[test]
    fn chrono() {
        let today = chrono::Local::today();
        let date_time = today.and_hms_milli(1, 2, 3, 1000);
        println!("time: {}", date_time);
    }
}
```

Output:
```text
thread 'packaging::tests::chrono' panicked at 'assertion failed: nsec >= 0 && nsec < NSEC_PER_SEC', /home/mwipliez/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.36/src/lib.rs:88
```

**Comment by lifthrasiir** [comment]
Very good point! This should have been translated to the carryover to the second part. I'll fix this as soon as possible.
