### ISSUE TITLE
test `test_issue_866` fails (`and_hms_milli_opt(1, 2, 59, 1000)` returns `None`)

### ISSUE THREAD

**Issue by jtmoon79** [chronotope/chrono#1236]
On Ubuntu 22 x86_64 using rust 1.72.0

```
$ cargo test --release --all-features
...
failures:

---- offset::local::tests::test_issue_866 stdout ----
thread 'offset::local::tests::test_issue_866' panicked at 'called `Option::unwrap()` on a `None` value', src/offset/local/mod.rs:266:77


failures:
    offset::local::tests::test_issue_866

test result: FAILED. 232 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

error: test failed, to rerun pass `--lib`

```

Relates to Issue #866 and PR #1076 (I added [this test](https://github.com/chronotope/chrono/blob/v0.4.28/src/offset/local/mod.rs#L266)).

**Comment by jtmoon79** [comment]
Why wasn't this caught by the CI ?

**Comment by pitdicker** [comment]
Removed the test, as it is pretty much guaranteed to cause trouble.

Any method that returns `LocalResult` can return something that is not `LocalResult::Single`. Testing that it only returns `LocalResult::Single` by calling `LocalResult::unwrap` does not make all that much sense.

**Comment by pitdicker** [comment]
> Why wasn't this [caught by the CI](https://github.com/chronotope/chrono/blob/v0.4.28/.github/workflows/test.yml#L19) ?

Probably because the CI tests only a couple of time zones, and one that has a transition at the time in this test isn't among them.
