### ISSUE TITLE
Breaking change in RFC 3339 parser

### ISSUE THREAD

**Issue by amousset** [chronotope/chrono#1239]
https://github.com/chronotope/chrono/commit/e985f08868922d38b2b446977cebf19fe960fde3 changed the behavior of the RFC3339 parsers to switch to a relaxed implementation. The modifies notably the behavior of the parser, e.g. the following code fails before and succeeds starting from 0.4.27 (which actually broke some code using it in my case).

```rust
let d = "\n2019-05-09T13:36:46+00:00";
DateTime::<FixedOffset>::parse_from_str(d, "%+").unwrap();
```

I'm not sure if this impact was expected but it is probably worth a warning in the release notes (it currently only says "Small fixes to the RFC 3339 parsers").

**Comment by djc** [comment]
Can you say more about the code it broke and how bad the impact is? Generally my operating assumption is that making parsers more relaxed is usually okay, but of course this is one of those areas where semver is tricky to navigate.

@pitdicker can you propose some changes to the release notes for this?

**Comment by amousset** [comment]
It broke a nom-based parser for log files, that tries to parse a datetime at the beginning of the lines, and that ended up eating an unexpected `\n` in a test case. It has no serious impact and is easy to workaround in our case, and I agree semver is tricky in those cases.
I'd be happy with a clear message in the release notes.

**Comment by pitdicker** [comment]
@amousset In your case the problem is the `"\n"` at the start, right? And not in the fields within the RFC3339 format?
I had to think about the other issues we have about accepting too much whitespace when parsing, https://github.com/chronotope/chrono/issues/660 and https://github.com/chronotope/chrono/issues/548.

Still parsing with the `%+` specifier or the `RFC3339` formatting item is not strict anymore. Is using the strict parsing in `DateTime::FixedOffset::from_rfc3339` a solution?

**Comment by amousset** [comment]
> Is using the strict parsing in DateTime::<FixedOffset>::from_rfc3339 a solution?

Yes, it restores the behavior we were relying on  :+1:

**Comment by pitdicker** [comment]
> @pitdicker can you propose some changes to the release notes for this?

"The parser for the `%+` formatting specifier and the `RFC3339` formatting item is switched from a strict to a relaxed parser. This matches the existing documentation, and the parser used by `DateTime::from_str`. If you need to validate the input, consider using `DateTime::from_rfc3339`."

**Comment by djc** [comment]
Sounds good!

**Comment by pitdicker** [comment]
Updated the release notes.

**Comment by amousset** [comment]
Thanks!

**Comment by tyranron** [comment]
Just another relevant note here for those who may seek answers:

I have a [code](https://github.com/graphql-rust/juniper/blob/df9da4c776a3fa22f67e07327dc3c9caf8e07dfd/juniper/src/integrations/chrono.rs#L224) breakage [too](https://github.com/graphql-rust/juniper/actions/runs/6108983003/job/16579092989#step:5:900).

Now it started to allow `1996-12-19 14:23:43Z` input without `T` in-between. Looking at [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339#section-5.6), it seems that `T` could be relaxed on choice:
> NOTE: ISO 8601 defines date and time separated by "T".
> Applications using this syntax may choose, for the sake of
> readability, to specify a full-date and full-time separated by
> (say) a space character.

**Comment by djc** [comment]
Right, that is actually correct per the RFC.

**Comment by pitdicker** [comment]
> NOTE: ISO 8601 defines date and time separated by "T". Applications using this syntax may choose, for the sake of readability, to specify a full-date and full-time separated by (say) a space character.

My understanding of this paragraph is:
- An ISO 8601 parser will only accept "T" as a separator. We don't need that paragraph to say so, that is specified so in ISO 8601:
  > The character [T] shall be used as time designator to indicate the start of the representation of the time of day component in these expressions.
  >
  > NOTE By mutual agreement of the partners in information interchange, the character [T] may be omitted in applications where there is no risk of confusing a date and time of day representation with others defined in this International Standard.
  
  ISO 8601 is a bit annoying because it specifies something, and then often puts in a note than you can deviated if both parties agree.
- RFC 3339 specifies "T" as separator for compatibility with ISO 8601 parsers, but also allows other characters.
