### ISSUE TITLE
Publish Release with Serde 0.9

### ISSUE THREAD

**Issue by KodrAus** [chronotope/chrono#126]
Now that we've got support for `serde 0.9` merged it would be awesome to get a new release out to unblock anyone who's waiting on it (disclaimer: that includes me :smile:).

CC: @lifthrasiir

**Comment by lifthrasiir** [comment]
I'm working on it. To be more exact: Since we have dropped the support for Serde 0.8 (which I think fine), I think it's a good time to make it 0.3.0 at least for the sake of compatibility. I expect 0.3.0 will be available within a day.
