### ISSUE TITLE
RFC 2822 should have only a single space between weekday and day

### ISSUE THREAD

**Issue by pitdicker** [chronotope/chrono#1269]
From https://github.com/chronotope/chrono/pull/249:
> Test : `EDT.ymd(2015, 2, 3).and_hms_milli(23, 16, 9, 150)` generates `Tue,<space><space>3 Feb 2015 23:16:09 +0500` i.e. 2 spaces before day's value `3`.
> 
> It should be `Tue,<space>3 Feb 2015 23:16:09 +0500`

> The rfc recommends to fold the white spaces (replace multiple white spaces to single white space).
> From [rfc](https://www.ietf.org/rfc/rfc2822.txt) :
>
>```
> Though folding   white space is permitted throughout the date-time specification, it
> is RECOMMENDED that a single space be used in each place that FWS
> appears (whether it is required or optional); some older
> implementations may not interpret other occurrences of folding white
> space correctly.
>
> day             =       ([FWS] 1*2DIGIT) / obs-day
> ```

**Comment by pitdicker** [comment]
And the opinion of @quodlibetor at the time:
> Okay, I think you've convinced me. My inclination is that this is a breaking change and so it should wait for Chrono 0.5. It should get in there, so I've added it to that milestone. There's no real timeline for that release right now, sadly.
> 
> I would happily immediately take a PR to the chrono docs explaining the fact that the date is space-padded.
> 
> I would _like_ to also say that I would also take a PR changing the alignment from space-padded to zero-padded, but the problem is that often, as I'm sure you've encountered, time-parsing code is sensitive to whitespace so any code that relies on this existing behavior might get busted if we eliminate double spaces. On the other hand, all code that can handle chrono-formatted RFC-2833 timestamps _must_ already be capable of handling arbitrary whitespace, so maybe it's not that big of a deal, and I should just accept this PR after you've addressed my one comment. On the _other_ other hand, accepting this PR will ruin alignment of any terminal apps that are depending on it for their display.
> 
> So I still think this needs to at least wait for 0.5, but I'm obviously a bit torn and am open to argument.

**Comment by pitdicker** [comment]
I am not sure yet. Just opening this issue so that we don't loose the issue accidentally.

**Comment by djc** [comment]
Are we talking about formatting or parsing? It's not very clear from title or description.

**Comment by djc** [comment]
I think formatting tweaks probably shouldn't be semver-breaking usually, except insofar as they break roundtripping with our RFC 2822 parsing code.
