### ISSUE TITLE
Add timestamp_micros to Utc

### ISSUE THREAD

**Issue by emikitas** [chronotope/chrono#1284]
I wanted to know if there is a reason for having the functions `timestamp_millis` and `timestamp_nanos` in the trait `TimeZone` but not `timestamp_micros`.
If there is no reason not to have it, will it be possible to implement it?

**Comment by djc** [comment]
What's your use case for it?

**Comment by emikitas** [comment]
I wanted to add support for processing microseconds in VRL, specifically in the following function:
https://github.com/vectordotdev/vrl/blob/000109385569314c6715300bfd84cba0971646c3/src/stdlib/from_unix_timestamp.rs#L5
I figured I might not be the only person interested in transforming microsecond timestamps into DateTime, so I figured I could add it to chrono.
I'd like to implement it myself, but I first wanted to check if there is a reason not to.
