### ISSUE TITLE
Missing panic condition on doc

### ISSUE THREAD

**Issue by HeeillWang** [chronotope/chrono#1302]
Though this is intentional crash, I think it's better to mention on docs as well, like [some other APIs](https://docs.rs/chrono/0.4.31/chrono/struct.DateTime.html#method.date_naive) mentions it.

https://github.com/chronotope/chrono/blob/b64cedc6a8758d15265702895d917045ce1eebf8/src/datetime/mod.rs#L1254-L1258

**Comment by pitdicker** [comment]
Thank you for the report. Fixed in https://github.com/chronotope/chrono/pull/1316.
