### ISSUE TITLE
Example / guide for people migrating from time::strftime

### ISSUE THREAD

**Issue by golddranks** [chronotope/chrono#131]
I am in impression that the `time` crate is deprecated, and one should use the `std::time` if that's enough, and `chrono` for more sophisticated functionality. I've been using all the three in my project, but now I'm trying to strip it down to two. The things my migration is hinging on is how to use the formatting features on `chrono`. The documentation at https://docs.rs/chrono/*/chrono/format/index.html isn't very helpful, as it doesn't contain any concrete examples or even explanation how the formatting / parsing system is supposed to work.

**Comment by lifthrasiir** [comment]
I've assumed that the [landing page](https://docs.rs/chrono/*/chrono/index.html) clearly shows how to format things (`.format("strftime-like string")`)---how did you get to that page at the first place? I guess the search engine directly links to that page, in which case I should put the identical information to that page as well.

**Comment by golddranks** [comment]
Ah, indeed. I found it by a direct link, and expected that a module named `format` would contain all the docs you need to know about formatting.

Even a short description like "Check the guide about how to format times (link) on the front page." would do.
