### ISSUE TITLE
Restart 0.5 branch?

### ISSUE THREAD

**Issue by pitdicker** [chronotope/chrono#1319]
We currently have a 100-commit difference between 0.4.x and main. But the actual changes are limited:
- remove `rustc_serialize`
- rename `Duration` to `TimeDelta`
- move `DateTime<Tz>::{MIN_UTC, MAX_UTC}` to `DateTime<Utc>::{MIN_UTC, MAX_UTC}`
- move `*SecondsTimestampVisitor` from `datetime::serde` to submodules
- mark `SecondsFormat`, `ParseErrorKind` and `Parsed` as `non_exhaustive`
- remove `num_traits` dependency
- be stricter with whitespace parsing
- adds parsing methods to `DateTime<Utc>`

Of three of these I am not convinced they are entirely changes we want:
- adds parsing methods to `DateTime<Utc>`
  Opened a PR to revert https://github.com/chronotope/chrono/pull/1318.
- be stricter with whitespace parsing
  I think we should become much stricter than we currently are. But accepting various Unicode whitespace characters instead of requiring an exact match seems like a useful thing we currently have, and have lost on 0.5.
- rename `Duration` to `TimeDelta`
  Do we want to rename, or somehow switch to `std::Duration`? I prefer a rename. Then: is `TimeDelta` the name we want?

Beyond those that leaves 5 trivial changes between main and 0.4.x.
Does it make sense to restart the branch and get a history I can make sense of?

**Comment by pitdicker** [comment]
> Why are you having trouble making sense of the history?

I don't care all that much about git history. But it is pretty much impossible to tell from the history that the changes I listed above are all there is to it.
And I came to that list by diffing the directories.

**Comment by djc** [comment]
I do care about git history -- this lets us do `git blame` and link from a commit to a PR to see the discussion associated with a change, the motivation, etc. Maybe a better way to look at the changes is by looking at PRs that targeted the `main` branch after the 0.4.x branch was made leading? I think the constituency for this request is probably 1 -- you're the only person who needs this knowledge (because I already knew) and you now have it.

**Comment by pitdicker** [comment]
For reverence to filter PRs by target branch: [`is:pr is:merged base:main`](https://github.com/chronotope/chrono/pulls?page=1&q=is%3Apr+is%3Amerged+base%3Amain)
That is a useful trick :+1:. It leaves only 53 PRs to look through, of which only 4 have not made it to 0.4.x.

I already knew the difference quite well. Did you know this was all that has happened until know for 0.5?
I have compared the difference between 0.4.x and main a bunch of times after making a merge PR, just for fun.

> I do care about git history -- this lets us do `git blame` and link from a commit to a PR to see the discussion associated with a change, the motivation, etc.

There is a trade-off between having a readable git history (git blame works either way), and having an easy link to to the associated GitHub PR. And I have to admit that part is useful.

**Comment by djc** [comment]
IMO "release" branch history should never be changed -- it can also be very confusing for other people who have a local clone.

**Comment by pitdicker** [comment]
Yes, that is a good rule.
