### ISSUE TITLE
input is not enough for unique date and time

### ISSUE THREAD

**Issue by net-illia-stetsenko** [chronotope/chrono#1321]
Hello!
Here I have faced with a problem while trying to move from `Timezone.datetime_from_str` to `DateTime::parse_from_str` in my project.
By using `Timezone.datetime_from_str` I was able to do the following:
`let time = Utc.datetime_from_str("Sat, 11 Feb 2023 23:40:00.000000000 UTC", "%a, %d %b %Y %H:%M:%S.%f %Z").unwrap();` and there weren't any errors in the result.
Now I am trying to use `DateTime::parse_from_str` like this:
`let time = DateTime::parse_from_str("Sat, 11 Feb 2023 23:40:00.000000000 UTC", "%a, %d %b %Y %H:%M:%S.%f %Z").unwrap();`
It produces errror saying "input is not enough for unique date and time". 
It is said in the documentation that this method requires a timezone in the input string which I have successfully provided.
Will be glad for any responce
Thank you in advance

**Comment by pitdicker** [comment]
You are hitting this issue: https://github.com/chronotope/chrono/issues/38. Sorry.

In your case this should work (not tested though):
```
let time = NaiveDateTime::parse_from_str("Sat, 11 Feb 2023 23:40:00.000000000 UTC", "%a, %d %b %Y %H:%M:%S.%f %Z").unwrap().and_utc();
```

**Comment by net-illia-stetsenko** [comment]
> You are hitting this issue: #38. Sorry.
> 
> In your case this should work (not tested though):
> 
> ```
> let time = NaiveDateTime::parse_from_str("Sat, 11 Feb 2023 23:40:00.000000000 UTC", "%a, %d %b %Y %H:%M:%S.%f %Z").unwrap().and_utc();
> ```

Works now, thank you
