### ISSUE TITLE
Offer options to configure how to create rfc 3339 string

### ISSUE THREAD

**Issue by Jasperav** [chronotope/chrono#1339]
The current implementation is that when you want to format a date without milliseconds, the output of the rfc 3339 doesn't contain milliseconds as well. When there are milliseconds, the rfc 3339 also contains them.

Is it possible to configure this behavior? I send formatted rfc 3339 strings data back to clients (iOS + Android) and for some reason, I HAVE to specify client side if the string contains milliseconds or not, it can not handle both cases (I use `ISO8601DateFormatter` in which only 1 case is allowed).

I now divide the time by 1000 and multiple it by a thousand before I format the string. This way, in the current chrono version, I don't get milliseconds in the output but this looks fragile and maybe in a different chrono release this breaks.

**Comment by djc** [comment]
Why not use a custom formatting string?

**Comment by Jasperav** [comment]
@djc What do you mean? I want a consistent generated ISO 8601 string, not sometimes with and sometimes without milliseconds.

**Comment by djc** [comment]
So call [`format()`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.format) on it with the exact format you need.

**Comment by Jasperav** [comment]
@djc Do you expect me to copy paste the implementation of the `write_rfc3339` and never write milliseconds? If was just as simple as calling a `format` method on `DateTime`, why doesn't `write_rfc3339` do that simply? Formatting everything myself looks like re-inventing the wheel.

**Comment by pitdicker** [comment]
Are you looking for [`DateTime::to_rfc3339_opts`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.to_rfc3339_opts)?

`to_rfc3339` has a different implementation instead of `format()` as a performance optimization.
