### ISSUE TITLE
Expose a way to convert from oldtime::Tm to DateTime<Local>

### ISSUE THREAD

**Issue by nox** [chronotope/chrono#135]
The `cookie` crate uses `oldtime::Tm` extensively, I need a way to use these datetimes with `chrono`.

**Comment by pitdicker** [comment]
Duplicate of https://github.com/chronotope/chrono/issues/50.

To quote from there:
> Time 0.2 and 0.3 no longer have these types, and we are trying to move away from time 0.1.
> Adding support for them would be easy, but I don't think it is something we would want to do.
