### ISSUE TITLE
Avoid using operators for date/time arithmetics in the documentation

### ISSUE THREAD

**Issue by expobrain** [chronotope/chrono#136]
Am I wrong or the implementation of `NaiveTime` arithmetics, sum and subtraction, are not implemented yet despite the [docs](https://github.com/chronotope/chrono/blob/master/src/naive/time.rs#L90)?

**Comment by lifthrasiir** [comment]
It is implemented but named [`checked_add_signed`](https://docs.rs/chrono/0.3.0/chrono/datetime/struct.DateTime.html#method.checked_add_signed), [`checked_sub_signed`](https://docs.rs/chrono/0.3.0/chrono/datetime/struct.DateTime.html#method.checked_sub_signed) and [`signed_duration_since`](https://docs.rs/chrono/0.3.0/chrono/datetime/struct.DateTime.html#method.signed_duration_since) currently. I guess they should be updated, as I plan _not_ to reintroduce those operators (there is a reason why `std::time::SystemTime` does not implement operators even though it does have relevant methods).
