### ISSUE TITLE
This API seems very complicated

### ISSUE THREAD

**Issue by gdennie** [chronotope/chrono#1370]
Making `DateTime` generic was probably unfortunate. Perhaps keeping it UTC and performing timezone conversions at point of type conversion (`TryFrom<T>`, `From<T>`, etc) would have lead to a more intuitive result.

...of course, I could be wrong.

**Comment by pitdicker** [comment]
Let's keep the discussion in a single issue in https://github.com/chronotope/chrono/issues/1369.

**Comment by gdennie** [comment]
Hi Paul. 
Thanks for responding. 
I subsequently discovered `Local`, if memory serves, as the correct type to use.
I will continue on the thread you indicated with any suggestions.
Thanks again.
