### ISSUE TITLE
Truncating a timestamp close to EPOCH fails

### ISSUE THREAD

**Issue by joroKr21** [chronotope/chrono#1375]
Due to this check in `duration_truc`:
https://github.com/chronotope/chrono/blob/main/src/round.rs#L221-L223

Expected behaviour: I should be able to truncate the timestamp to 0

**Comment by djc** [comment]
I'd be happy to review a PR -- I probably won't have time to work on this myself.

**Comment by joroKr21** [comment]
It's not urgent for me but I think I will find time for it

**Comment by pitdicker** [comment]
To be honest in my opinion the API and approach in the `round` module is fundamentally flawed. A lot of the behavior doesn't make sense, especially for a library that tries to do handle dates and timezones correctly like chrono. And I don't think it is even possible to fix all logic bugs.

But we would need to have an alternative before it can be deprecated.

**Comment by djc** [comment]
> But we would need to have an alternative before it can be deprecated.

Why? If we think this API is silly or wrong or dangerous, we could deprecate it without providing an alternative.

Does the time crate provide this functionality?

**Comment by pitdicker** [comment]
There are some cases where it works and gives correct results. For example rounding or truncating a `NaiveTime` to a reasonable `Duration` such as 10 seconds. But rounding to for example 7 seconds, and especially when involving dates becomes a mess. And that is ignoring DST :smile:.

> Why? If we think this API is silly or wrong or dangerous, we could deprecate it without providing an alternative.

Maybe you are right. It does not really feel like an inconvenience yet, but we can expect more issues like this.

> Does the time crate provide this functionality?

It doesn't seem to.

**Comment by pitdicker** [comment]
Another issue with `duration_trunc`: https://github.com/chronotope/chrono/issues/584.
