### ISSUE TITLE
Week number in Datelike

### ISSUE THREAD

**Issue by robbym** [chronotope/chrono#139]
It would be really nice to have week number in the `Datelike` trait.
In my particular use case I need to group an `Iterator<Item=NaiveDate>` by month and week number, but I can only do months. I am using the [group_by](https://docs.rs/itertools/0.5.9/itertools/trait.Itertools.html#method.group_by) function in itertools.
```
// days: Iterator<Item=NaiveDate>
days.group_by(|d| d.month())
    .into_iter()
    .map(|(_, month)| {
        month.group_by(|d| d.weeknum()) // Doesn't exist
            .into_iter()
            .map(|(_, week)| {
                //More processing...
            })
    })
```
I saw that there was `week_from_sun` and `week_from_mon` in the `chrono::format::parsed::Parsed`, but I don't know if there is a direct way to use those on `Datelike` things.

**Comment by lifthrasiir** [comment]
[`Datelike::isoweekdate`](https://docs.rs/chrono/0.3.0/chrono/trait.Datelike.html#tymethod.isoweekdate) is *almost* what you want, but its definition of week number is strictly based on [ISO week date](https://en.wikipedia.org/wiki/ISO_week_date). Probably we may want to have a `Week` type strictly dedicated for conversion to many other week numbering systems.

**Comment by robbym** [comment]
Oh, I don't know how I missed that, thanks. Yes it would be nice to have the ability to choose between week numbering systems. Maybe pass in a Weekday parameter to specify the day of the week to start on? I know most people use Sunday and Monday as the "start" of a week, but passing in a Weekday offset seems to be most general. IDK.

**Comment by pitdicker** [comment]
Given that there is [`Datelike::isoweekdate`](https://docs.rs/chrono/0.3.0/chrono/trait.Datelike.html#tymethod.isoweekdate) and we have https://github.com/chronotope/chrono/issues/405 for other (non ISO) week definitions this issue can be closed.
