### ISSUE TITLE
string parse with user specified format.

### ISSUE THREAD

**Issue by stmtk1** [chronotope/chrono#1407]
Some library implements `strptime`. This function parses a DateTime in a user-specified format. This function can be used to support a variety of formats.

**Comment by pitdicker** [comment]
Are you looking for something like [`DateTime::parse_from_str`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.parse_from_str)?

The [`strftime`](https://docs.rs/chrono/latest/chrono/format/strftime/index.html) module shows out supported syntax.

**Comment by stmtk1** [comment]
Yes. I will use this function. Thanks
