### ISSUE TITLE
Help understanding Parsing error: NotEnough while using parse_from_str 

### ISSUE THREAD

**Issue by miketwenty1** [chronotope/chrono#1422]
I'll call "`to_string()`" on a `DateTime<Utc>`.
Later I want to take this string that looks like this: "`2024-02-10 06:44:34.499 UTC`" and turn it back into a `DateTime<Utc>`.

```rust
let date_str = "2024-02-10 06:44:34.499 UTC";    
let format = "%Y-%m-%d %H:%M:%S%.3f %Z";

// this failed with NotEnough and ParseError: input is not enough for unique date and time
let tryparse = DateTime::parse_from_str(date_str, format); 

// Code doesn't make it here, but I suppose this would be the way 
// to finish the conversion from the String back to DateTime<Utc>
let datetime_utc = tryparse.with_timezone(&Utc);
```

What am I doing wrong?

**Comment by pitdicker** [comment]
You are doing nothing wrong, it is a limitation we currently have unfortunately. See https://github.com/chronotope/chrono/issues/38.

Not tested, but if you skip the ` UTC` part, parse to `NaiveDateTime` and then convert it to `DateTime<Utc>` it should work:
```rust
let date_str = "2024-02-10 06:44:34.499 UTC";    
let format = "%Y-%m-%d %H:%M:%S%.3f UTC";

let datetime_utc = NaiveDateTime::parse_from_str(date_str, format)?.and_utc(); 
```

**Comment by miketwenty1** [comment]
@pitdicker thank you it worked. Feel free to keep open for tracking or close.

**Comment by pitdicker** [comment]
Good :smile:. I'll leave #38 as the issue tracking this.
