### ISSUE TITLE
Different performance between UTC and local

### ISSUE THREAD

**Issue by josephDunne** [chronotope/chrono#143]
I have the following two benchamrks:
```
    #[bench]
    fn local_timestamp(bench: &mut Bencher) {
        bench.iter(|| Local.timestamp(100, 100))
    }

    #[bench]
    fn utc_timestamp(bench: &mut Bencher) {
        bench.iter(|| UTC.timestamp(100, 100))
    }
```

and the results are:

```
test local_timestamp ... bench:       3,025 ns/iter (+/- 218)
test utc_timestamp   ... bench:          11 ns/iter (+/- 0)
```

This was unexpected. I didn't see anything anything in the docs that would have warned me. Is this making a system call somewhere or something?

OS: OSx

**Comment by lifthrasiir** [comment]
`Local` goes through the system's `localtime` library function which tends to be not very fast. This is quite expected.

**Comment by josephDunne** [comment]
Ok. So Local is less of a time zone and more of a library implementation choice? I'll read the Offset module and see if there is a function to get the local offset of the machine at runtime.
