### ISSUE TITLE
Inconsistent crate features documentation

### ISSUE THREAD

**Issue by edmorley** [chronotope/chrono#1434]
PR #1343 added a new `now` feature, however, this feature is only documented in `README.md` and not in the features list on `docs.rs`.

Compare README.md:
https://github.com/chronotope/chrono/blob/3016c30014064bd1c67d285bd23c9e232b9efb80/README.md?plain=1#L49-L67

With the crate rustdocs:
https://github.com/chronotope/chrono/blob/3016c30014064bd1c67d285bd23c9e232b9efb80/src/lib.rs#L20-L44

I see there are also some differences in the other features listed under "optional features" too.

**Comment by pitdicker** [comment]
@edmorley Thank you for reporting this. Would you be interested in making a PR to straighten it out?
We should also document or at least mist the extra `rkyv` features.

**Comment by edmorley** [comment]
I've opened #1455 - happy to make further wording/... adjustments if needed (or feel free to push to the PR directly if easier) :-)
