### ISSUE TITLE
the trait `serde::Deserialize<'_>` is not implemented for `chrono::DateTime<chrono::UTC>`

### ISSUE THREAD

**Issue by FractalMatt** [chronotope/chrono#144]
Getting a bunch of these errors, guessing this needs to be fixed on your side?  Thanks!!

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Serialize` is not satisfied
  --> post-dto/src/lib.rs:31:39
   |
31 | #[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]//RustcDecodable, RustcEncodable)]
   |                                       ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize<'_>` is not satisfied
  --> post-dto/src/lib.rs:31:50
   |
31 | #[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]//RustcDecodable, RustcEncodable)]
   |                                                  ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::SeqAccess::next_element`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize<'_>` is not satisfied
  --> post-dto/src/lib.rs:31:50
   |
31 | #[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]//RustcDecodable, RustcEncodable)]
   |                                                  ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::MapAccess::next_value`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Serialize` is not satisfied
  --> post-dto/src/lib.rs:58:39
   |
58 | #[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]
   |                                       ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize<'_>` is not satisfied
  --> post-dto/src/lib.rs:58:50
   |
58 | #[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]
   |                                                  ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::SeqAccess::next_element`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize<'_>` is not satisfied
  --> post-dto/src/lib.rs:58:50
   |
58 | #[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]
   |                                                  ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::MapAccess::next_value`

**Comment by Sunspar** [comment]
Sounds like you may be using 0.9.x serde with chrono 0.3.1. If thats true, you'll need to either a) pin chrono to 0.3.0 or b) migrate your application to use serde 1.0.

I can confirm that the following versions play nicely:
```
chrono 0.3.0
serde 0.9.15
serde_derive 0.9.15
serde_json 0.9.10
```

**Comment by FractalMatt** [comment]
Thank you for the fast response!

Yeah, that makes sense.  Unfortunately I definitely need to use serde 1.0 for another library and I don't think you can tell it use this version of the library in this place.. this other version in the other place.

So looks like it needs to be upgraded.

The other option I heard is that I can create my own wrapper around chrono and do it that way.  I guess might as well do it in a way and host it somewhere seperate on github or just to push it here or something so that it can be used in other places :(

Or do you know if there are plans to update this to Serde? Given the lack of updates in quite a while.. guessing this one is dead and I should clone it.

Thanks.

**Comment by Sunspar** [comment]
I'm not a chrono maintainer; just someone who came across the same issue earlier this evening, so I can't say how fast any fixes would get pushed through. :P

But just for clarity, what versions of various serde libraries, alongside chrono, are found in your Cargo.lock file?

**Comment by FractalMatt** [comment]
What... it says that there actually was a commit two days ago that provided serde v1 support... 

Huh. You are basically right.  OH I'm stupid... I have a submodule within my main project.  Updated the toml for the main project, but not the submodule.  Very awesome that I don't have to fix this myself!

Thanks again Sunspar!

**Comment by Sunspar** [comment]
Ah. That'd do it I suppose. Glad everything worked out. :)
