### ISSUE TITLE
RFC: add feature "abi_stable" and make types abi stable

### ISSUE THREAD

**Issue by gwy15** [chronotope/chrono#1446]
Hello. In my project, I'm using Rust to load a dynamic library from an executable, and I'm utilizing certain chrono types across the ABI (Application Binary Interface) boundary. To ensure that the program does not crash, I'm employing the crate abi_stable to guarantee that the layouts of types passing through the ABI boundary are consistent.

At present, I have created my own fork of chrono and added an "abi_stable" feature to it. This modification ensures that types such as DateTime<Utc> maintain ABI stability and can be safely passed through ABI boundaries. I am interested in contributing this modification to the upstream repository. What are your thoughts on this idea?

**Comment by pitdicker** [comment]
I don't understand this request and its consequences well enough.

- What stability guarantees would we have to give around our internal representation?
- How does this work with `DateTime`, which takes a generic `TimeZone` that may not come from chrono?
- Is the `abi_stable` crate the way to go and getting some acceptance in the ecosystem? It exists for 5 years, but only has 1200 downloads/day.
- Is any type supported, such as `NonZero*`?
- What is the difference with making some types `#[repr(C)]1?
- Is this something that can't be implemented in another crate? Why not?

> At present, I have created my own fork of chrono and added an "abi_stable" feature to it.

Could you point to your branch (may be unpolished)?

**Comment by pitdicker** [comment]
Another question. How is the safety story for `abi_stable`?
Rust has an unstable ABI, this crate offers a workaround. `abi_stable` has its own [unsafe_code_guidelines](https://docs.rs/abi_stable/0.11.3/abi_stable/docs/unsafe_code_guidelines/index.html). What transmutes or things is it doing? Has anyone vetted this crates safety? Is there a chance it may break with a future rust version?

**Comment by pitdicker** [comment]
> How is the safety story for `abi_stable`?

This [comment](https://github.com/rodrimati1992/abi_stable_crates/issues/46#issuecomment-751875355) makes me uneasy:

> 😦 This would be two orders of magnitude more work than every other time that the compiler decided to break my code combined.

It shows there is nontrivial unsafety, in a way that may not agree with the opinions of the rust language/compiler.

**Comment by gwy15** [comment]
- The main reason I want to introduce abi_stable into chrono, instead of purely using `#[repr(C)]`, is that it would provide a trait (`StableAbi`) and provides a link of trust.
- There are no stability guarantees that chrono has to give. Let's say there's a breaking changes in memory layout, executables and dynamic libraries that replys on two different versions of chronos should detect the different memory layout in runtime using the StableAbi crate and thus prevents crashing, which is the reason I want to introduce abi_stable.
- AFAIK, in my implementation, I bounded the `StableAbi` trait to only implement on Timezone that implements `StableAbi`.
- AFAIK, abi_stable is currently the only way to do this (runtime check memory layout and abi stability)
- StableAbi is implemented for NonZero* and Option<NonZero*>, but not all types (those who do not guarantees a memory layout stability in rust reference)

**Comment by gwy15** [comment]
This is the proposed commit: https://github.com/chronotope/chrono/commit/81f0c1ab50f11d3f84d68172abfe946b3771c7fd

**Comment by gwy15** [comment]
I agree that my use case may not be that common (putting a lot of computation and business code in dynamic library to keep the core code clean, and passing structs through ffi boundards). And I can totally understand that for that, introducing such a lesser-used crate into chrono may not be accepted.

But for those do have this use case, since Rust does not provide a stable ffi, abi_stable is by far the best solution. And it is exactly the fact that it is lesser-used, unlike serde which most of crates provide features, not many, actually very few crates provides this feature. And due to the orphan rule, I can only fork and modify structs passing through ffi boundary.

**Comment by djc** [comment]
Given the lack of popularity of the abi_stable crate, I don't think we should do this. Note also that if we commit to abi_stable 0.11.x in chrono 0.4.x we can't bump abi_stable to 0.12.x or later on chrono 0.4.x because this dependency will become part of our public API.

I think your best bet would be either on using some kind of fast serialization (like postcard or rkyv) or (longer term) on the efforts to provide Rust with a more stable ABI.
