### ISSUE TITLE
Consider including the `T` in Display of DateTime

### ISSUE THREAD

**Issue by withoutboats** [chronotope/chrono#147]
Currently, you cannot roundtrip a DateTime to a String through `ToString` and back with `FromStr`, because `FromStr` rejects strings without the `T` between the date and time, and `ToString` does not include it. This is pretty surprising behavior IMO, and it doesn't seem harmful to include the `T` in the displayed output anyway.

**Comment by lifthrasiir** [comment]
If you are talking about `DateTime` (instead of `NaiveDateTime`) this is much harder because it can display any string the `Offset` implementation chose to display. For example, `DateTime<UTC>` will print something like `2017-05-11 02:50:47 UTC` right now.
