### ISSUE TITLE
`UTC` should be `Utc` in idiomatic Rust

### ISSUE THREAD

**Issue by LukasKalbertodt** [chronotope/chrono#148]
Abbreviations in `UpperCamelCase` names shouldn't be completely uppercase. I can't find a link to a styleguide right now, but it's consistently done that way in the standard library:

- `TcpStream` (instead of `TCPStream`)
- `Rc`, `Arc` and `Cow` (instead of `RC`, `ARC` and `COW`)
- `AsciiExt`, `DecodeUtf16Error`
- ...

I've seen this pattern in most crates, too. And some text editors already highlight `SCREAMING_SNAKE_CASE` in a different way than types, which is confusing.

Please consider renaming `UTC` to `Utc` with the next major version bump ^_^

Edit: I don't know if this applies to other names in this library as well; those should be changed, too, of course.

**Comment by alexbool** [comment]
+1.
There's also a case with something like `MSSQLXMLJDBCException` :)

**Comment by Stargateur** [comment]
@lifthrasiir Why this doesn't trigger a new version ? This is breaking change.
