### ISSUE TITLE
Deserializing DateTime from unix timestamp is not implemented, despite description

### ISSUE THREAD

**Issue by jmaximusix** [chronotope/chrono#1484]
The Deserialize Trait can't deserialize DateTimes from timestamps despite the error message you get. I tried tracking it down in the source code, I hope the cited references are correct.

The Deserialize Trait only calls the `deserialize_str()` function

https://github.com/chronotope/chrono/blob/f4adc28dce9a139ef17c7044e2adafde029cb17d/src/datetime/serde.rs#L75-L82

where, in spite of the `expecting()` stating it accepts **"a formatted date and time string or a unix timestamp"** it only calls the `parse()` function

https://github.com/chronotope/chrono/blob/f4adc28dce9a139ef17c7044e2adafde029cb17d/src/datetime/serde.rs#L53-L66

which in turn is implemented to only try and deserialize rfc3339 strings

https://github.com/chronotope/chrono/blob/f4adc28dce9a139ef17c7044e2adafde029cb17d/src/format/parse.rs#L523-L534

**Comment by pitdicker** [comment]
That error message, "a formatted date and time string or a unix timestamp", seems not right indeed.

We do not really have a solution yet. There is an old PR to add deserializing from strings to the existing timestamp deserializers (https://github.com/chronotope/chrono/pull/926). And another one to add full string serialization and deserialization modules (https://github.com/chronotope/chrono/pull/1067).
