### ISSUE TITLE
Doc links go to 0.3.0 not 0.3.1

### ISSUE THREAD

**Issue by daboross** [chronotope/chrono#149]
I can make a PR for this, but it seems like it'd be more effort to merge than to just change in-tree. 

README.md states "chrono 0.3.0" and has a docs badge pointing to chrono 0.3.0, and [`lib.rs`'s html_root_url](https://github.com/chronotope/chrono/blob/master/src/lib.rs#L348) points to chrono `0.3.0`.

**Comment by lifthrasiir** [comment]
Whoops. Yeah, I forgot to run that step (having made a release after some months). Probably I should make the entire process a checklist.

**Comment by daboross** [comment]
Thanks!
