### ISSUE TITLE
function Utc::now().checked_add_signed raised wrong error

### ISSUE THREAD

**Issue by Anoencs** [chronotope/chrono#1496]
![image](https://github.com/chronotope/chrono/assets/57495997/ca60a9b5-2fe9-4e5e-8c0a-2bbaa76a2b81)
I have that error when compile my server although my init duration variable is: 
let duration = Duration::try_hours(3).unwrap()

**Comment by pitdicker** [comment]
@Anoencs There are multiple methods that can return an `Option`. Can you double check you unwrapped the right result? We surely aren't returning `Option<Option<TimeDelta>>` from `try_hours`.

**Comment by Anoencs** [comment]
![bug](https://github.com/chronotope/chrono/assets/57495997/01a9050a-1d23-4bdf-9dc7-8a12c0d9f64c)
I'm trying to use unwrap on my duration variable, but I'm encountering conflicting errors. On one hand, I get an error saying that TimeDelta doesn't have a method called unwrap. On the other hand, it says my variable isn't a TimeDelta but rather an Option<TimeDelta>.

**Comment by djc** [comment]
We can't see the surrounding code, so just these error snippets aren't helpful. If you come up with a minimal reproducing example we might be able to help you, although it is more likely that you'll realize where your confusion comes from.

**Comment by Anoencs** [comment]
> We can't see the surrounding code, so just these error snippets aren't helpful. If you come up with a minimal reproducing example we might be able to help you, although it is more likely that you'll realize where your confusion comes from.

![image](https://github.com/chronotope/chrono/assets/57495997/cbecdc24-e05c-4f7f-bbdb-db418afb3300)
That my code where it raise error look like above, thank you for your help

**Comment by pitdicker** [comment]
It seems to me you only need to remove the `unwrap()` on `checked_add_signed(duration.unwrap())`.

**Comment by Anoencs** [comment]
![image](https://github.com/chronotope/chrono/assets/57495997/eb62da9b-44a2-4d57-a912-56eda7826b48)
Once I remove the unwrap method call, I get an error indicating that my duration variable is actually of type Option<TimeDelta> instead of just TimeDelta.

**Comment by djc** [comment]
That's 30 lines down, though, so might be a different `duration`.

Anyway, this is not a chrono issue and the chrono issue tracker is not the best place to help you figure out compiler errors.
