### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by lifthrasiir** [chronotope/chrono#150]
Historically the new releases were solely made by @lifthrasiir, but this list should make the process more reproducible.

- Of course, the CI should be all green.
- Bring `CHANGELOG.md` up to date. Ideally this should equal to the final commit message as well.
- Bump the version number in `src/lib.rs`.
- Run `make authors readme`. This will update `README.md` and `AUTHORS.txt`; those two files should not be altered directly.
- Bump the version number in `Cargo.toml`.
- Run `make test`. This is same to the CI test and acts as the last-minute safety guard.
- Run `cargo package` if `Cargo.toml` has been changed in other ways. Sometimes it is required to use the nightly Cargo due to the `Cargo.toml` format changes.
- Review and commit the changes. *Do not push them!*
- Run `cargo publish`.
- Tag the commit as `vN.N.N`, and push everything to the master.

**Comment by theduke** [comment]
It might be a good idea to require every pull request to also update the changelog if APIs or behaviour are changed.
