### ISSUE TITLE
Is there a way to instantiate DateTimes over a generic TimeZone type?

### ISSUE THREAD

**Issue by jesse1412** [chronotope/chrono#1532]
Is there a way to create a trait+struct, which is generic over a TimeZone, which can get the current DateTime with said generic timezone? Everything I've tried has failed because all of the DateTime constructors expect an _instance_ of a TimeZone, and I can't find any way in Chrono to create a TimeZone instance from a TimeZone type.

Is the only way to do this to store a concrete TimeZone within the struct?

Example code:

```rust
use chrono::TimeZone;

pub trait Job {
    type TZ: TimeZone;

    fn get_last_run_date(&self) -> Option<Self::TZ>;
}

struct JobForSomeTimeZone<TZ> {
    last_job_dt: Option<TZ>,
}

impl<TZ> Job for JobForSomeTimeZone<TZ>
where
    TZ: TimeZone,
{
    type TZ = TZ;
    fn get_last_run_date(&self) -> Option<Self::TZ> {
        self.last_job_dt.clone()
    }
}

impl<TZ> JobForSomeTimeZone<TZ>
where
    TZ: TimeZone,
{
    pub fn do_job(&mut self) -> Option<TZ> {
        self.last_job_dt = // How do we get the current time in timezone TZ while staying generic?
        self.last_job_dt.clone()
    }
}
```

Thanks for any help.

**Comment by pitdicker** [comment]
I don't think this is possible unfortunately. Creating a `TimeZone` object is not part of the `TimeZone` trait.

If you have a `DateTime<Tz: TimeZone>` however you can recreate a `TimeZone` object from it with [`DateTime::timezone()`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.timezone).
That makes use of the [`TimeZone::from_offset`](https://docs.rs/chrono/latest/chrono/trait.TimeZone.html#tymethod.from_offset) method.

Would that help?

**Comment by jesse1412** [comment]
> I don't think this is possible unfortunately. Creating a `TimeZone` object is not part of the `TimeZone` trait.
> 
> If you have a `DateTime<Tz: TimeZone>` however you can recreate a `TimeZone` object from it with [`DateTime::timezone()`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.timezone). That makes use of the [`TimeZone::from_offset`](https://docs.rs/chrono/latest/chrono/trait.TimeZone.html#tymethod.from_offset) method.
> 
> Would that help?

Thanks for the quick reply. I think this is essentially the same as storing the TimeZone for my case (as I wanted the initial DateTime to be optional). I'll do a bit more digging to see if I can find any nice solutions to this, but happy to close the issue for now. If any ideas come to mind for making this available Chrono-side, I can open another issue/PR.

Thanks.

**Comment by pitdicker** [comment]
Thinking about it some more storing a value is the right solution.

A *type* that implements `TimeZone` is not the same thing as a *time zone*.

For example knowing that the generic type is `FixedOffset` doesn't tell you much. The offset can be -06:00, +03:00, etc. Just the type is not enough to create a `DateTime`, you need to know the value of the type.
