### ISSUE TITLE
Make Weekday::num_days_from public

### ISSUE THREAD

**Issue by NickUfer** [chronotope/chrono#1560]
Currently [`Weekday::num_days_from`](https://github.com/chronotope/chrono/blob/0cfc405d3e93b1f4e8c6fd37a51449b6be7edb2c/src/weekday.rs#L156-L159) is only public inside the crate, but this function is useful for crates using this lib too.
For example I had to write some code with different behavior for the united states and how they handle some things different than ISO 8601 and I could have used `num_days_from_monday` and `num_days_from_sunday` to solve my problem... but this requires another if statement which I could remove if `Weekday::num_days_from` was public.
I'm pretty sure there are more use cases for this besides that.

**Comment by pitdicker** [comment]
I agree. #1249 is open to make it public with the name `days_since`.

**Comment by pitdicker** [comment]
It will be public in the next release.
