### ISSUE TITLE
`gh-pages` branch

### ISSUE THREAD

**Issue by pitdicker** [chronotope/chrono#1566]
At some point documentation for chrono was hosted on https://lifthrasiir.github.io/rust-chrono/. 8 years ago it was changed to redirect from all pages to docs.rs. Now that chrono has moved to the chronotope organization the original url is dead.
We still have the old `gh-pages` branch, and that makes a never-used https://chronotope.github.io/chrono/ redirect to docs.rs.

Is it time to delete our `gh-pages`?

**Comment by djc** [comment]
Is the original or current URL still referenced somewhere?

**Comment by pitdicker** [comment]
Not that I know of since chrono 0.3.0.

**Comment by djc** [comment]
Okay, let's ditch it!
