### ISSUE TITLE
How do I get the raw underlying bytes of a `NaiveDate`

### ISSUE THREAD

**Issue by 617a7aa** [chronotope/chrono#1574]
Sorry, I can't see an ability to convert to and from bytes directly without formatting to a string. Is it possible?

**Comment by pitdicker** [comment]
We don't have a way to do so, how a `DateTime` is represented as bytes is an implementation detail.
May I ask your use case?

**Comment by 617a7aa** [comment]
I'm building a digest from some dates and other data fields and want to make sure it's stable. I don't know if the string formatted version will change over time whereas the raw bytes is less likely to be

**Comment by 617a7aa** [comment]
Thank you!
