### ISSUE TITLE
Datetime Parse Error when converting rfc2822 date to chrono Datetime

### ISSUE THREAD

**Issue by SamTV12345** [chronotope/chrono#1580]
Hi Chrono maintainers,

I am maintaining a podcast management tool written in Rust. When saving podcast episodes I use the date of recording of mentioned episode. Unfortunately some podcast episodes return a parse error impossible. Below code snippets errors withb a ParseError. Do you have an idea why? I checked multiple validators and they all said this is encoded in rfc2822 format.

```Rust
    let date_str = "Fri, 03 Jul 2014 08:00:00 +0100";
    let date = DateTime::parse_from_rfc2822(date_str).unwrap().with_timezone(&Utc);
    println!("{}", date);
```

**Comment by pitdicker** [comment]
The format is valid according to RFC 2822, but the day of the week does not match the date. 2014-07-03 was a Thursday.
