### ISSUE TITLE
Wasm support for NaiveTime, NaiveDate and alike

### ISSUE THREAD

**Issue by madser123** [chronotope/chrono#1585]
I recently stumbled upon wanting to use a struct in javascript that returns a NaiveDate from one of its methods.

I added the `wasmbind` feature - However, i got the following error when compiling:

```
error[E0277]: the trait bound `NaiveDate: FromWasmAbi` is not satisfied
   --> src/time/timestamp.rs:233:30
    |
233 | #[cfg_attr(feature = "wasm", wasm_bindgen)]
    |                              ^^^^^^^^^^^^ the trait `FromWasmAbi` is not implemented for `NaiveDate`
    |
    = help: the following other types implement trait `FromWasmAbi`:
              bool
              char
              isize
              i8
              i16
              i32
              i64
              usize
            and 87 others
    = note: this error originates in the attribute macro `wasm_bindgen::prelude::__wasm_bindgen_class_marker` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Is there no wasm support for these types? I saw that there is wasm support for `DateTime` and `Offset` but not `naive` types?

**Comment by pitdicker** [comment]
I think you already found the answer. Chrono can only convert from `js_sys::Date` to `DateTime<Utc>`, which does not discard information such as the time and offset. Can you solve your problem by using `DateTime::date_naive()` and similar methods?

**Comment by madser123** [comment]
That makes a lot of sense. I might be able to - I will experiment a bit with this. Thank you for the quick reply 😄
