### ISSUE TITLE
Proposal: Release chrono 0.4 supporting serde 1, dropping rustc-serialize and rust < 1.15

### ISSUE THREAD

**Issue by quodlibetor** [chronotope/chrono#159]
Serde is growing more and more features and rustc-serialize has been dead for a long time. Keeping rustc-serialize support causes a significant amount of work, makes tests harder to write, and I still can't figure out how to make doctests for custom-derive work in travis in #125.

I think we could clean up a bunch of code and fix the annoyance that we're causing to the community in #146 and #156 by changing serde version and dropping old support in one fell swoop, rather than having to do another breaking change at a later date.

**Comment by quodlibetor** [comment]
Also bincode 1.0 does not support rustc-serialize, so if we ever want to support that we will need to drop support or go through some (probably extremely) uncomfortable contortions to maintain old and new bincodes.

**Comment by quodlibetor** [comment]
Oh, I was wrong, it's _going_ to drop support for rustc-serialize, [once it's released](https://github.com/TyOverby/bincode/blob/master/changelist.org)

**Comment by lifthrasiir** [comment]
I personally have no problem in keeping Rustc-serialize support (they essentially have the same code as Serde support for now, and can be left as is without breaking others). As a data point, Rust-url 1.5.0 (released last week) still continues to support it.

**Comment by dtolnay** [comment]
I agree with @quodlibetor and I would recommend dropping rustc-serialize.

The `url` crate is in a totally different situation because they are preserving compatibility back to their 1.0.0 release in April 2016. If they were releasing an 0.4.0 this week, there would be no rustc-serialize in it.

If somebody needs to continue using an ancient serialization library, they can easily use an ancient version of chrono as well. Cargo makes that easy. (Well, except when 0.3.1 is a breaking change.)

**Comment by quodlibetor** [comment]
@lifthrasiir Rustc-Serialize has the same code as Serde now, but when I tried to implement #125 there are a couple of meaningful differences, Serde makes it [trivial](https://github.com/chronotope/chrono/pull/125/files#diff-8daac88609c52af7718d9f334e7a2bf7R729) to support deserializing from multiple types (positive/negative integers) trivially, I _think_ it's possible to do correctly in Rustc-Serialize but it's a bit more work, based on [the generic Decodable example](https://docs.rs/rustc-serialize/0.3.24/rustc_serialize/trait.Decodable.html#examples). 

But the [field attributes that serde supports](https://serde.rs/field-attrs.html) (specifically `with`) are essential for the API to be reasonable. In order to do the same thing with Rustc-Serialize I'm pretty sure that we'd need newtypes (like I implemented [once](https://github.com/chronotope/chrono/pull/125/files#diff-8daac88609c52af7718d9f334e7a2bf7R22)) which makes the API *terrible*.

I don't think it would be reasonable to support Rustc-Serialize in the eventual Chrono 1.0. If that's true, then it's a matter of _when_ we remove it. It might make sense to just document it as deprecated in this release, not support it for new features, and actually delete it in some later release. The cost for that is pretty cheap (although the tests are made more confusing and the errors a bit worse when making mistakes) and I'd be happy to do the work to update the docs if that would be satisfactory.

**Comment by lifthrasiir** [comment]
@quodlibetor I agree that evolving the serialization support for both crates would be very hard. What I thought is that we can leave Rustc-serialize support *as is* and remove it in 1.0.0, which seems to be exactly what you are proposing in the last paragraph. I'll do the necessary documentation updates.
