### ISSUE TITLE
Flatten intermediate implementation modules

### ISSUE THREAD

**Issue by lifthrasiir** [chronotope/chrono#161]
Currently types like `DateTime` are available both at `chrono::DateTime` and `chrono::datetime::DateTime`. I think modules like `chrono::datetime` are implementation details and should be hidden from the public visibility; that would greatly streamline the documentation as well.

I expect the following modules will remain after the flattening:

* `format`
* `format::strftime` (this sounds strange, but we have a bulk of documentation in this module and possibly some more internal types exposed in the future)
* `offset`
* `prelude`

All reexported types originally in the modules not included above will be publicly moved to the reexported position otherwise noted below:

* `chrono::date::{MIN, MAX}` will be renamed to `chrono::{MIN_DATE, MAX_DATE}`. Ideally this should be also associated consts.
* `chrono::naive::date::{MIN, MAX}` will be renamed to `chrono::{MIN_NAIVE_DATE, MAX_NAIVE_DATE}`. Same as above.
* `chrono::offset::utc::UTC` etc. will be moved to `chrono::offset::UTC` *and* reexported as `chrono::UTC`.

**Comment by quodlibetor** [comment]
I agree, this would be great.
