### ISSUE TITLE
`std::fmt::Display` implementation of `Weekday` does not honour width, alignment or fill

### ISSUE THREAD

**Issue by horazont** [chronotope/chrono#1620]
## Summary

The `Display` implementation of `Weekday` uses `Formatter::write_str`, which doesn't honour [width](https://doc.rust-lang.org/std/fmt/index.html#width) or [alignment and fill](https://doc.rust-lang.org/std/fmt/index.html#fillalignment).

## Reproducer

```rust
use chrono::Weekday;

fn main() {
    println!("Expected result: <{:X>10}>", format!("{}", Weekday::Mon));
    println!("Actual result: <{:X>10}>", Weekday::Mon);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e9d6cafc549ad505e6f932697fbda305))

## Expected result

`<XXXXXXXMon>`

## Actual result

`<Mon>`

**Comment by horazont** [comment]
Looking further, seems like the easy way out is to use [`Formatter::pad`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.pad) instead of `write_str`.

**Comment by djc** [comment]
Happy to review a PR for this!

**Comment by horazont** [comment]
There you go: https://github.com/chronotope/chrono/pull/1621
