### ISSUE TITLE
Chrono can't parse a date from iso8601

### ISSUE THREAD

**Issue by vityafx** [chronotope/chrono#163]
Some server sends me the date time in the json:

    "creationTime": "2017-06-22 13:32:16Z",

But I can't parse it neither trough `Datetime` nor `NaiveDateTime`. However, if I change the space between the date and the time to `T` as in `2017-06-22T13:32:16Z` it parses okay.

I could not find any information does this conform iso8601 or not, different sources say different answers, iso8601. If it is `iso8601` so the `chrono` must be able to parse it.

**Comment by quodlibetor** [comment]
[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations) (and [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.8)) both require the `T`.

The [readme](https://github.com/chronotope/chrono/blob/6f69ab758b14be76bf20fae0243cf8a469d7a483/README.md#date-and-time) contains examples for parsing a datetime that includes a space, if you'd like.

**Comment by vityafx** [comment]
@quodlibetor I don't parse it manually, I use `serde` for this. If I did that manually, I would have everything okay of course. I have also found that information but some resources also treat a datetime stamp without `T` as correct, however, I have not seen anything like that before today. I have told the api writer of the service I use to add `T` to the timestamp.

**Comment by quodlibetor** [comment]
In that case if you need to use it you can write `my_custom_deserializer` module (like [we have for timestamps](https://github.com/chronotope/chrono/blob/6f69ab758b14be76bf20fae0243cf8a469d7a483/src/naive/datetime.rs#L1610-L1717)) that parses your format, if the service you're interacting with doesn't support it.

Something like the following (untested) code:

```rust
pub mod custom_deserialize {
    use std::fmt;
    use serde::de;

    use chrono::NaiveDateTime;

    struct NaiveDateTimeFromMyFormatVisitor;

    pub fn deserialize<'de, D>(d: D) -> Result<NaiveDateTime, D::Error>
        where D: de::Deserializer<'de>
    {
        Ok(try!(d.deserialize_str(NaiveDateTimeFromMyFormatVisitor)))
    }

    impl<'de> de::Visitor<'de> for NaiveDateTimeFromSecondsVisitor {
        type Value = NaiveDateTime;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result
        {
            write!(formatter, "a datetime string")
        }

        fn visit_str<E>(self, value: &str) -> Result<NaiveDateTime, E>
            where E: de::Error
        {
            DateTime::parse_from_str(value, "%Y-%m-%d %H:%M:%S%z")
                .map_err(|e| E::custom(format!("Parse error {} for {}", e, value)))
        }
    }
}
```

Should allow you to use serde's [`#[serde(deserialize_with = "path")]`](https://serde.rs/field-attrs.html) attribute in your struct.

**Comment by vityafx** [comment]
@quodlibetor thanks a lot, I will try that if the resource refuse to support the correct version of time stamp.

**Comment by vityafx** [comment]
@quodlibetor the service api author gave me this [link](https://en.m.wikipedia.org/wiki/ISO_8601#cite_note-21) which says the `T` may be omitted. What do you think?

**Comment by quodlibetor** [comment]
Ha, the specific text in the note in wikipedia is:

> 4.3.2 NOTE: By mutual agreement of the partners in information interchange, the character [T] may be omitted in applications where there is no risk of confusing a date and time of day representation with others defined in this International Standard.

so, if _you_ agree that the `T` may be omitted then the format can still be considered ISO-8601 compliant :smile: It still wouldn't be RFC 3339 compliant, though.

Adding the ability to accept the space would require an attempted parse and a fallback. That seems like an unacceptable hidden performance hit for default behavior.

I'll investigate alternate parsing techniques, but it won't be super fast, our current code is pretty... specific.

If you want to accept strings in the format that you are currently receiving I'd recommend going with the alternate deserialization I described in a previous comment.
