### ISSUE TITLE
DateTime::parse_from_rfc3339 cannot parse BC dates

### ISSUE THREAD

**Issue by victorteokw** [chronotope/chrono#1631]
Thanks for this great crate!

I parse BC date with `parse_from_rfc3339`, which errors:
```
DateTime::parse_from_rfc3339("-0001-11-21T14:08:00.591Z")
```

How to correctly parse date BC?

Thanks

**Comment by djc** [comment]
You can use `parse_from_str()` to specify the format you expect. See also the docs:

> Why isn’t this named `parse_from_iso8601`? That’s because ISO 8601 allows representing values in a wide range of formats, only some of which represent actual date-and-time instances (rather than periods, ranges, dates, or times). Some valid ISO 8601 values are also simultaneously valid RFC 3339 values, but not all RFC 3339 values are valid ISO 8601 values (or the other way around).
