### ISSUE TITLE
Way to spell `TimeDelta::MIN` on older chrono versions

### ISSUE THREAD

**Issue by ngoldbaum** [chronotope/chrono#1640]
Over at https://github.com/PyO3/pyo3/pull/4785 we're confused about how to update a test that uses `min_value` to not emit a deprecation warning on the newest chrono version but still be runnable on our minimum supported version. The suggestion in the deprecation message is only possible on the latest version of chrono.

**Comment by djc** [comment]
Why do you have an older minimum version of chrono?

**Comment by djc** [comment]
Yes, it doesn't seem like a big deal. Could go with 0.4.38 if that's new enough since 0.4.39 is relatively recent.

**Comment by ngoldbaum** [comment]
Cool, we'll just do `[allow(deprecated)]` I think. Thanks for the advice!
