### ISSUE TITLE
 DateTime::from_timestamp_millis zero error

### ISSUE THREAD

**Issue by zomem** [chronotope/chrono#1642]
```rust
let dt = DateTime::from_timestamp_millis(1734090000000).unwrap()
println!("dtdtdtdt,, {}", dt);

is 
2024-12-13 11:40:00 UTC

hope is 
2024-12-13 11:40:00.000 UTC
```

**Comment by djc** [comment]
This doesn't make sense. The output format doesn't depend on the value was constructed (and extra trailing zeros are ignored). If you want the timestamp to include milliseconds, use [formatting strings](https://docs.rs/chrono/latest/chrono/format/strftime/index.html) with `%.f` or `%.3f`.
