### ISSUE TITLE
formatting chrono time with G shows one year later than it should

### ISSUE THREAD

**Issue by sbuzzard** [chronotope/chrono#1644]
See this [rust playground snippet](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4f511d2aa72447efeeb2436282c5f154) and below screenshot for details.  It wasn't doing this a week or so ago so must have been triggered closer to end of the year.   `Utc:now()` is getting formatted to the correct time but year of 2025, using `DateTime::format` instance method.  Appologies if this is a duplicate.  Also happens with latest (0.4.39).

<img width="1435" alt="Screenshot 2024-12-30 at 12 11 26 PM" src="https://github.com/user-attachments/assets/7ad8f53b-dab0-4f20-856e-f335e840afcd" />

**Comment by sbuzzard** [comment]
I guess it's because year comes from `iso_week.year()` in formatting and the end of this week the year will be 2025 ...

**Comment by djc** [comment]
Yes, this seems to work as intended. Why not `%Y`?

**Comment by sbuzzard** [comment]
doh, appologies ...
