### ISSUE TITLE
Why chrono::Date does not have serde traits implemented?

### ISSUE THREAD

**Issue by vityafx** [chronotope/chrono#167]
Why `Date` structure does not implement `Serialize` and `Deserialize` traits?

**Comment by quodlibetor** [comment]
[The Documentation](https://docs.rs/chrono/0.4.0/chrono/struct.Date.html) (for version 0.4) states:

> This type should be considered ambiguous at best, due to the inherent lack of precision required for the time zone resolution. For serialization and deserialization uses, it is best to use NaiveDate instead.

You can get a `NaiveDate` via the `naive_utc` method.
