### ISSUE TITLE
Quickcheck Arbitrary support

### ISSUE THREAD

**Issue by clarfonthey** [chronotope/chrono#177]
Would be nice to have!

**Comment by quodlibetor** [comment]
I probably agree -- I've played with adding cargo fuzz, but haven't invested much time. I'm not very familiar with quickcheck, what would "quickcheck arbitrary support" look like?

**Comment by PureW** [comment]
It could potentially look something like https://github.com/chronotope/chrono/pull/298

**Comment by pitdicker** [comment]
Added in https://github.com/chronotope/chrono/pull/849.
