### ISSUE TITLE
formatting in RFC3339 has a different format on different platforms

### ISSUE THREAD

**Issue by Thomasdezeeuw** [chronotope/chrono#178]
On MacOS the nanoseconds are printed with 6 numbers after the decimal, while Linux and Window prints it with 9 numbers.

```
2017-08-04T13:57:08.427902+00:00 // MacOS
2017-08-04T13:57:08.427902838+00:00 // Linux, Windows
```

Any change we can change this to have a more constant experience cross platform?

**Comment by Thomasdezeeuw** [comment]
I think I found the cause here: https://github.com/chronotope/chrono/blob/42a7c8e5899b1e0087294779df27c8ecd095fa8c/src/naive/time.rs#L1144-L1164. Would a change be accept that always print 6 numbers after the decimal for the nanoseconds?

**Comment by quodlibetor** [comment]
I wouldn't really want to drop 3 significant digits on Linux and Windows just because MacOS only provides microsecond precision. Chrono also generally uses the number of digits of precision (0, 3, 6, 9) to signify how much precision is available, so defaulting to 9 digits seems wrong.

If you want deterministic output I'd recommend using a format string with the `%6f` format specifier. I'm open to more conversation around this, but changing the output of a method that's used by so many crates would require a pretty strong motivation, IMO.

**Comment by Thomasdezeeuw** [comment]
I'm currently using the following code:

```
    const FORMAT_ITEMS: &'static [Item<'static>; 1] = &[Item::Fixed(Fixed::RFC3339); 1];
    let timestamp = chrono::Utc::now()
        .format_with_items(FORMAT_ITEMS.iter().cloned());
```

How would I change the format to deterministic in that case?

**Comment by quodlibetor** [comment]
I think this does what you want:

```rust
#![allow(dead_code)]
extern crate chrono;

use chrono::format::StrftimeItems;
use chrono::format::Item;

fn format() {
    let res = StrftimeItems::new("%Y-%m-%dT%H:%M:%S%.6fZ")
        .map(|item| match item {
            Item::Error => Err(item),
            _ => Ok(item),
        })
        .collect::<Result<Vec<_>, _>>()
        .unwrap();
    println!("parsed out: {}", chrono::Utc::now().format_with_items(res.iter().cloned()));
}

fn without_parse() {
    use chrono::format::Item::*;
    use chrono::format::Numeric::*;
    use chrono::format::Pad::*;
    use chrono::format::Fixed::*;

    const ITEMS: &[Item<'static>] =  &[
        Numeric(Year, Zero),
        Literal("-"),
        Numeric(Month, Zero),
        Literal("-"),
        Numeric(Day, Zero),
        Literal("T"),
        Numeric(Hour, Zero),
        Literal(":"),
        Numeric(Minute, Zero),
        Literal(":"),
        Numeric(Second, Zero),
        Fixed(Nanosecond6),
        Literal("Z"),
    ];

    println!("const out: {}", chrono::Utc::now().format_with_items(ITEMS.iter().cloned()));
}

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        super::format();
    }

    #[test]
    fn const_works() {
        super::without_parse();
    }
}
```

Gives the output:

```
running 2 tests
parsed out: 2017-08-05T21:06:22.226824Z
test tests::it_works ... ok
const out: 2017-08-05T21:06:22.226699Z
test tests::const_works ... ok
```

Just, you know, don't do all those glob imports, please.

**Comment by quodlibetor** [comment]
I'm going to close this, feel free to keep this conversation going here, or we can re-open if you feel like the original request should be followed through on.

**Comment by Thomasdezeeuw** [comment]
@quodlibetor thanks I'll use you code instead.
