### ISSUE TITLE
Make format_from_items more efficient

### ISSUE THREAD

**Issue by quodlibetor** [chronotope/chrono#179]
It currently requires an iterator of clonable `Item`s, which isn't necessary, it should be possible with just a borrowed iteratable.

**Comment by pitdicker** [comment]
The current signature is similar to the one in 2017:
```rust
    pub fn format_with_items<'a, I, B>(&self, items: I) -> DelayedFormat<I>
    where
        I: Iterator<Item = B> + Clone,
        B: Borrow<Item<'a>>;
```

The iterator must be `Clone` because we need to be able to run it multiple times from the start.
It is possible to `Display` a `DelayedFormat` multiples times.
