### ISSUE TITLE
Format ms to DateTime

### ISSUE THREAD

**Issue by nihiluis** [chronotope/chrono#181]
how do I format this to DateTime?

"1503931187"

I have no idea and I can't find anything in the docs.

**Comment by nihiluis** [comment]
there is for seconds

Local.timestamp(1503931187, 0)

at least. 

is this left over intentionally or I just cant find it?

**Comment by quodlibetor** [comment]
right now we don't have anything for creating a datetime directly from milliseconds, the only option is, as you mentioned, to use one of the Tz types (including `Utc`) and their `.timestamp` constructor.
