### ISSUE TITLE
Support serialization with Serde on the `Date` Type

### ISSUE THREAD

**Issue by whmountains** [chronotope/chrono#182]
I need this.  I hope I'm not the only one.

**Comment by tmccombs** [comment]
How would it work? Would it serialize `date.naive_utc()`, `date.naive_local()`, or `date.naive_local()` with the time zone indicated somehow? 

> For serialization and deserialization uses, it is best to use NaiveDate instead.

Is there a use case where you want to use serialize a `Date` rather than a `NaiveDate`?

**Comment by dpc** [comment]
Ha. I was just googling for this. I just want to serialize some creation timestamp in UTC. I don't really care about how it's done. Something like ISO 8601 seems the way to go.

**Comment by dpc** [comment]
I am not very versed in chrono, but it seems to me that all types with timezones could just serialize to ISO 8601 full representation (with TZ included), and then deserialize to any other timedate type, with automatic timezone conversions.

**Comment by quodlibetor** [comment]
IIUC, a large part of the reason that this type doesn't implement serialization is that this type doesn't really make sense. 

It exists primarily to not lose information that existed in the `DateTime<Tz>` when you extracted the `Date` portion. Which, mostly, makes all the "convert back into `DateTime`" methods significantly more convenient. (Does that sound right @lifthrasiir ?)

So, really, the first thing that you want to do with a `Date` if don't care about converting it back into a `DateTime<Tz>` is to convert it into a `NaiveDate`. :-(

The docs are... kind of... clear about this. We could phrase it more strongly, or we could just allow serializing a `Date`, which IMO would involve just dropping the timezone in the default case. Given some time I would like to look into what other languages do to handle the "I want to convert into a `Date` and then back into a `DateTime` without losing the timezone" problem. Honestly I can't think of a time I have ever _had_ that problem.

The solution to the problem in the interim continues to be to use the result of `my_date.naive_utc()` for serialization.

**Comment by dpc** [comment]
I'm sorry, but I don't get it. :D

If I have `TimeDate<UTC>`, why can't it be serialized into `2017-09-26 20:08:39.603506017+01:00`?, and when I"m deserializing it back to `TimeDate<PST>` why can't I get corresponding time in PST? Naively, seems natural to me.

**Comment by tmccombs** [comment]
@dpc I'm not sure I follow. Are you suggesting that serializing a Date would be equivalent to converting to a DateTime and then serializing that?

**Comment by dpc** [comment]
Oh. So that's how I am confused. I was actually talking about `TimeDate`, not `Date`, and I've conflated the two, since `TimeDate<TZ>` does not seem to have `Serialize` implemented, and I had to use serde directives and helper functions.

Now that I see it, I agree that `Date<TZ>` is tricky, and having to convert it to `NaiveDate` for serialization kind of makes sense.

**Comment by dpc** [comment]
Should I create another issue for `impl SerdeStfuff  for TimeDate<TZ>`? Or did I just miss it?

**Comment by quodlibetor** [comment]
If you use the `serde` feature `DateTime` should already have all that implemented for it.

**Comment by quodlibetor** [comment]
I'm going to close this since I believe the original desire (to be able to serialize using serde) has been available since before 0.4. Feel free to re-open if I'm missing something.

**Comment by doivosevic** [comment]
I just wish I could have some struct which has Date<Tz> and be able do add Serialize and Deserialize without thinking too much or having to use some proxy types.
