### ISSUE TITLE
Parse failures on certain dates

### ISSUE THREAD

**Issue by alatiera** [chronotope/chrono#187]
I was parsing rss files  , which use rfc822 for the date format, and stumbled upon some cases where chrono was failing and I cant figure out why.

Even worse some of the times when calling parse_from_rfc2822(&foo) fails where when I copied the rfc2822 sequence from [here](https://docs.rs/chrono/0.4.0/src/chrono/format/mod.rs.html#490) they somehow succeed.

[Here](https://play.rust-lang.org/?gist=76e4b97e5b99dea1d5de13a6de158c8c&version=stable) is a playground gist that showcases it.

And here are the dates that fail:

```
let dates = vec![
        "Thu, 6 July 2017 15:30:00 PDT",
        "Mon, 10 July 2017 16:00:00 PDT",
        "Mon, 17 July 2017 17:00:00 PDT",
        "Mon, 24 July 2017 16:00:00 PDT",
        "Mon, 31 July 2017 16:00:00 PDT",
        "Thu, 30 Aug 2017 1:30:00 PDT",
        "Monday, 25 Sept 2017 5:30:00 PDT",
        "Wed, 20 Sep 2017 10:00:00 -0000",
        "Wed, 13 Sep 2017 10:00:00 -0000",
        "Wed, 09 Aug 2017 10:00:00 -0000",
        "Wed, 02 Aug 2017 10:00:00 -0000",
        "Wed, 26 Jul 2017 10:00:00 -0000",
        "Wed, 19 Jul 2017 10:00:00 -0000",
        "Wed, 12 Jul 2017 10:00:00 -0000",
        "Wed, 28 Jun 2017 10:00:00 -0000",
        "Wed, 21 Jun 2017 10:00:00 -0000",
        "Wed, 14 Jun 2017 10:00:00 -0000",
        "Wed, 07 Jun 2017 10:00:00 -0000",
        "Wed, 31 May 2017 10:00:00 -0000",
        "Wed, 24 May 2017 10:00:00 -0000",
        "Wed, 17 May 2017 10:00:00 -0000",
        "Wed, 10 May 2017 10:00:00 -0000",
        "Wed, 03 May 2017 10:00:00 -0000",
        "Wed, 19 Apr 2017 10:00:00 -0000",
        "Wed, 12 Apr 2017 10:00:00 -0000",
        "Wed, 05 Apr 2017 10:00:00 -0000",
        "Wed, 29 Mar 2017 10:00:00 -0000",
        "Wed, 22 Mar 2017 10:00:00 -0000",
        "Wed, 15 Mar 2017 10:00:00 -0000",
        "Wed, 08 Mar 2017 11:00:00 -0000",
        "Wed, 01 Mar 2017 11:00:00 -0000",
        "Wed, 22 Feb 2017 11:00:00 -0000",
        "Wed, 15 Feb 2017 11:00:00 -0000",
        "Wed, 08 Feb 2017 11:00:00 -0000",
        "Wed, 01 Feb 2017 11:00:00 -0000",
        "Wed, 25 Jan 2017 11:00:00 -0000",
        "Fri, 13 Jan 2017 18:38:00 -0000",
        "Wed, 20 Sep 2017 03:30:00 -0000",
        "Wed, 13 Sep 2017 03:15:00 -0000",
        "Wed, 06 Sep 2017 03:15:00 -0000",
        "Wed, 30 Aug 2017 03:15:00 -0000",
        "Wed, 23 Aug 2017 03:15:00 -0000",
        "Wed, 16 Aug 2017 03:15:00 -0000",
        "Wed, 09 Aug 2017 03:15:00 -0000",
        "Wed, 02 Aug 2017 03:00:00 -0000",
        "Tue, 11 Jul 2017 17:14:45 -0000",
        "Thu, 03 August 2017 06:00:00 -0400",
        "Thu, 27 July 2017 06:00:00 -0400",
        "Thu, 20 July 2017 06:00:00 -0400",
        "Thu, 13 July 2017 06:00:00 -0400",
        "Thu, 06 July 2017 06:00:00 -0400",
        "Thu, 28 June 2017 06:00:00 -0400",
        "Thu, 17 Jul 2013 06:00:03 -0400",
        "Thu, 02 Apr 2014 06:00:03 -0400",
        "Wed, 14 Jan 2016 06:00:03 -0400",
        "Thu, 22 June 2017 06:00:00 -0400",
        "Thu, 15 June 2017 06:00:00 -0400",
        "Thu, 7 June 2017 06:00:00 -0400",
        "Thu, 1 June 2017 06:00:00 -0400",
        "Thu, 23 Dec 2015 06:00:03 -0400",
        "Thu, 14 Feb 2014 06:00:03 -0400",
        "Thu, 04 Dec 2013 06:00:03 -0400",
        "Thu, 20 Dec 2016 06:00:00 -0400",
        "Thu, 23 Nov 2016 06:00:00 -0400",
        "Thu, 05 Aug 2016 06:00:00 -0400",
        "Fri, 09 Jun 2016 12:00:00 -0400",
        "Thu, 10 May 2017 06:00:00 -0400",
        "Thu, 22 Feb 2017 06:00:00 -0400",
        "Thu, 15 Feb 2017 06:00:00 -0400",
    ];
```

**Comment by upsuper** [comment]
The time strings with timezone `-0000` seems to be [rejected intentionally](https://github.com/chronotope/chrono/blob/5c0b77366851bdaaf4beee8ae3ad749faaeb464f/src/format/parse.rs#L73-L75). I guess to fix that perfectly, `parse_from_rfc2822` may need to return something like `ParseResult<Either<DateTime<FixedOffset>, DateTime<Local>>>` instead.

**Comment by upsuper** [comment]
Long weekday and month spellings are illegal in RFC 2822 IIUC, so it should be considered to be correct behavior of rejecting things like `Augest` or `June` or `Monday`.

From [RFC 2822 S3.3](https://tools.ietf.org/html/rfc2822#section-3.3):
```
day-name        =       "Mon" / "Tue" / "Wed" / "Thu" /
                        "Fri" / "Sat" / "Sun"
month-name      =       "Jan" / "Feb" / "Mar" / "Apr" /
                        "May" / "Jun" / "Jul" / "Aug" /
                        "Sep" / "Oct" / "Nov" / "Dec"
```

**Comment by upsuper** [comment]
Single digit for hour is also illegal:
```
hour            =       2DIGIT / obs-hour
minute          =       2DIGIT / obs-minute
second          =       2DIGIT / obs-second
```

**Comment by alatiera** [comment]
And some of the dates are illegal too, cause they claim "Thu, 05 Aug 2016 06:00:00 -0400" when it was in fact Friday.

**Comment by alatiera** [comment]
Is there any chance we can get an option for parsing rfc822?

**Comment by upsuper** [comment]
Excluding the time strings which are rejected from the issues above, the remaining ones are
```
        "Thu, 17 Jul 2013 06:00:03 -0400",
        "Thu, 02 Apr 2014 06:00:03 -0400",
        "Wed, 14 Jan 2016 06:00:03 -0400",
        "Thu, 23 Dec 2015 06:00:03 -0400",
        "Thu, 14 Feb 2014 06:00:03 -0400",
        "Thu, 04 Dec 2013 06:00:03 -0400",
        "Thu, 20 Dec 2016 06:00:00 -0400",
        "Thu, 23 Nov 2016 06:00:00 -0400",
        "Thu, 05 Aug 2016 06:00:00 -0400",
        "Fri, 09 Jun 2016 12:00:00 -0400",
        "Thu, 10 May 2017 06:00:00 -0400",
        "Thu, 22 Feb 2017 06:00:00 -0400",
        "Thu, 15 Feb 2017 06:00:00 -0400",
```
and all of them have mismatched weekday, so I would say it is correct behavior to reject them.

**Comment by upsuper** [comment]
> Is there any chance we can get an option for parsing rfc822?

I'm not the maintainer, but I would probably prefer not to have such option to accept more than what is specced, because that would likely make the parser harder to maintain.

My suggestion is that you add an additional layer for your own application to do a normalization before passing the string to chrono. For the list you provide, you probably need to do
* replace all long month names to short ones
* remove the weekday part (which is optional in RFC 2822)
* do some special handling for `-0000` (in my program, I [replace it with `+0000`](https://github.com/upsuper/maildir-pack/blob/9432f3244b976fb48acd2458c5dd483de74c9a4b/src/collect.rs#L19-L24) to satisify chrono)

**Comment by upsuper** [comment]
Oh, and pad any single digit with a leading zero, probably.

**Comment by alatiera** [comment]
@upsuper Thanks alot for the informative response, I gonna go ahead and do as you suggest probably.

**Comment by quodlibetor** [comment]
Thanks @upsuper, your investigation and suggestion is correct!

And the reason for the difference between the `-0000` and `+0000` is that they technically specify different things, as your `Either<..>` comment correctly points out.

We don't want to add a very high-level "do what I mean" parser to chrono (as exists in libraries for other languages) for the reasons that you suggested. But a crate that implemented that would be very welcome in the chronotope organization!

**Comment by alatiera** [comment]
@quodlibetor I've written a parser that aims to convert rfc822 formatted strings to valid rfc2822. 
Just pushed it (here)[https://github.com/alatiera/chrono_rfc822]. It's almost 50 loc and no way finished.
I am looking for feedback and guidance on the way the crate should continue and things to be done before being(I hope) part of chronorope.

**Comment by upsuper** [comment]
I would say that the naming is misleading. Those strings are not valid for RFC 822 either. IIUC, any datetime string valid in RFC 822 is also valid in RFC 2822.

**Comment by quodlibetor** [comment]
Yeah from a cursory glance at [the datetime part of RFC 822](https://tools.ietf.org/html/rfc822#section-5) I agree with @upsuper that it looks the same as 2822. Can you point to any parts in the spec that are more general?

**Comment by alatiera** [comment]
Yeah, Looking at it turns out to be the same.
I though it had to be different since so many people/generators mess up the dates in RSS feeds when it's supposed to be 822formatted.

**Comment by quodlibetor** [comment]
If there's one thing I've learned from chrono it's that people and generators mess up dates _horribly_. We're trying to make it hard to do that with chrono, while trying to also reduce friction. It's tough.
