### ISSUE TITLE
No way to convert Datetime<FixedOffset> to Datetime<Local>

### ISSUE THREAD

**Issue by Yanpas** [chronotope/chrono#193]
I'm using FixedOffset for parsing from txt and Local to obtain it from system. Seems there is no way to convert from first to second and vice versa. The only choice I have left is to use UTC. Is it by design?

**Comment by peterjoel** [comment]
There is also no way (at least that I can find) to convert a `DateTime<FixedOffset>` to a `DateTime<Utc>`. The only way I can see is to subtract the timezone offset from the Utc time, after it's been constructed :(

**Comment by quodlibetor** [comment]
Directly from one to the other must currently be done via `UTC`. There is a PR to add `From` impls in various directions, but it is ancient and no longer works.

I would really like for these `From/Into` to work.

**Comment by pitdicker** [comment]
This was implemented quite a while ago in https://github.com/chronotope/chrono/pull/271.
