### ISSUE TITLE
Localized date/time

### ISSUE THREAD

**Issue by gm666q** [chronotope/chrono#199]
I would be nice to have a ability to get localized date/time. For example in C++ std::strftime function has format %x/%X that displays date/time in format appropriate to current locale.
P.S. If it's there already sorry for creating this issue I couldn't find it.

**Comment by quodlibetor** [comment]
Getting locale information (I believe) requires integration with the operating system, which chrono has basically no support for. This should either go in a separate crate, or, if there is an obvious mapping to something that doesn't require complex dependencies we could do it in chrono.

**Comment by gm666q** [comment]
I'm not C expert but you can get localized date/time formats(that is format only) from glibc(not sure whether it's cross-platform or Unix only or Linux only). I also found this crate [https://docs.rs/locale/0.2.2/locale/index.html](url) that tries to expose that functionality, however it seems to be in early stages of development. I will look into that.

**Comment by quodlibetor** [comment]
Reasonable. If you figure out a correct way of doing this PRs are very welcome!

**Comment by quodlibetor** [comment]
One other project that *might* be interested in either exposing or integrating with local formats is [project fluent](https://crates.io/crates/fluent). I don't think that it currently exposes anything for local times, though.

**Comment by bbigras** [comment]
Any crate implemented this yet?

Also is this issue the same as #153 ?

**Comment by cecton** [comment]
@quodlibetor I just released this: https://docs.rs/pure-rust-locales/0.1.0/pure_rust_locales/

It's a pure Rust lib without any dependency that has the locales from glibc. It does **not** depend on glibc. It's using the locale data files from glibc.

I believe it can be used to solve this issue for formatting date and time with chrono. If I'm correct, the functions that will not be used (for formatting money for example) will not be include in the library at compile time because not used right? So I believe it should produce small binaries for people. We could also make a feature flag to get English only.

If you believe it's a good idea I will make a PR. I have time until end of the year to do it but I won't be available after.

**Comment by CryZe** [comment]
What's the licensing on that?

**Comment by cecton** [comment]
GNU Lesser General Public License I think

**Comment by CryZe** [comment]
That is likely problematic then, as it's statically linked in.

**Comment by cecton** [comment]
There is this in the header of every locale data file:
```
% This file is part of the GNU C Library and contains locale data.
% The Free Software Foundation does not claim any copyright interest
% in the locale data contained in this file.  The foregoing does not
% affect the license of the GNU C Library as a whole.  It does not
% exempt you from the conditions of the license if your use would
% otherwise be governed by that license.
```

**Comment by cecton** [comment]
I'm not a lawyer so I asked some help to others. There are many answers yet... https://twitter.com/CecileTonglet/status/1205162361826500611

I don't have much time left so if we want to move forward let me know.

**Comment by cecton** [comment]
@CryZe I asked a lawyer but without success, so I contacted FSF and got an answer:

> In short, we believe these files aren't copyrightable; for more background,
> please check https://sourceware.org/ml/libc-locales/2013-q1/msg00048.html
>
> --
> I am not a lawyer, this is not a legal advice.

So if you think this is good I will probably make a PR at some point. Unfortunately I don't have as much time so it might take a while.

Let me know so I don't start working on something that will never be merged.

Best
