### ISSUE TITLE
Replace month numbers with enum

### ISSUE THREAD

**Issue by clarfonthey** [chronotope/chrono#202]
Also allow determining its corresponding number similar to #201.

**Comment by jam1garner** [comment]
I'd like to second this. I think some good reasoning for this would be:
* Compile time ensuring all months are accounted for
* Cleaner pattern matching
* More inline with Rust idioms

At minimum providing both an enum option and a numerical option would be a good start, albeit I don't know what the deprecation/compatibility guarantees of the project are. I would be willing to work on this issue but I'm struggling to find anything on what contributing looks like. @lifthrasiir or @quodlibetor do you have any thoughts? I would rather not put effort into an implementation only for it to not even receive a comment (see #353), but certainly don't mind putting in the leg work behind whatever you guys would like!

**Comment by pitdicker** [comment]
A `Month` enum was added in https://github.com/chronotope/chrono/pull/461.
