### ISSUE TITLE
Performance of retrieving the month, day, etc. from a DateTime<Local>

### ISSUE THREAD

**Issue by michaeleiselsc** [chronotope/chrono#215]
Hi, I was benchmarking my code and noticing that just retrieving the month, day, etc. was involving a non-trivial amount of work with calls to fns like `checked_mul`. But I saw that it was also calling localtime_r. Can't it just return the members of localtime_r?

**Comment by pitdicker** [comment]
Chrono internally stores a `DateTime` in its own format, and converts it to UTC. Also it now has its own timezone logic, and no longer uses `localtime_r`.

I don't think there is anything we can or want to change here.

**Comment by djc** [comment]
Going to close this, since it's more than 5 years old at this point. @michaeleiselsc if you still see issues with chrono performance, feel free to reopen or create a new issue.
