### ISSUE TITLE
Replacing time with chrono crate, what type should I use for `Timespec` in chrono?

### ISSUE THREAD

**Issue by vityafx** [chronotope/chrono#218]
I have previously used the [`Timespec`](https://doc.rust-lang.org/time/time/struct.Timespec.html) type from deprecated `time` crate. Now I am moving to `chrono` crate and I can't find similar structure to move to.

**Comment by quodlibetor** [comment]
The closest that chrono has to that is probably a `Duration`, although you probably actually want a `DateTime` or `NaiveDateTime`.

Althouth since `Duration`s are always positive, @lifthrasiir has expressed interest in replacing `Duration`s with `TimeSpan`s.

**Comment by vityafx** [comment]
`NaiveDateTime` is the answer.
