### ISSUE TITLE
supported timezone syntax for DateTime from string

### ISSUE THREAD

**Issue by Dowwie** [chronotope/chrono#219]
I'm trying to accommodate the default timezone syntax returned from postgresql.  It seems to provide an abbreviated form that chrono may not support-- it omits 00 minutes.  Is there support for this in Chrono?  

http://play.integer32.com/?gist=b6394d764deb6a4bcf7b1b5ebd038969&version=stable

```
extern crate chrono;
use chrono::prelude::*;
use chrono::DateTime;

fn main() {
    let dt = "2018-02-06 11:17:09.534889-05";
    let test = DateTime::parse_from_str(dt, "%Y-%m-%d %H:%M:%S%.6f-%z");
    println!("{:?}", test);                                        
}

```

**Comment by quodlibetor** [comment]
Postgres returns the timezone as just the hours offset, not including the minutes? While I believe you, is that documented anywhere?

**Comment by Dowwie** [comment]
As per the gurus in #postgresql on Freenode, the minutes are explicitly optional in the iso spec

**Comment by quodlibetor** [comment]
Yeah this is a bug.

**Comment by dekellum** [comment]
Note that the pattern in the above example should not have a '-' between f and %z:

`"%Y-%m-%d %H:%M:%S%.6f%z"`

Since that '-' in input is a negative offset, not a separator.  But the input still won't parse unless '00' is added to the end. Still a bug or missing parse feature.

**Comment by dekellum** [comment]
Even ISO8601 includes supports for the truncated `±hh` tz format.

**Comment by quodlibetor** [comment]
Hmmm in implementing a fix for this I see that interestingly RFC 3339 [explicitly requires the full 4 digits](https://tools.ietf.org/html/rfc3339#section-5.6), in [contrast to ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC). But RFC 3339 also requires the `:`. And `chrono` [doesn't promise anything](https://docs.rs/chrono/0.4.0/chrono/format/strftime/index.html) about this.

I might need to add a `%#z` format to say ISO 8601 -- aka permissive -- TZ format. That's so gross, though.

I don't know how this is working in other languages:

* [linux strftime](https://linux.die.net/man/3/strftime) doesn't appear to support this
* [neither does python?](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior)
* I can't find evidence of what C++ does here (maybe @gnzlbg has an opinion?)
* [`java.time` appears to use `%X`/`%x` for this](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html). Sadly, chrono already aliases those chars to other format options, so the adding that would be  a breaking change. If `%X` is agreed to a be a good option maybe we could do it as a feature in 0.4.1 and break it in 0.5?

**Comment by gnzlbg** [comment]
@quodlibetor The authoritative answer here is [p0355r5](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0355r5.html) and the section you are looking for is probably "23.17.8 Formatting [time.format]". @HowardHinnant is the contact person.

FWIW, this code:

```c++
#include <iostream>
#include <date/date.h>

int main() {
  using namespace date;
  std::istringstream dt("2018-02-06 11:17:09.534889-05");
  year_month_day ymd = year{2000}/1/1;
  dt >> parse("%Y-%m-%d %H:%M:%S%.6f-%z", ymd);

  std::cout << ymd << std::endl;  // PRINTS: 2000-01-01
}
```

**Comment by quodlibetor** [comment]
Interesting.  I do love the C++ literal syntax from that page, we could probably come up with a nice, similar DSL.

It's also interesting to me that it parses into an existing structure. Considering the size of a rust-Chrono DateTime ([12/16 bytes](https://play.rust-lang.org/?gist=2cceafdcc0bd83f669d3c5d380de7cb7&version=stable) depending on if we have a TZ offset) I'm not sure if there would be much benefit to us doing something like that.

I'll update my table in the previous comment to include that in C++ `%X` represents the locale's current representation.

**Comment by gnzlbg** [comment]
> we could probably come up with a nice, similar DSL.

I started writing one but decided to put it on hold until const generics. `local_time<seconds>` is actually:

```c++
time_point<date::local_t, duration<long long, ratio<1, 1>>>
```

Those `ratio<N, D>` are used to convert between units at compile-time in some cases doing things like `gcd` at compile-time as well.

**Comment by quodlibetor** [comment]
woah, neat.

**Comment by HowardHinnant** [comment]
Well this is a first for me.  A bug report from another language! :-)

My intent was to do whatever `strptime` does for `%z`.  But now that I double-checked `strptime`, I see that it does not define `%z` at all (and that evidently irritated me), and so I just extrapolated from the `%z` for `strftime` (doesn't C have such _wonderful_ names?!).

It didn't occur to me to make the minutes optional.  And now that you bring it up, that sounds like a good idea to me.  I'm thinking:

```
%z
    [+|-]hh[mm]

%Ez
%Oz
    [+|-]hh[:mm]
```
I.e. Allow the minutes to be optional for both `%z` and `%Ez`, but for the latter, once the `:` appears, you have to have the minutes.

**Comment by gnzlbg** [comment]
@HowardHinnant Sounds good. One question: what do `%E_` and `%O_` mean? I cannot really find that in the paper. It seems that both denote modified forms of some commands. But some commands use %E_, others use %O_, and others use both.  I am unable to find a pattern in the proposal about when %E_ or %O_ should be used.

@quodlibetor 

> I might need to add a %#z format to say ISO 8601 -- aka permissive -- TZ format. That's so gross, though.

Sounds good to me as long as we keep things consistent. If we are going to have modified forms of some commands I'd like to always use the same symbol to represent that as long as it makes sense. If some commands might have multiple modified forms, it might make sense to also consider which symbols we are going to use there.

This is not as critical here as in C++ though, because we can always do a breaking release and move on.

**Comment by HowardHinnant** [comment]
`strftime` and `strptime` use the `E` and `O` modifiers in pretty much random fashion to "modify" the flag to do something different.  It is often a localized version of the flag.  So in the few places I invented (such as `%z` for parse), I took the liberty of inventing modified versions of it as well based on customer needs.  I'd have to do a survey to be sure, but I think `z` might be the only place where I got so inventive.

**Comment by quodlibetor** [comment]
Yeah in rust-chrono we use `#` as the "do something different" modifier... usually.

The only thing that has prevented me from saying that `%z` should handle optional minutes is something pathological like `%z%S` in which case it could be ambiguous if you have a parsing error or a two-digit timezone and a two-digit seconds. I can't think of any sane format that would stick plain digits after a variable-length digit field, though.

**Comment by HowardHinnant** [comment]
I haven't implemented it yet (maybe this weekend), but I'm thinking that I'll parse 4 digits into the `z`, and if there are none left for the `S` after that, error out.

**Comment by quodlibetor** [comment]
Yeah that does seem like the only reasonable option. I hate having ambiguity, but TZs usually come at the end so it shouldn't be _likely_ issue. 

Also, in case it affects your implementation or docs, RFC 3339 does _not_ support 2-digit timezone offsets, which is a much more reasonable behavior, IMO.

Thanks for your input!

**Comment by Dowwie** [comment]
@quodlibetor @HowardHinnant Any progress to report for TZ enhancement?

**Comment by gnzlbg** [comment]
@Dowwie I think Howard fixed this in the date library in this commit: https://github.com/HowardHinnant/date/commit/0bde4ba8c8eea1ade240f0249972594e486af3fe

**Comment by Dowwie** [comment]
@gnzlbg Hi!  How does that propagate to chrono formatting now?

**Comment by gnzlbg** [comment]
It doesn't. Howard "manages" the equivalent C++ library, which had the same issue reported here, but already implements the fix. 

AFAIK nobody is working on fixing this in chrono, and nobody has submitted a PR with a fix.

**Comment by Enet4** [comment]
@gnzlbg That is likely to change soon, with the upcoming efforts from the ecosystem working group. https://github.com/rust-lang-nursery/ecosystem-wg/issues/16 It's hard to believe that `chrono` will fail to deliver at this point.

**Comment by quodlibetor** [comment]
Yeah at this point I would love to implement a fix but I haven't even started on it. A PR would be most welcome. If anyone is interested in working on it I am happy to mentor.

**Comment by quodlibetor** [comment]
Speaking of mentoring, I finally figured out how to create a gitter channel for an organization: https://gitter.im/chrono-rs/chrono
