### ISSUE TITLE
How do I deserialize DateTime<Utc> from a timestamp?

### ISSUE THREAD

**Issue by vityafx** [chronotope/chrono#220]
I have made an attempt to deserialize a `DateTime<Utc>` from a unix timestamp [playground](https://play.rust-lang.org/?gist=1b19d47cc82605f4b94751aa9ba6854c&version=stable) but had no success:

```rust
extern crate serde;
extern crate serde_json;
#[macro_use]
extern crate serde_derive;
extern crate chrono;

use chrono::prelude::*;


#[derive(Debug, Deserialize)]
struct A {
    f: DateTime<Utc>,
}

fn main() {
    let s = r#"{ "f": 1515253798 }"#;
    let a = serde_json::from_str(s).unwrap();
    println!("A: {:?}", a);
}
```

Could we have such a deserializer? The implementation would be quite easy - just try to deserialize from `i64` value in the visitor. Can I make such a PR?

**Comment by quodlibetor** [comment]
PRs are always welcome, but in this case when you went to implement it you would find that we [already have an impl](https://github.com/chronotope/chrono/blob/ff962d452c3136e3793544288a168578dc4f55ca/src/datetime.rs#L819). If you build with the `serde` feature enabled you should find docs for it.

**Comment by vityafx** [comment]
@quodlibetor any idea why it does not work in the playground then? I also found it but it does not worm in my case.

**Comment by quodlibetor** [comment]
I believe that the playground builds with only default features, and serde is not a default feature. You'll need to test locally with the serde feature enabled -- see [the readme](https://github.com/chronotope/chrono/tree/ff962d452c3136e3793544288a168578dc4f55ca#usage) for instructions.

**Comment by quodlibetor** [comment]
also if you do that and then run `cargo doc --open` and search from `from_ts` you should get some decent instructions. You need to add an attribute to the field you want to deserialize.

**Comment by vityafx** [comment]
Strange, I personally use chrono for a lot of time in my project with serde feature enabled. Other deserializers are visible and work good but not from the timestamp.

**Comment by vityafx** [comment]
Just realized. Do you mean I should use (serde deserialize with)?

**Comment by quodlibetor** [comment]
Yes, exactly.

**Comment by vityafx** [comment]
@quodlibetor why this is not a default behavior?

**Comment by quodlibetor** [comment]
Do you mean supporting timestamps in deserialization? There are a few reasons:

* If we support multiple deserialization schemes, then we have to have fallback logic, which makes the failure case for the default mode slower, and the success case for the fallback mode slower
* Supporting fallback means that it's possible for different, but equally valid interpretations of values to be used accidentally (for example, some services send timestamps as integral seconds, some as integral milliseconds, some as floating point seconds/millis, some as integral seconds encoded as a string... etc). It's better to be explicit, with good docs, IMO.

I'm pretty sure that there are other reasons, but I don't recall them.

**Comment by vityafx** [comment]
Thanks much for the clarification. I have also suggested the `docs.rs` service to build with all available features so we can find the docs for stuff like that.

**Comment by quodlibetor** [comment]
Yup it would be nice to be able to specify what features to build docs with, and I thought it was possible, but I can't find any docs (ha!) for how to do it.

**Comment by dekellum** [comment]
There is a not-well-documented way to get features enabled for docs.rs. Here is an example diff:

servo/rust-url@72b7ff9c9 

(also links to the docs.rs supporting change).

**Comment by quodlibetor** [comment]
Thanks @dekellum! Hilariously we've actually had "all-features on docs.rs" enabled in our Cargo.toml since 5 days after the last release. @lifthrasiir this is another reason we could stand to do a `0.4.1` release.
