### ISSUE TITLE
Cut a 0.4.1 release?

### ISSUE THREAD

**Issue by robomancer-or** [chronotope/chrono#225]
About a month ago you switched to depending on a no_std compatible version of num-traits, is there any ETA on when that change will make it to crates.io?

As is I'm facing dependency hell trying to use both `uom` and `cortex-m-rt` (which has a dev dependency on `chrono`) in a no_std context because both transitively depend on `num-traits`.  So I'd like to humbly request a 0.4.1 release (preferably one with up to date num-* dependencies), if it's not too big a derailment.

**Comment by quodlibetor** [comment]
I agree that this should happen, I've reached out to the owner of the project to try and get a release cut.

**Comment by quodlibetor** [comment]
This is done.
