### ISSUE TITLE
Clippy fails to run on Travis

### ISSUE THREAD

**Issue by phansch** [chronotope/chrono#229]
I'm not sure exactly why, but it looks like the latest Travis build doesn't run clippy anymore: https://travis-ci.org/chronotope/chrono/jobs/358703644#L578

I was trying to run clippy over Chrono locally and I get the same error. It seems to originate from [.travis.sh#56](https://github.com/chronotope/chrono/blob/master/.travis.sh#L56).

```
lib: chrono
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading num-integer v0.1.36
 Downloading time v0.1.39
   Compiling num-traits v0.2.2
   Compiling libc v0.2.40
   Compiling time v0.1.39
   Compiling num-integer v0.1.36
   Compiling chrono v0.4.1 (file:///home/travis/build/chronotope/chrono)
error: Unrecognized option: 'features'
error: Could not compile `chrono`.
```

This was with
```
rustc 1.26.0-nightly (482a913fb 2018-03-25)
cargo 1.26.0-nightly (d10ec661b 2018-03-20)
```

I tried to run `TRAVIS=true CHANNEL=nightly CLIPPY=y ./.travis.sh`

**Comment by quodlibetor** [comment]
Yup, I'll be trying to figure out what's going on with it today. A PR to fix it would be welcome, if you're working on it. Otherwise, if you've got something else, you can just send a PR and ignore the clippy issues.

**Comment by phansch** [comment]
Looks like this is fixed with the latest clippy (0.0.190). 

Would you welcome a PR that lets you upgrade clippy yourself, so that it doesn't automatically fetch the newest version on a new build? That way you would have control over when you upgrade (or downgrade) clippy.

**Comment by quodlibetor** [comment]
Yes! I believe it would need to specify an exact version of nightly rustc as well, but I think that that would be fine, or even excellent. I think I'd prefer if we continued to run tests on the latest nightly, but that we ran clippy with a known one.

**Comment by pitdicker** [comment]
This issue can be closed, our CI is green
