### ISSUE TITLE
strftime formatting

### ISSUE THREAD

**Issue by manfredlotz** [chronotope/chrono#230]
I want to print the time zone name using chrono::format::strftime and specifier %Z.  A time zone name could have 3 or 4 characters. 

Is there a possibilty to specify a width for that value? Reason I want this is that I create some output which should be formatted nicely.

I tried something like this
```rust
   println!("{:20} {:4} {}", str1,  j.format("%Z"), str2);
```
but it doesn't work.

**Comment by quodlibetor** [comment]
I don't believe that there is any sane way to do this, the timezone names are based on the official appreviations, which [have a variety of different character counts](https://www.timeanddate.com/time/zones/).

If you want nice alignment you're on the right track, but I think chrono's `DelayedFormat` has a bug in terms of alignment, so you'd want to convert to `String` first.

```
println!("{:20} {:4} {}", str1,  j.format("%Z").to_string(), str2);
```

**Comment by manfredlotz** [comment]
Yes, you are right. to_string() helps here.  So it is at least a helpful workaround.

Thanks a lot, Manfred
