### ISSUE TITLE
Right nanoseconds parsing

### ISSUE THREAD

**Issue by gukoff** [chronotope/chrono#238]
Consider `2018-01-01T20:00:00.123`.
`Utc.datetime_from_str` parses it as a datetime with 123 nanoseconds.
[Every Python package](https://nbsoftsolutions.com/blog/iso-8601-and-nanosecond-precision-across-languages) and [Go](https://play.golang.org/p/Dqm2yVlo8U9) parse it like 123000000 nanoseconds.

I haven't found an ISO specification for nanoseconds. But shouldn't chrono better align with libraries in other languages?

**Comment by dekellum** [comment]
What format string are you passing in the call to `datetime_from_str`?  What version of chrono?

**Comment by gukoff** [comment]
Format: `%Y-%m-%dT%H:%M:%S.%f`
Version: 0.4.1

**Comment by dekellum** [comment]
I _think_ you want this instead:

~~~ diff
+++ Format: %Y-%m-%dT%H:%M:%S%.f
--- Format: %Y-%m-%dT%H:%M:%S.%f
~~~
(Swap order of final '.' and '%')

**Comment by gukoff** [comment]
Looks bizarre. This fails to parse: "microsecond must be in 0..999999".
The error itself says it's microseconds, not nanoseconds.

Why `%.f`? What's the difference between `%f` and `%.f`?

**Comment by Enet4** [comment]
@gukoff That is documented [here](https://docs.rs/chrono/0.4.1/chrono/format/strftime/index.html). `%.f` is left-aligned, and so achieves exactly what you originally intended.

**Comment by quodlibetor** [comment]
I'm not sure what the docs _should_ look like for the `%f` format specifier, but the fact that it is right-aligned is probably too late to change and is also probably hard to document. PRs making this less of a footgun are welcome!

**Comment by pitdicker** [comment]
Updated the documentation in https://github.com/chronotope/chrono/pull/1173.
