### ISSUE TITLE
getting utc in wasm

### ISSUE THREAD

**Issue by jaroslaw-weber** [chronotope/chrono#243]
Is there a workaround for making chrono work with wasm? I want to get current time (utc). I am using wasm-unknown-unknow flag.

**Comment by quodlibetor** [comment]
What is the error that you're running into? I haven't done any work with it, but running with `no-default-features` might help you out.

**Comment by ablwr** [comment]
I'm having this problem as well, and this user reporting in the `time` repo gets the same errors as I do: https://github.com/rust-lang-deprecated/time/issues/163

**Comment by CryZe** [comment]
Would it be if I would just send a PR real quick that extends all the local cfgs to also check for wasm? That'd be a fast and easy, but slightly dirty fix (although somewhat necessary for the meantime).

**Comment by quodlibetor** [comment]
@CryZe yes I'd be curious what that looks like, if it's backwards-compatible I'd be happy with it.

**Comment by CryZe** [comment]
Actually, that wouldn't work, as the time crate would still be pulled in then. Bleh, I guess someone needs to fix cargo then.

**Comment by quodlibetor** [comment]
If you disable default features we should not be pulling in the time crate.

**Comment by jjpe** [comment]
> Is there a workaround for making chrono work with wasm? I want to get current time (utc). I am using wasm-unknown-unknow flag.

I have a [PR](https://github.com/chronotope/chrono/pull/287) waiting to be merged that enables `Utc::now()`  and `Local::now` to work on WASM.

**Comment by David-OConnor** [comment]
Still broken

**Comment by quodlibetor** [comment]
This is fixed.
