### ISSUE TITLE
Clippy: the trait bound `Tz2: offset::TimeZone` is not satisfied

### ISSUE THREAD

**Issue by oherrala** [chronotope/chrono#246]
Clippy throws following error when running it for chrono crate. This error also happens for every crate depending on chrono making it impossible to use Clippy.

```console
$ cargo +nightly clippy
    Checking chrono v0.4.2 (file:///Users/oherrala/rust/chrono)
error[E0277]: the trait bound `Tz2: offset::TimeZone` is not satisfied
  --> src/date.rs:44:5
   |
44 |     offset: Tz::Offset,
   |     ^^^^^^^^^^^^^^^^^^ the trait `offset::TimeZone` is not implemented for `Tz2`
   |
   = help: consider adding a `where Tz2: offset::TimeZone` bound

error[E0277]: the trait bound `Tz2: offset::TimeZone` is not satisfied
  --> src/datetime.rs:60:5
   |
60 |     offset: Tz::Offset,
   |     ^^^^^^^^^^^^^^^^^^ the trait `offset::TimeZone` is not implemented for `Tz2`
   |
   = help: consider adding a `where Tz2: offset::TimeZone` bound

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `chrono`.

To learn more, run the command again with --verbose.
```

This happens with:

 * rustc 1.27.0-nightly (ac5c0848d 2018-05-14)
 * Clippy 0.0.200

**Comment by mitskevich** [comment]
Clippy issue is tracked here: https://github.com/rust-lang-nursery/rust-clippy/issues/2760

**Comment by CAD97** [comment]
Partial workaround for crates depending on clippy: run `cargo +nightly check`, and cargo/clippy will reuse that work in the future and not recheck chrono.

It will require touching any crates you care about the clippy output to, however.

**Comment by phansch** [comment]
This is fixed with the next clippy release

**Comment by mitskevich** [comment]
Latest Clippy version (0.0.204) does not throw this error anymore. I think this issue can be closed now.

**Comment by quodlibetor** [comment]
Indeed, thanks everyone!
