### ISSUE TITLE
Sub-second format without dot (.)

### ISSUE THREAD

**Issue by emschwartz** [chronotope/chrono#250]
I'm working on a project that uses an RFC 3339-like format without the symbols (`-`, `:`, `.`) and with milliseconds cut/padded to 3 . As far as I can tell, chrono allows me to parse everything except the milliseconds on their own. However, I think the only way to encode and decode milliseconds (or other fixed-length fractions of a second) is with a leading dot (`.070`). 

Would it be possible to add a way to parse milliseconds without the dot (e.g. `%3f`)?

**Comment by quodlibetor** [comment]
Yup, that seems like a reasonable request. If you want to implement it I'm happy to mentor, otherwise I'll try and build it this weekend.

**Comment by emschwartz** [comment]
Excellent. I'm a rust newbie but I can take a stab at it this afternoon

**Comment by quodlibetor** [comment]
cool, feel free to ask questions here or in https://gitter.im/chrono-rs/chrono
