### ISSUE TITLE
Can't parse datetime from another timezone

### ISSUE THREAD

**Issue by achntrl** [chronotope/chrono#255]
I noticed that I can't parse a date with another offset than mine.

I'm in the +0200 timezone:

```rust
extern crate chrono;

use chrono::{Local, TimeZone};

fn main() {
    let working_input_string = "05/Jun/2018:20:55:45 +0200";
    match Local.datetime_from_str(working_input_string,"%d/%b/%Y:%T %z") {
        Ok(d) => println!("{:?}", d),  
        Err(err) => println!("{}", err),
    }  // This will Ok and print the date: 2018-06-05T20:55:45+02:00

    let failing_input_string = "05/Jun/2018:20:55:45 +0300";
    match Local.datetime_from_str(failing_input_string,"%d/%b/%Y:%T %z") {
        Ok(d) => println!("{:?}", d),
        Err(err) => println!("{}", err), 
    }  // This will Err and print "no possible date and time matching input"
}
```

I would have expected `failing_input_string` to be parsed as `2018-06-05T19:55:45+02:00`. Is that something that we shouldn't do or is this a missing feature / a bug ?

There is the same issue with `Utc`: in that case I can parse "05/Jun/2018:20:55:45 +0000" but not any other offset

**Comment by svenfoo** [comment]
As far as I understand that's intentional. You can use `DateTime::parse_from_str()` instead to be able to parse a date with timezone specifier from any timezone.

**Comment by quodlibetor** [comment]
svenfoo is correct.
