### ISSUE TITLE
This comment indicates that the `from_utc` function is not named new "to discourage direct usage".

### ISSUE THREAD

**Issue by zancas** [chronotope/chrono#260]
https://github.com/chronotope/chrono/blob/e165a93a6c3cd351fa6e46495406187f1903cb6e/src/datetime.rs#L76

I found this pattern being used in the wild, so the comment was insufficient to enforce "correct"?  Behavior.

Would it be a good idea to remove the "`pub`" keyword in this case?

**Comment by pitdicker** [comment]
Removed the comment in https://github.com/chronotope/chrono/pull/1135.
