### ISSUE TITLE
Improvements to parsing into Utc, converting from other timezones to Utc

### ISSUE THREAD

**Issue by mqudsi** [chronotope/chrono#263]
Thanks for making dealing with dates and times in rust easier and for providing what has become the defacto standard for date-based operations.

I do believe there is room for improvement however when it comes to dealing with `DateTime<Utc>` instances; unless I'm mistaken and there's actually an easier way, this is what my code currently looks like to parse a timestamp from a string into a `DateTime<Utc>` instance:

```rust
        let created: DateTime<Utc> = DateTime::from_utc(
            DateTime::<FixedOffset>::parse_from_rfc3339("1996-12-19T16:39:57-08:00")
                .unwrap()
                .naive_utc(),
            Utc,
        );
```

Aside from the fact that it isn't very pretty or terse, I think it's also extremely undiscoverable. In particular, the usage of DateTime::**from_utc** to convert _to_ a `DateTime<Utc>` object is unexpected (I understand why it works).

It would be extremely helpful if `DateTime<FixedOffset>` had a `to_utc()` helper method or some other means of converting more intuitively between `DateTime` flavors.

Is there a fundamental reason why there are no `std::convert` impls to facilitate conversion between these types? Since in the code above there is only the first `.unwrap()` and all other operations are not expected to ever produce an error, I imagine it would be possible to use `std::convert` in its current form (vs waiting for `std::convert::TryFrom` to finally stabilize).

If `std::convert::From<chrono::DateTime<chrono::FixedOffset>>` were implemented for `chrono::DateTime<chrono::Utc>` (or `std::convert::Into<chrono::DateTime<chrono::Utc>>` implemented for `chrono::DateTime<chrono::FixedOffset>` if one type isn't aware of the other) the code above could be simplified considerably:

```rust
        let created: DateTime<Utc> = DateTime::<FixedOffset>::parse_from_rfc3339("1996-12-19T16:39:57-08:00").unwrap().into();
```

(Although I would still suggest that `parse_from_rfcxxxx` be implemented for `DateTime<Utc>` in all cases.)

**Comment by dpc** [comment]
I came here, looking for help, found this issue so I'll post my experiences.

I was trying to convert date in `Local` timezone to a `FixedOffset` timezone.

The timezone/offset conversions are very confusing and very hard to discover. Some of the traits involved don't even make sense to me:

Like offset vs timezone - what is `Local` if not a `FixedOffset` timezone of system-configured value? Donno. Maybe I'm missing something.

Some simple conversion functions between dates in different timezone, would be greatly appreciated. :)

**Comment by quodlibetor** [comment]
Hey, sorry about the delay!

I think that the most fundamental question is why there are no `From` impls for the various timezones. IMO there is no good reason. #67 actually implemented them, but it was from a time when this library was less-maintained. I tried to rebase so that dbrgn would get the original credit, but ran into semantic conflicts.

I believe that when I last gave it a go the design of the Tz traits was such that it was really awkward to implement conversions pleasantly, but I'm not super confident that that's true.

I agree that `From` should be implemented between all `DateTime<T>` and `parse_from_xxx` should be implemented on `Utc`. A PR implementing those items would be very welcome, otherwise I'll implement it after RustConf.

**Comment by mqudsi** [comment]
I started working on this but I'm pretty sure I'm doing something wrong because the approach I took (`.with_timezone()`) made it much less painful than I'd expected.

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/271.

Since then you can write:
```rust
let created: DateTime<Utc> = DateTime::parse_from_rfc3339("1996-12-19T16:39:57-08:00").into();
```
