### ISSUE TITLE
Minimum and maximum NaiveDateTimes

### ISSUE THREAD

**Issue by njaard** [chronotope/chrono#276]
It would be useful to get the "earliest" and "latest" `NaiveDateTime` in much the same way that `::std::u64::MAX` contains 2^64.

~~Frustratingly, the actual value isn't even documented, so I couldn't specify this value if I wanted to.~~

**Comment by pitdicker** [comment]
Constants for this were added in https://github.com/chronotope/chrono/pull/452, and moved to associated constants in https://github.com/chronotope/chrono/pull/726.
