### ISSUE TITLE
Add round/truncate functions for any specified Duration

### ISSUE THREAD

**Issue by douglascaetano** [chronotope/chrono#280]
It would be very useful for some use cases to have a round or truncate function for any specified Duration.

For now, I'm doing this to truncate some DateTime to a 5 minutes interval:
```rust
    let dt = Utc::now();
    let round_down = dt.timestamp() % (5 * 60);
    let dt_rounded = dt.with_nanosecond(0).unwrap() - time::Duration::seconds(round_down);
```

It would be nice to have something like this:
```rust
    let dt = Utc::now();
    let dt_rounded = dt.truncate(time::Duration::minutes(5));
```

I can submit a PR if there is some basic mentoring available -- I'm still inexperienced in Rust.

**Comment by gwik** [comment]
https://docs.rs/chrono/0.4.11/chrono/trait.SubsecRound.html

Could be closed.

**Comment by douglascaetano** [comment]
> https://docs.rs/chrono/0.4.11/chrono/trait.SubsecRound.html
> 
> Could be closed.

Hi @gwik. Actually, this isn't the same as what I asked. The SubsecRound trait you linked does truncate or round a DateTime, but only by a specified subsecond digit. What I asked is to round a DateTime by any specified Duration, e.g., truncating `08/apr/2020 15:19` with a 5-minute duration would yield `08/apr/2020 15:15` and rounding it by same duration would yield `08/apr/2020 15:20`.

(After thinking again about this question, it came to me that this truncation/rounding makes sense only for Time or the time part of DateTime.)

**Comment by gwik** [comment]
I agree this is not the same and that truncating by duration is more general.
Have you give a shot at a PR ? You could take inspiration from the SubsecRound trait.

**Comment by douglascaetano** [comment]
I must admit I have forgot about this, as I faced this problem in some tests I was doing at the time. But I can try something, for sure. I'll post it in a few days.

**Comment by douglascaetano** [comment]
@jiacai2050, sorry for taking so long to answer. I'm trying to get some time to do this, but still couldn't yet.

Feel free to implement the solution, if you want (or anyone else reading this issue). I'll still try to get some time to tackle this if no one solved it by then.

**Comment by Aunmag** [comment]
How do I round `NaiveDateTime`?

**Comment by robyoung** [comment]
@Aunmag I'm afraid it's not implemented yet. #509 will address this when it's merged.
