### ISSUE TITLE
Utc::now() panicks when targetting WebAssembly

### ISSUE THREAD

**Issue by jjpe** [chronotope/chrono#284]
I have a crate that uses chrono extensively, and I am trying to enable that crate to target WASM.

However, I've traced a `panic!` I'm getting to the `UTC::now()` constructor fn. Specifically:
```` rust
#[cfg(feature="clock")]
impl Utc {
    // ...
    pub fn now() -> DateTime<Utc> {
        let spec = oldtime::get_time(); // <-- offending line
        let naive = NaiveDateTime::from_timestamp(spec.sec, spec.nsec as u32);
        DateTime::from_utc(naive, Utc)
    }
}
````

I'm hoping a fix for this can be as easy as an extra version of `UTC::now()` for WASM, but I'm unsure.

**Comment by jjpe** [comment]
I've added initial support for `wasm32` @ PR #287.

**Comment by David-OConnor** [comment]
Note that this is still unmerged.

**Comment by jasonwilliams** [comment]
@quodlibetor are you able to help with this? Some projects targeting web assembly breaks because of this issue, looks like there's been a PR

**Comment by ctaggart** [comment]
I just ran into this. I looks like https://github.com/chronotope/chrono/pull/331 has the minimal changes. Thank you @evq for picking this back up!

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/331.
