### ISSUE TITLE
Remove dependency on the `time` crate

### ISSUE THREAD

**Issue by alexcrichton** [chronotope/chrono#285]
The `time` crate has been unmaintained and deprecated for a very long time now and isn't very keen or eager to add new features or fix bugs. It'd be best if the required functionality for `chrono` were folded directly into this crate (which probably doesn't include the entire `time` crate). 

This would likely make it easier to solve issues like https://github.com/chronotope/chrono/issues/284 and https://github.com/chronotope/chrono/issues/243 because fixing those will require a new feature of the `time` crate which is not maintained and difficult to modify nowadays.

**Comment by jjpe** [comment]
WIP now. The idea is to make a `time` module within chrono that just contains the code from the `time` crate.
After that, there is every possibility for refactoring where desired/necessary.

**Comment by zserik** [comment]
Is there any update on this? `time v0.2` was released recently.

**Comment by pitdicker** [comment]
The relevant parts of time 0.1 were absorbed into chrono in https://github.com/chronotope/chrono/pull/478, and https://github.com/chronotope/chrono/issues/1073 is the issue for dropping time as a dependency.
