### ISSUE TITLE
outdated info on the most recent doc?

### ISSUE THREAD

**Issue by andy5995** [chronotope/chrono#289]
I'm not sure if the chrono-crate doc needs updating. I'm fairly new to rust and maybe that's the source of my confusion. 

There is a [forum thread](https://users.rust-lang.org/t/using-std-duration/22218) where I explain how I'm perceiving things. Apparently I'm wrong but just wanted to offer some feedback and double-check before I let it go.

**Comment by pitdicker** [comment]
To copy the discussion from https://users.rust-lang.org/t/using-std-duration/22218:
> I'm trying to work through the gigasecond exercise.
>
> I can't seem to use `std::time::Duration` though. I'm getting the impression there's some conflicting documentation.
>
> I see an example such as `Duration::seconds(-2 * 3600 + 2)` used in a file with use `chrono::prelude::*; use time::Duration;` at the top.
>
>Well that gives me an error:
> ```
> use time::Duration;
> ^^^^ Did you mean std::time?
> ```
>
> So I change it, and the error goes away.
>
> But then I get an error with my code, even though I'm pretty sure it's being used as shown in the example
>
> ```
>  8 | start + Duration::seconds(1_000_000_000)
>    | ^^^^^^^^^^^^^^^^^ function or associated item not found in std::time::Duration
> ```
>
> But something similar to that is what's shown in the example in the docs at [chrono - Rust 8](https://docs.rs/chrono/0.4.6/chrono/)
>
> But at the top of that page, under the Duration section:
>
> > Chrono does not yet natively support the standard `Duration` type, but it will be supported in the future. Meanwhile you can convert between two types with `Duration::from_std` and `Duration::to_std` methods.

And also https://users.rust-lang.org/t/using-std-duration/22218/8:

> Well... this is mentioned on the [chrono crate doc](https://docs.rs/chrono/0.4.6/chrono/#duration)
>
> > Chrono does not yet natively support the standard  `Duration` type, but it will be supported in the future. Meanwhile you can convert between two types with `Duration::from_std` and  `Duration::to_std` methods.
>
> And further down in that same doc in an example
> ```rust
>     use chrono::prelude::*;
>     use time::Duration;
>
> ...
>
>     assert_eq!(dt1.signed_duration_since(dt2), Duration::seconds(-2 * 3600 + 2));
>     assert_eq!(dt2.signed_duration_since(dt1), Duration::seconds(2 * 3600 - 2));
>     assert_eq!(Utc.ymd(1970, 1, 1).and_hms(0, 0, 0) + Duration::seconds(1_000_000_000),
> ```
>
> > It seems as if you are confusing the documentation of `chrono` s `Duration` with the one from `std`
>
> I rather feel that **I'm** not confusing the documentation, but **it** is confusing **me.**

**Comment by pitdicker** [comment]
Since 0.4.16 the main documentation (https://docs.rs/chrono/0.4.16/chrono/index.html) starts with
```rust
use chrono::prelude::*;
use chrono::Duration;
```

Having two different types that are named `Duration` is confusing, but I think this helps a bit.
