### ISSUE TITLE
Unix Epoche const

### ISSUE THREAD

**Issue by nifker** [chronotope/chrono#294]
I think it would be useful to add an DateTime Unix Epoche const similiar to std::time::UNIX_EPOCHE

**Comment by quodlibetor** [comment]
Yes, the next 0.x release of chrono will definitely take advantage of const. It requires a compiler version bump, which we only do on minor version upgrades.

**Comment by pitdicker** [comment]
Added in https://github.com/chronotope/chrono/pull/1291.
