### ISSUE TITLE
Add Serialize/Deserialize for `std::ops::Bound<DateTime>` and friends

### ISSUE THREAD

**Issue by manifest** [chronotope/chrono#299]
Would be useful for serializing PostgreSQL [time range](https://www.postgresql.org/docs/11/rangetypes.html) data types: `tsrange`, `tstzrange`, `daterange` that are already supported by Diesel.

**Comment by quodlibetor** [comment]
Where does the `Bound` type come from?

Either way you ought to be at least partially unblocked by using [serde's support for remote crates](https://serde.rs/remote-derive.html)

**Comment by manifest** [comment]
> Where does the `Bound` type come from?

Diesel [implements](https://github.com/diesel-rs/diesel/issues/676) PostgreSQL range data types as `(Bound<T>, Bound<T>) where T: FromSql<ST, Pg>` and it looks as a good solution for ranges in general.

> Either way you ought to be at least partially unblocked by using serde's support for remote crates

Sure, but it would be great to have such feature right out of box.

**Comment by quodlibetor** [comment]
I agree it would be nice. I think that this feature belongs in diesel, though, since diesel depends on chrono not the other way around.

**Comment by manifest** [comment]
I think about that as a support for serialization and deserialization for time ranges in general. Because `Bound` is a native data type for Rust, it seems the only valid option for time ranges. I mean the type itself may be useful without Diesel.

**Comment by manifest** [comment]
Yes, I was referring to `std::ops::Bound`.

**Comment by manifest** [comment]
We still need a few serde helpers (ts_seconds, etc) I believe.

**Comment by quodlibetor** [comment]
the serde helpers are only needed for the module helpers, which I don't think will be necessary for interacting with diesel's serde support.

I'm going to close this for now in favor of 0nkery's serde patches, but if those don't help enough then we can re-open or open a new, more specific, issue.
