### ISSUE TITLE
Support for european date format for formatting syntax

### ISSUE THREAD

**Issue by porky11** [chronotope/chrono#300]
In Europe, date is normally written as "DD.MM.YYYY" or "DD.MM.YY".
There should be format directives to support this, too.
The example date looks like this:
```
08.07.01
08.07.2001
```

I know it's possible using more complicated directives, but since there are also pedefined directives for american and international format, and since [many countries in Europe seem to use that format](https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe), it may be appropriate to include a new directive for that format.

**Comment by pitdicker** [comment]
> In Europe, date is normally written as "DD.MM.YYYY" or "DD.MM.YY".

This claim is a little strong :smile:. According to Wikipedia it is the traditional notation in Germany and most post-Soviet states.

The [`strftime` format](https://cplusplus.com/reference/ctime/strftime/) is not unique to Chrono. It already uses most of the upper- *and* lowercase alphabet. I don't think adding any more specifiers is going to improve it.

This is what the separate format specifiers are for, in this case `%d.%m.%y` and `%d.%m.%Y`.
