### ISSUE TITLE
Missing padding when `Display`ing DateTime

### ISSUE THREAD

**Issue by kstrafe** [chronotope/chrono#303]
When writing out datetimes, I mostly get

```
2019-01-28 07:40:10.313365014 +01:00
```

But sometimes I get
```
2019-01-28 07:40:10.313222 +01:00
```

It's unclear whether it should have been `313222000` or `000313222`, and looks odd when all surrounding prints contain the corrent number of subsecond digits.

# Reproduce # 
```
println!["{}", Local::now()];
```

**Comment by dekellum** [comment]
The default `Display` tries to be smart regarding available nanosecond digits. Even on platforms that have nanosecond precision, given random times, there is a 1/1000 chance that the least significant digits are '000', and it will format using only 6 digits.  Other custom and standard-based formats don't have this problem, like  `to_rfc3339_opts(SecondsFormat::Nanos, true)` or `to_rfc3339_opts(SecondsFormat::Micros, true)`.

**Comment by BourgondAries** [comment]
That works I guess, but it's a bit of a nuisance considering the default format is quite nice.

**Comment by pitdicker** [comment]
I don't think changing the `Display` implementation of `DateTime` to always print full nanosecond resolution is something we want. That would clutter the output for users that currently only deal with seconds precision.

This is what [`DateTime::format`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.format) is for.
