### ISSUE TITLE
Add a FixedOffset parser

### ISSUE THREAD

**Issue by linkmauve** [chronotope/chrono#314]
In [my project](https://gitlab.com/xmpp-rs/xmpp-parsers), an [XMPP](https://xmpp.org) element parser, I need to be able to parse a timezone on its own, in order to implement [XEP-0202](https://xmpp.org/extensions/xep-0202.html).

I’m currently using [a super ugly workaround](https://gitlab.com/xmpp-rs/xmpp-parsers/blob/master/src/time.rs#L46-49) by creating a DateTime from a random date concatenated with the timezone I want to parse, and then extracting the timezone from it.

A correct way to implement that could be to `impl std::str::FromStr for FixedOffset`, which would return only the timezone information and reject any other string.

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/1157.
