### ISSUE TITLE
`.timestamp()` doesnt match `Display` output in certain circumstances

### ISSUE THREAD

**Issue by sparky8251** [chronotope/chrono#318]
Take the sample code here:

```rust
use chrono::NaiveDateTime;
use chrono::TimeZone;
use chrono::{DateTime, Duration};
use chrono_tz::US::Eastern;
use chrono_tz::Tz;

fn main() {
    let timestamp = 1572580800;

    let mut dt: DateTime<Tz> = Eastern.from_utc_datetime(&NaiveDateTime::from_timestamp(timestamp, 0));

    println!("Written datetime: {}\n Timestamp: {}", dt, dt.timestamp());

    //increment past the daylight savings change

    dt = dt + Duration::days(88);

    println!("Written datetime: {}\nTimestamp: {}", dt, dt.timestamp());
}
```

You should get the following output:

```bash
# this is right!
Written datetime: 2019-11-01 00:00:00 EDT
Timestamp: 1572580800

# the datetime is right, but EDT is not!
Written datetime: 2020-01-28 00:00:00 EDT
Timestamp: 1580184000
```

And then verifying the timestamps:
```bash
# this one is right!
date -d @1572580800
Fri Nov  1 00:00:00 EDT 2019

# this one is wrong! its lost an hour to the void!
# it also correctly outputs with EST instead of chrono's incorrect EDT
date -d @1580184000
Mon Jan 27 23:00:00 EST 2020
```

Maybe I'm just thinking about this wrong, but daylight savings is almost always considered part of the timezone from what I've seen. This feels a tad unexpected to say the least.

I looked through the docs and I don't see anything that handles daylight savings, so I had presumed it was handled as part of the timezone implementation.

If this is intended behavior, there should be some mention in the docs of how to handle daylight savings time (and I'd love to know the proper way of handling it). If I add a day I expect it to add a day, not 23 hours. 

Furthermore, whatever the answer to the above questions are I'd expect chrono to agree with itself when it comes to printing the value as a string vs a timestamp (somehow it manages to be mostly correct as a string while being very wrong as a timestamp). This inconsistency feels *very* unexpected and dangerous.

EDIT: there also seems to be some odd behavior around when it triggers this missing hour. Nov 3rd, 2019 @ 2:00 AM is when DST changes this year in the US/Eastern timezone. Adding 3 days instead of the 88 I supplied with the example code triggers this lost time even though it doesn't cross the DST border. I should've had to add 4 days or 3 days and 2 hours to trigger the time loss, NOT an exact 3 days.

Something is very wrong here...

**Comment by sparky8251** [comment]
Did I improperly explain this set of bugs? It's rather serious since time isn't properly added if you use `.timestamp()` to output it. It makes this library entirely unreliable for keeping track of time.

It's a bit alarming to hear nothing in nearly 2 months for what is arguably a core crate for Rust. I have attempted to look into this bug, but as I am a novice programmer (let alone Rust specifically), I have been having trouble.

**Comment by quodlibetor** [comment]
Sorry, this definitely fell through the cracks of a vacation and some overall life churn.

I agree that this looks like a bug, I'm looking into it.

**Comment by sparky8251** [comment]
Np man! I figured things fell through the cracks, so I commented :)

As a quick summary of the bugs reported here:

1. `Display` doesn't respect daylight labels but does produce proper times
2. `.timestamp()` doesn't account for daylight savings when converting to unix time and this can result in loss of time
3. `.timestamp()` doesn't respect start/end times of daylight savings properly. It respects them in terms of day, but not in terms of time of day. This can result in unexpected outcomes for a brief period of time... which is not good.

If you need help testing or more info, please ask. I'm willing to do whatever I can to help :)

**Comment by quodlibetor** [comment]
FWIW the problem is almost certainly in either the chrono-tz library, or else that maybe chrono is not using chrono-tz correctly when doing addition.

The probably best workaround for _correctness_ right now (and probably not so bad for perf) would be to convert to UTC, do the math, then convert back to the target TZ.

**Comment by quodlibetor** [comment]
Okay I've got some fixes up which should be released soon.

FWIW @sparky8251 , when you said:

> ```
> # this is right!
> Written datetime: 2019-11-01 00:00:00 EDT
> Timestamp: 1572580800
>
> # the datetime is right, but EDT is not!
> Written datetime: 2020-01-28 00:00:00 EDT
> Timestamp: 1580184000
> ```

You weren't entirely correct: that written datetime should have been
`2020-01-27 23:00:00 EST` , because adding a duration adds a number of
_seconds_, not logical days. See the test added to chrono-tz and
linked above for what the correct behavior should be.

The only way to add days right now is to implement a day iterator manually.
Note that in that case you might end up with an ambiguous/nonexistent time, whereas adding a number of seconds always ends up with something real.

**Comment by quodlibetor** [comment]
wrong button.

**Comment by sparky8251** [comment]
Coolio! I'll try running my tests on this and see if it helps my specific issue. Based on your mentioning of seconds and not days, it might not solve my problem.

Thanks for the fixes man!

**Comment by sparky8251** [comment]
No idea... chrono-tz doesn't wanna build on my machine and if I just set the dependency to a clone of chrono master it freak out the compiler since 2 versions of chrono get pulled in.

Guess I just need to wait for 0.4.9

**Comment by quodlibetor** [comment]
if you add a 

```toml
[patch.crates-io]
chrono = { git = "https://github.com/chronotop/chron" }
```

you should get around the compiler "too many versions of chrono" issue.

**Comment by quodlibetor** [comment]
0.4.9 is out with this change.

**Comment by sparky8251** [comment]
So, I have tested and this does not solve my current issue. In fact, as a consumer of the crate I'm unsure if I would count this as solved at all (though I can see the argument why when it's viewed as a developer).

I'll open some new issues that track the bits you didn't fix in this issue AND attempt to explain why I feel this bug is still unsolved as it pertains to a user of the crate.

Thanks for the improvement to consistency! It's def a good change!

**Comment by quodlibetor** [comment]
could you explain what your specific issue is? Is it that you'd like to be able to add some "logical days"?

**Comment by sparky8251** [comment]
Yes. One specific problem (the one I specifically am facing) is that it does not add days, it adds seconds that amount to a day. This results in issues with timezones that implement daylight savings time causing inconsistencies.

In my very very very specific case, I am taking an input Unix timestamp (that is a local TZ), converting it to a chrono object respecting that timezone, the increment it by X days printing each new unix timestamp. I need it to generate consistent timestamps but instead its losing an hour when it crosses a daylight savings border.

If I use a `Duration::days(3)` I'd personally expect it to increment 3 days, NOT `86400 x 3` seconds. The latter causes confusion, the former makes "sense."

I am reasonably certain I have documented a few more bugs in this that haven't been addressed yet around timezones and daylight savings. I will be confirming these and opening issues for them just so they aren't lost to the sands of time :)

**Comment by quodlibetor** [comment]
Sounds good! Thanks for taking the time.
