### ISSUE TITLE
Link to docs for std::time::Duration in chrono docs on docs.rs seems out of date

### ISSUE THREAD

**Issue by broersma** [chronotope/chrono#322]
[The paragraph about Duration](https://docs.rs/chrono/0.4.6/chrono/#duration) on Docs.rs links to the docs for the [time crate's Duration](https://docs.rs/time/0.1.40/time/struct.Duration.html) in the sentence "Chrono does not yet natively support the standard Duration type".

Instead, it should be linking to https://doc.rust-lang.org/std/time/struct.Duration.html

Interestingly the link seems correct in [README.md](https://github.com/chronotope/chrono/blob/master/README.md) and [lib.rs](https://github.com/chronotope/chrono/blob/master/src/lib.rs) (which I presume should the source for the docs on Docs.rs, so I'm not really sure how to fix this).

**Comment by quodlibetor** [comment]
Ah, yeah that got fixed awhile ago, I just haven't done a release in too long. Just did one, so this should be good pretty soon! Thanks!
