### ISSUE TITLE
Utc.timestamp_millis panic on negative values that do not divide by 1000

### ISSUE THREAD

**Issue by aztecrex** [chronotope/chrono#324]
Utc.timestamp_millis and Utc.timestamp_millis_opt panic when supplied a negative
number that is not on a seconds boundary.

```rust
Utc.timestamp_millis_opt(-7000); // OK
Utc.timestamp_millis_opt(-7001); // Panic
```

Using chrono 0.4, rustc 1.35.0 (3c235d560 2019-05-20)

**Comment by quodlibetor** [comment]
@aztecrex are you by any chance on chrono 0.4.6? 0.4.7 includes a fix for negative `timestamp_millis`.

**Comment by aztecrex** [comment]
I'm on 0.4.6

**Comment by aztecrex** [comment]
0.4.7 solves it for the example I provided. I'll remove my workarounds in code to see if it generally works. Thanks.

**Comment by aztecrex** [comment]
Yep. Replaced custom date constructor with `Utc.timestamp_millis_opt` and all tests pass now.

**Comment by quodlibetor** [comment]
great!
