### ISSUE TITLE
why i64 instead of u64

### ISSUE THREAD

**Issue by nbari** [chronotope/chrono#326]
Hi, not really an issue but just curious of why the usage of `i64` when returning Unix timestamps/timestamp_nanos instead of `u64`

**Comment by quodlibetor** [comment]
Times before the epoch are negative.

**Comment by BratSinot** [comment]
But this have no sense in this cases:
```rust
            Utc::now()
                .checked_add_signed(duration)
                .expect("not valid timestamp")
                .timestamp(),
```
