### ISSUE TITLE
Daylight savings start/end time is not respected

### ISSUE THREAD

**Issue by sparky8251** [chronotope/chrono#340]
This sample code will help demonstrate the problem:

```rust
use chrono::TimeZone;
use chrono::{DateTime, Duration};
use chrono_tz::US::Eastern;
use chrono_tz::Tz;

fn main() {
    let mut dt: DateTime<Tz> = Eastern.ymd(2019,11,1).and_hms(0,0,0);
    println!("Initial datetime: {}", dt);

    // Increment to the day of daylight savings
    // but not PAST the daylight savings "border"
    dt = dt + Duration::days(3);
    println!("Day of daylight savings change: {}", dt);

    // Increment past the daylight savings "border"
    dt = dt + Duration::hours(3);
    println!("After daylight savings change: {}", dt);

}
```

When run, the output is: 
```
Initial datetime: 2019-11-01 00:00:00 EDT
Day of daylight savings change: 2019-11-03 23:00:00 EST // this is wrong
After daylight savings change: 2019-11-04 02:00:00 EST // this is right but for the wrong reason
```

At first blush, this seems correct. It is not... US Eastern ends DST this year on 2019-11-3 t 2am, not midnight.

Adding 3 days should not have tripped a DST change causing a loss of time. It should only have changed DST in the 3rd print statement.

I know the rules for start/stop of DST change by timezone and country (sometimes even more granularly, like how 2 states in the US don't respect DST), so I am unsure how to really address this... I just know it will need addressing at some point. I *think* the TZ support already handles countries, so it's likely down to finding and following the rules presented for each TZ down to the time it changes and not just the day. Hard saying though.

**Comment by quodlibetor** [comment]
Closing this in favor of the chrono-tz issue, I'll comment there.
