### ISSUE TITLE
Support for wasm32-wasi

### ISSUE THREAD

**Issue by CryZe** [chronotope/chrono#352]
It seems like wasm32-wasi isn't supported, but could very easily be supported by chrono (although I don't quite know what the situation with the time crate is nowadays).

**Comment by quodlibetor** [comment]
In what way exactly is wasm32-wasi not supported?

**Comment by CryZe** [comment]
The clock APIs (dates and co.) are directly supported through syscalls / libc on WASI unlike with wasm32-unknown-unknown. In fact most of Rust‘s std even fully works. iirc chrono‘s clock feature does not work on WASI because the time crate doesn‘t know about WASI, so it handles it the same way as the normal unknown target.

**Comment by CryZe** [comment]
This is what I'm doing as a workaround: https://github.com/LiveSplit/livesplit-core/blob/2057b3a3828bd0a2469d96b1f9713bf3f9a2e23b/src/platform/wasm/wasi/mod.rs#L9-L17

Basically since SystemTime in std works, you can just get the unix timestamp and thus a DateTime from there.

**Comment by quodlibetor** [comment]
Interesting. I'll try and set up a wasm-wasi test or definitely accept a PR adding one, and then we can flip some cfg flags to make this all work.

**Comment by quodlibetor** [comment]
if you (or anyone) wants to work on this feel free to assign it to yourself! I'll assign to myself when I start work, which probably won't be this week.

**Comment by coolreader18** [comment]
I can try working on this; it's relevant to a project I'm working on.

**Comment by quodlibetor** [comment]
There are a few more things before we actually want this to be closed:

* support for `now()` in wasi
* adding a test to CI that verifies that `now()` works in wasi.

Anyone should feel free to assign this to themselves and start working on either part of that!

**Comment by pitdicker** [comment]
We have support for `now()` from the standard library, and https://github.com/chronotope/chrono/pull/1237 added `wasm32-wasi` to the CI.
