### ISSUE TITLE
Implement comparison for DateTimes with different TimeZones

### ISSUE THREAD

**Issue by mrbus** [chronotope/chrono#354]
PartialEq is implemented for different timezones:
`impl<Tz: TimeZone, Tz2: TimeZone> PartialEq<DateTime<Tz2>> for DateTime<Tz>`
but PartialOrd is only implemented for the same timezone:
`impl<Tz: TimeZone> PartialOrd<DateTime<Tz>> for DateTime<Tz>`

Example:
```
use chrono::{Local,Utc};
if Local::now() == Utc::now() { }; // Compiles
if Local::now() < Utc::now() { }; // Does not compile
if Local::now() < Utc::now().into() { } // Compiles
```

**Comment by quodlibetor** [comment]
This should not be too hard to implement and I agree it would be a great feature!
