### ISSUE TITLE
Update try to question mark operator

### ISSUE THREAD

**Issue by hhamana** [chronotope/chrono#357]
As of Rust 1.39, it seems usage of the try!() macro is now deprecated in favor of the ? operator.
It should be a good opportunity to also update to the 2018 edition syntax (including documentation).

**Comment by quodlibetor** [comment]
chrono has a very strong back-compat policy, I'm not planning on requiring anything newer than what ships with a current LTS of debian/rhel, unfortunately. Believe me I would like to use the newest features. There are a few things that I would be willing to add behind (possibly default) feature gates, but even then it will probably be another year or two before I get to use new syntax universally :-/

**Comment by quodlibetor** [comment]
So we can't update to the new edition, but `?` was stabilized in 1.13, which is in fact the oldest release we support so that's fine to do. Commit incoming.
