### ISSUE TITLE
0.4.9->0.4.10 breaking change: no method named `to_rfc3339_opts` for type `DateTime<Utc>`

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [chronotope/chrono#364]
```rust
fn main() {
    use chrono::{DateTime, Utc, NaiveDateTime, SecondsFormat};
    let dt = DateTime::<Utc>::from_utc(NaiveDateTime::from_timestamp(42, 0), Utc);
    dbg!(dt.to_rfc3339_opts(SecondsFormat::Secs, true));
}
```
This program compiles without errors with `chrono = { version = "=0.4.9", default-features = false }`, but with `chrono = { version = "=0.4.10", default-features = false }` there is an error:
```
error[E0599]: no method named `to_rfc3339_opts` found for type `chrono::datetime::DateTime<chrono::offset::utc::Utc>` in the current scope
 --> src\main.rs:4:13
4 |     dbg!(dt.to_rfc3339_opts(SecondsFormat::Secs, true));
  |             ^^^^^^^^^^^^^^^ method not found in `chrono::datetime::DateTime<chrono::offset::utc::Utc>`
```

**Comment by CryZe** [comment]
I‘m pretty sure the no_std changes were a breaking change too, because adding a new feature for previously ungated functionality removes that functionality for everyone not using the default set of features. I haven‘t checked yet, but I believe the published version of my crate therefore likely doesn‘t compile anymore.

**Comment by quodlibetor** [comment]
Following the [Rust API guidelines](https://rust-lang.github.io/rfcs/1105-api-evolution.html) I do not believe that this should be considered a breaking change, although I agree that it is unfortunately annoying and also this isn't described _precisely_.

Specifically @Vlad-Shcherbina I believe you want to add the `alloc` feature. (You were already depending on alloc being available, it's just now explicitly required to specify it.)

**Comment by Vlad-Shcherbina** [comment]
If you don't want to call it a breaking change, fine. Still, it would be nice if the changelog mentioned this.

**Comment by quodlibetor** [comment]
I agree. I'll add a section to the changelog.

It's not only that I don't want to call it a breaking change as that I think that asking people who are already using feature flags to add a flag to their cargo.toml is _significantly_ less disruptive to the ecosystem than releasing a 0.5, while also making no-std work correctly.
