### ISSUE TITLE
Chrono is no longer able to be compiled by the playground

### ISSUE THREAD

**Issue by shepmaster** [chronotope/chrono#373]
```toml
[package.metadata.playground]
all-features = true
```

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.10/src/lib.rs:386:32
    |
386 | #![cfg_attr(feature = "bench", feature(test))] // lib stability features as per RFC #507
    |                                ^^^^^^^^^^^^^
```

**Comment by quodlibetor** [comment]
@shepmaster I believe that the linked commit #374 will fix it, what's the easiest way to verify?

**Comment by shepmaster** [comment]
> the easiest way to verify?

There isn't, really, other than to use the crate in a project that is compiled via the stable / beta / nightly compilers. Testing in the playground generally involves spinning up Docker containers and the like.
