### ISSUE TITLE
Parse String instead of &str

### ISSUE THREAD

**Issue by TheFox** [chronotope/chrono#377]
How can I parse a `String` instead of a `&'static str`?

Every example regarding Chrono is using a `&'static str`.

My code looks like this:

```rust
extern crate chrono;
use std::env;
use chrono::{DateTime, Date};

fn main() {
    let args: Vec<String> = env::args().collect();
    println!("-> args: '{:?}'", args);
    println!("-> args[1]: '{:?}'", args[1].clone());

    let d: DateTime<Local> = DateTime::parse(args[1].clone());
    let d: Date<Local> = Date::parse(args[1].clone(), "%Y-%m-%d");
}
```

The last two lines are not working. Is there something similar I can use to parse a String I do not know at compile time but maybe the format?

**Comment by quodlibetor** [comment]
You'd want to pass in a reference by using `&`:

```
    let d: DateTime<Local> = DateTime::parse(&args[1]);
    let d: Date<Local> = Date::parse(&args[1], "%Y-%m-%d");
```

note that this also gets rid of the `clone()`
