### ISSUE TITLE
Implement start_of_* and end_of_* APIs

### ISSUE THREAD

**Issue by liquidscorpio** [chronotope/chrono#383]
### Context
Back in 2015, a [similar request](https://github.com/chronotope/chrono/issues/29) for a date transition API was closed. I wish to re-open conversation for a more generalized API for the same. Such APIs are utilized extensively in time-series & analytical workloads and with chrono almost being the canonical date-time crate for Rust, there is value to be had by having such APIs within the library.

I am already building this and would like put forth a PR for the same. In the meanwhile, checking if the stance of the team on the issue has changed?

## Public Interface
Support for following methods on a `NaiveDate` instance for the following APIs:

```rust
start_of_year() // Transforms 2019-07-12 to 2019-01-01
end_of_year() // Transforms 2019-07-12 to 2019-31-12
start_of_month()  // Transforms 2019-07-12 to 2019-07-01
end_of_month()  // Transforms 2019-07-12 to 2019-07-31
start_of_week()   // Transforms 2019-07-12 to 2019-07-08
end_of_week() // Transforms 2019-07-12 to 2019-07-14
```

All the APIs can also have `start_of_pred_*` / `end_of_pred_*` / `start_of_succ_*` / `end_of_succ_*` keeping things consistent.

While I am explicitly referring to `NaiveDate`, other structs can also be considered one at a time.

**Comment by quodlibetor** [comment]
Yes, the stance has changed, I would love a PR for this!

**Comment by liquidscorpio** [comment]
Work relating to this have been moved to a new crate.
See: https://github.com/chronotope/chrono/pull/385#issuecomment-619153726 for more information.
