### ISSUE TITLE
Add MIN_DATETIME and MAX_DATETIME

### ISSUE THREAD

**Issue by Koxiaet** [chronotope/chrono#386]
Also add the naive versions. These would just be useful to have for completeness in the library.

**Comment by quodlibetor** [comment]
Agreed! The naive versions should be pretty trivial to add based on the impls of `MIN_DATE` and `MAX_DATE`, I'm not sure if tz-aware versions (maybe other than UTC?) should be added.

**Comment by technetos** [comment]
Hi, is it possible to get alittle more clarification on this?

**Comment by Koxiaet** [comment]
@technetos something like:

```rust
// in naive
pub const MIN_TIME: NaiveTime = { secs: 0, frac: 0 };
pub const MAX_TIME: NaiveTime = { secs: u32::MAX, frac: u32::MAX };
pub const MIN_DATETIME: NaiveDateTime = { date: MIN_DATE, time: MIN_TIME };
pub const MAX_DATETIME: NaiveDateTime = { date: MAX_DATE, time: MAX_TIME };

// in root
pub const MIN_DATETIME: DateTime<Utc> = { datetime: naive::MIN_DATETIME, offset: Utc };
pub const MAX_DATETIME: DateTime<Utc> = { datetime: naive::MAX_DATETIME, offset: Utc };
```

Perhaps `MIN_UTC_DATETIME` is a better name, or you could even use associated trait consts for `TimeZone` (although I don't know if that's possible).

**Comment by LAC-Tech** [comment]
Hi, while I can confirm these are now in the code, they're not in the docs (Came in here to ask about them!).

**Comment by djc** [comment]
Where are you looking? I can find them in the docs. Note: these are not associated constants, they're just bare constants in for example the `naive` module.

**Comment by LAC-Tech** [comment]
https://docs.rs/chrono/0.4.0/chrono/index.html#constants

Pretty much here. I'm pretty new to rust, so very possible this is my issue, but I can't find them documented anywhere.

**Comment by djc** [comment]
Note this link:

<img width="238" alt="Screenshot 2022-04-13 at 09 18 54" src="https://user-images.githubusercontent.com/158471/163121368-8cfffd5f-e26c-4292-9787-2363b1dfdc58.png">

You're looking at documentation for 0.4.0, which is almost 5 years old at this point.

**Comment by rikvdkleij** [comment]
The issue is that `MIN_TIME` and `MAX_TIME` of `NaiveTime` are not exposed by re-exporting while the other ones are.

**Comment by djc** [comment]
Feel free to submit a PR fixing that.

**Comment by rikvdkleij** [comment]
@djc Done, see #713
