### ISSUE TITLE
panic using stdweb

### ISSUE THREAD

**Issue by JackMordaunt** [chronotope/chrono#387]
*I have searched extensively, so please excuse me if this has been addressed.*

I'm using `stdweb` api and compiling with `cargo web`.
My `wasm` module panics with a `"not implemented"`.
I have tried all feature options including `default-features = false`, `js-sys` and `wasm-bindgen`. 

(Obviously, with `wasm-bindgen` I get `Error loading Rust wasm module 'calendar': TypeError: "import object field '__wbindgen_placeholder__' is not an Object"`)

It's unclear what exact line of of *my* code produces the panic, but it appears to be the `time` crate causing the panic. 

<img width="1285" alt="Screen Shot 2020-01-18 at 6 02 01 PM" src="https://user-images.githubusercontent.com/6916093/72658936-c1044800-3a1c-11ea-8d5f-968d1570e78d.png">

```rust
// time 0.1.42, line 102
pub fn get_time() -> (i64, i32) {
    unimplemented!()
}
```

The only types I'm using are `use chrono::{Duration, NaiveDate, NaiveDateTime, NaiveTime};`.

What am I missing? Does `chrono` work with `stdweb` or only `wasm-bindgen`?

**Comment by kristoff3r** [comment]
I had the same issue until I realized that the feature is called `wasmbind`, which imports both `wasm-bindgen` and `js-sys`. That plus `default-features = false` made it work for me with stdweb and wasm-bindgen.

 I got a bit tricked by issue #382, which is apparently a bit out of date.

**Comment by quodlibetor** [comment]
I'm going to close this because I'm pretty sure kristoff3r's comment is correct. Feel free to re-open.
