### ISSUE TITLE
Implement `NaiveDateTime::with_timezone`?

### ISSUE THREAD

**Issue by dario23** [chronotope/chrono#388]
hi,

i noticed that for `NaiveDateTime`, the `with_timezone` method is missing; where the `Naive` types are where i think i need this functionality most, to add a timezone i know from somewhere else to a timezone-less value i just parsed.

was this forgotten, or is there a reason this method cannot/should not exist? happy to open a PR if that has any chance of getting accepted :-)

**Comment by hei-pa** [comment]
Yes I need something like this too.

I have parsed a String to a `NaiveDateTime`, now my timezone comes from somewhere else and I need to contruct a `DateTime` out of this `NaiveDateTime`. It would be great to have a `with_timezone(x)` function on `NaiveDateTime` with a `DateTime` as result.

**Comment by pitdicker** [comment]
Added `with_timezone` to `NaiveDateTime` in https://github.com/chronotope/chrono/pull/1021.

**Comment by pitdicker** [comment]
https://github.com/chronotope/chrono/pull/1021 was reverted in https://github.com/chronotope/chrono/pull/1029 because we already have this functionality as [`NaiveDateTime::and_local_timezone`](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDateTime.html#method.and_local_timezone).
