### ISSUE TITLE
can you update time-rs to 0.2.5？

### ISSUE THREAD

**Issue by Silentdoer** [chronotope/chrono#389]
like title

**Comment by swarnimarun** [comment]
https://github.com/time-rs/time/releases/tag/v0.2.6 came out 2 days ago btw...

And I was just thinking about it too. Btw they had also changed the MSRV to 1.34 which is a good thing IMHO. 

Just in case it was one of the concerns.

PS: I just started using the chrono. So not really sure about how things go around here.

**Comment by swarnimarun** [comment]
Btw just a heads up 0.2.5 had a few inconsistency which had to be fixed in 0.2.6 so I recommend changing the title to the latest stable time-rs crate.

**Comment by jhpratt** [comment]
Maintainer of time checking in. MSRV is 1.34 and is verified in CI. There were some issues with v0.2.5 that have been fixed. All versions currently on crates.io are backwards-compatible with each other.

Time v0.2 was partially inspired by chrono, so building a layer on top of that should be relatively easy, and actually reduce the amount of code here. One issue chrono may run into is that time currently doesn't have support for getting the local offset, though this is planned. See time-rs/time#203 for details and a possible implementation.

**Comment by quodlibetor** [comment]
Updating to use time would change our msrv from 1.13 to 1.34, which would require at least a minor version bump, so it is unlikely to happen in the immediate future.

That said, though, I would be happy to do work to make it easier for time-0.2 and chrono to interact, via more generics or helper methods.

**Comment by quodlibetor** [comment]
I'm going to close this because the answer is "probably not, but interop is a goal.
