### ISSUE TITLE
timezone detection from the environment when parsing dates

### ISSUE THREAD

**Issue by emmanueltouzery** [chronotope/chrono#393]
I wonder if this is related to https://github.com/chronotope/chrono/issues/391...

I wrote yesterday on the gitter channel but got no answer so far.

If I parse a local date without timezone, chrono doesn't pick up the timezone that I would expect:

```rust
    let expected = DateTime::<Local>::from(Utc.ymd(2013, 9, 27).and_hms(19, 46, 35));
    assert_eq!(
        expected,
        Local
            .datetime_from_str("Sep 27 20:46:35 2013", "%b %d %T %Y")
            .unwrap()
    );
```

fails with

```
  left: `2013-09-27T21:46:35+02:00`,
 right: `2013-09-27T20:46:35+02:00`'
```

now at the time where I live it was UTC+1. But what's baffling to me is that even right now it's UTC+1 for me. So I don't understand where does chrono find the UTC+2 it seems to be taking into account when parsing? It's true that where I live, winter time is UTC+1 (CET), summer is UTC+2 (CEST). But the time i want to parse and the current time are both UTC+1? Although I'd like this to work even if the current offset was UTC+2 of course..
to be clear, the left time is correct: 19:46 UTC, I was at UTC+1, therefore 20:46 local time. But the right time thinks the time is UTC+2. I'm in the CET timezone currently and I was in that timezone also for the time I want to parse.

EDIT: i'm on linux (fedora 31)

**Comment by CryZe** [comment]
You could try to use the time crate at version 0.1.42 and call [`time::now()`](https://docs.rs/time/0.1.42/time/fn.now.html) and check its [`tm_utcoff`](https://docs.rs/time/0.1.42/time/struct.Tm.html#structfield.tm_utcoff) field. This would then let us figure out if the problem is inside chrono or time / libc.

**Comment by emmanueltouzery** [comment]
Hi, I ran it now:

    println!("UTC offset is {}", time::now().tm_utcoff);

UTC offset is 3600

That sounds right, 1h off UTC.

**Comment by CryZe** [comment]
Actually can you try [`time::now_utc()`](https://docs.rs/time/0.1.42/time/fn.now_utc.html) and then [`.to_local()`](https://docs.rs/time/0.1.42/time/struct.Tm.html#method.to_local) and debug print it? What's more important than just the pure offset is whether this conversion works correctly.

**Comment by emmanueltouzery** [comment]
println!("converted is {:?}", time::now_utc().to_local());

converted is Tm { tm_sec: 59, tm_min: 7, tm_hour: 11, tm_mday: 7, tm_mon: 1, tm_year: 120, tm_wday: 5, tm_yday: 37, tm_isdst: 0, tm_utcoff: 3600, tm_nsec: 757579703 }

I ran that at 11:07 CET, which is 10:07 UTC.

that looks good to me.

I then ran only:
    println!("converted is {:?}", time::now_utc());

and got:

converted is Tm { tm_sec: 42, tm_min: 9, tm_hour: 10, tm_mday: 7, tm_mon: 1, tm_year: 120, tm_wday: 5, tm_yday: 37, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 432660108 }

again looks good.

**Comment by CryZe** [comment]
Mmh yeah, then I guess you probably should introduce a bunch of debug prints into chrono then.

**Comment by emmanueltouzery** [comment]
maybe you can give me a hint as to where to start? I'm not even sure what chrono is supposed to do in that case? Search for the timezone that would have held for me at that time? Or use the timezone as it is now on my machine (which would be wrong i guess).

**Comment by CryZe** [comment]
You'd clone it locally and probably introduce a bunch of debug prints all over the place here: https://github.com/chronotope/chrono/blob/master/src/offset/local.rs#L83-L164

**Comment by emmanueltouzery** [comment]
Ok I'm very sorry, it was my mistake, and a misunderstanding of chrono as well.

So, first off, sep 27 is summer time here, not winter time. Therefore that date _was_ utc+2 for me, not utc+1. But that's not the whole issue that I had. The other thing is that I thought that:

```rust
let expected = DateTime::<Local>::from(Utc.ymd(2013, 9, 27).and_hms(19, 46, 35));
```

would use the local time _for that date_. but it does not. So that Local would mean "local time" (eg CET or CEST, depending on the date), not "local timezone right now" (CET), if that makes any sense. it uses the local time as of now (always CET, no matter the parameter given to `from`). Which isn't _wrong_. So now I use rather:

```rust
let expected = FixedOffset::east(7200).ymd(2013, 9, 27).and_hms(20, 46, 35);
```

And now everything works! So again I apologize, it was strictly my mistake!
