### ISSUE TITLE
Add month

### ISSUE THREAD

**Issue by mirecl** [chronotope/chrono#397]
Hi, guys.
Help pls, how to add month to date?
For example
let dt = utc;
dt.add_month(1)

**Comment by Luro02** [comment]
I think you need the `DateLike` trait:
https://docs.rs/chrono/0.4.11/chrono/trait.Datelike.html#tymethod.with_month

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting
