### ISSUE TITLE
Update time crate to 0.2

### ISSUE THREAD

**Issue by estk** [chronotope/chrono#400]

**Comment by CryZe** [comment]
The problem is that time 0.2 is effectively a completely different crate from time 0.1, so this is not quite that trivial and I think it even lost some functionality.

**Comment by estk** [comment]
Wow, thanks @CryZe for the ultra fast response. Ya I've looked into it and for sure totally different. Are you thinking you'll proceed with #286  instead?

**Comment by quodlibetor** [comment]
yeah sorry that we now have time 0.2 showing up next to 0.1 in dep graphs, I'm working on absorbing the time crate without it being a back-compat problem, which mostly means adding a bunch of `From` implementations and I suppose putting it behind a default-included feature gate.

**Comment by quodlibetor** [comment]
I'm going to leave this open because people keep re-creating it, but the correct answer is indeed issue 286

**Comment by estk** [comment]
Roger, thanks for the update, will you link the pr here so I'll get notified when that work is done?

**Comment by quodlibetor** [comment]
@estk you can subscribe to a single PR/issue by clicking the "subscribe" button on the right column in github, under notifications:
![image](https://user-images.githubusercontent.com/277161/76420261-3a168080-6378-11ea-91bf-a5d478651b87.png)

you should do that if you care about it, although yeah this issue will also be closed when that's done.

**Comment by jhpratt** [comment]
@CryZe What behavior is missing that is needed? Obviously I'm biased, but the breadth of the API is pretty similar.

**Comment by RustySheldon** [comment]
I stand with the proposal as time crate 0.1.x cannot be compiled on some target platform (eg. x86_64-unknown-hermit) due to missing internal `sys` crate.
