### ISSUE TITLE
Sequential calls to Utc::now() result in identical values

### ISSUE THREAD

**Issue by mulkieran** [chronotope/chrono#402]
See https://github.com/stratis-storage/stratisd/pull/1897 here, and its related issue.

I'm not sure that this would be considered a bug as I don't know if there are any guarantees that these values should be different. The situation took years to show up, though, and it is a little weird, so I'm letting you know.

If you say there is no guarantee that they be different, then I'm satisfied.

**Comment by CryZe** [comment]
I don't think you can rely on now() being unique at all. Leap seconds result in duplicate time stamps. Synchronization with a time server can rewind your clock, which yet again results in duplicate time stamps. The resolution of the internal clock may just be too low, which is likely what happened here, results in duplicate time stamps. So not only is Utc::now() not strongly monotonic, but it's not even monotonic either.

**Comment by mulkieran** [comment]
Thanks!
