### ISSUE TITLE
Cannot parse date with NaiveDateTime::parse_from_str()

### ISSUE THREAD

**Issue by makorne** [chronotope/chrono#404]
Hi,
My example code:

```
#[test]
fn test_chrono() {
	let r = NaiveTime::parse_from_str("Mar 28 10:23", "%H:%M");
	println!("{:?}", r);
	println!("{:?}", r.err().unwrap().description());
	let d = NaiveDateTime::parse_from_str("Mar 28 10:23 CEST", "%b %d %R");
	println!("{:?}", d);
	println!("{:?}", d.err().unwrap().description());
	assert!(false) // to get the error output
}
```

It yields:

Err(ParseError(Invalid))
"input contains invalid characters"

What am I doing wrong?

**Comment by quodlibetor** [comment]
The `parse_from_str` expects to parse the entire string, it is starting with a date that is not in the parse string.

The second one that is failing is because, also, you're not matching the entire string.

**Comment by makorne** [comment]
> The second one that is failing is because, also, you're not matching the entire string.
I am trying to find in docs how to parse "CEST" world in "Mar 28 10:23 CEST" but can't find.
Is it inpossible with chrono?

Thank you!
