### ISSUE TITLE
Unable to parse custom datetime

### ISSUE THREAD

**Issue by srikwit** [chronotope/chrono#414]
Hi Team,

I am trying to parse a custom date time from string and am facing a lot of issue in parsing the following string:
`DateTime::parse_from_str("Sunday 26 April  03:00:01 ACST 2020","%A %d %B  %T %Z %Y")`

I have even tried the explicit variant of this as:
`DateTime::parse_from_str("Sunday 26 April  03:00:01 ACST 2020","%A %d %B  %H:%M:%S %Z %Y")` but it is not working.

Please note that there seems to be two spaces between %B and %H.

I am getting the following error: `bad or unsupported format string`
However, all of the format specifiers seem to be as expected from: https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html.

Kindly help me resolve this issue.

**Comment by pitdicker** [comment]
This is the problem that chrono can't (currently) parse strings with a timezone abbreviation; the `%Z` specifier.
The abbreviation is skipped instead.

This causes the parsed result to habe all the date and time fields, but no UTC offset.
You can parse to `NaiveDateTime` instead

If you have a way to get the offset from somewhere else, it can be used to convert that to a full `DateTime`.

**Comment by pitdicker** [comment]
I reopened the related issue https://github.com/chronotope/chrono/issues/38 because it is older and has some useful discussion.
Closing this one as a duplicate.
