### ISSUE TITLE
NaiveDateTime::from_millis

### ISSUE THREAD

**Issue by GopherJ** [chronotope/chrono#430]

**Comment by GopherJ** [comment]
This method is missing

**Comment by GopherJ** [comment]
It's super ugly to do:
```rust
   NaiveDateTime::from_timestamp(
                                                                    (timestamp / 1000) as i64,
                                                                    0,
                                                                )
```

**Comment by Pscheidl** [comment]
> It's super ugly to do:
> 
> ```rust
>    NaiveDateTime::from_timestamp(
>           (timestamp / 1000) as i64,
>           0,
>    )
> ```

Doing this results in reduced precision, as millis from the last second are lost. Do this instead (then it gets even more verbose).

```rust
        let secs = millis / 1000;
        let nsecs = (millis % 1000) as u32 * 1_000_000;
        NaiveDateTime::from_timestamp_opt(secs, nsecs)
```

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/818, backported to 0.4.x in https://github.com/chronotope/chrono/pull/823.
