### ISSUE TITLE
chrono::naive::serde::ts_milliseconds_option not found

### ISSUE THREAD

**Issue by GopherJ** [chronotope/chrono#434]

**Comment by quodlibetor** [comment]
Could you expand on this? Do you have the `serde` feature enabled?

**Comment by GopherJ** [comment]
@quodlibetor HI, I do have `serde` feature enabled I would like to be able to serialize `Option<NaiveDateTime>`,

but I cannot find equivalent `ts_milliseconds_option` serializer for `NaiveDateTime`

**Comment by quodlibetor** [comment]
Ah, yes I see. I agree that that should exist. I'd be happy to take a PR implementing it, or I will add it eventually, but there are some larger things I'm working on that means I won't be able to do it immediately.

As a workaround you should be able to deserialize to a `DateTime<Utc>` and just extract to a naive time with exactly the same performance and semantics.

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/664.
