### ISSUE TITLE
Feature Request: LDAP/FileTime epochs 

### ISSUE THREAD

**Issue by xd009642** [chronotope/chrono#440]
LDAP and windows Filetime uses the number of 100 nanosecond ticks since Jan 1, 1601 UTC, it could be nice for anyone being forced to work with this time to be able to create a DateTime from these timestamps.

**Comment by quodlibetor** [comment]
Do you have a link to the documentation for the definition of that epoch? I've never seen it, what would you expect to see other than `from_filetime`/`to_filetime` methods, does it have any weird interactions with regular time/leap seconds?

**Comment by xd009642** [comment]
Here's microsoft documentation https://docs.microsoft.com/en-us/windows/win32/sysinfo/file-times apparently it's also used in LDAP, COBOL and the base time it comes from is the start of the 400 year leap year cycle. 

I first bumped into it today working with some ASF media files and I looked in the format appendix and found:

```
        15.2 FILETIME 
A 64-bit integer that contains a time stamp corresponding to the number of 100 nanosecond ticks since January 1, 1601. The following diagram demonstrates the filetime format:

   (MSB)                                                                            (LSB)
   +--------+--------+--------+--------+--------+--------+--------+--------+
   |byte 0 |byte 1 |byte 2 |byte 3 |byte 4 |byte 5 |byte 6 |byte 7 |
   +--------+--------+--------+--------+--------+--------+--------+--------+
   <--------------------------------- 64 bits -------------------------------->

The GMT time zone is used for all filetime entries.
```

If it's some help this is currently what I've implemented to sort it out in my own code (no guarantees of correctness yet I'm still to try it out on a file using that timestamp format):

```Rust
pub fn file_time_to_naive_datetime(timestamp: u64) -> Option<NaiveDateTime> {
    const SECONDS_BETWEEN_1601_AND_1970: i64 = 11_644_473_600;
    let nano_seconds = (timestamp % 1e-7) as i64 * 100;
    let seconds = (timestamp/1e-7) as i64 + SECONDS_BETWEEN_1601_AND_1970;
    NaiveDateTime::from_timestamp_opt(seconds, nano_seconds)
}
```

**Comment by quodlibetor** [comment]
Thanks!

My inclination right now is that this is pretty obscure and the only feature necessary is the function that you've provided. That said:

* I'm open to adding more features around this if folks feel like it is beneficial to have in chrono
* I would like to support something more like C++ chrono's epoch types in the future, which I think might provide more tight alignment with this epoch out of the box.

**Comment by xd009642** [comment]
Yeah C++ epoch types would be good, I did check the chrono docs for an equivalent to them when going to implement this :+1:

**Comment by quodlibetor** [comment]
I'm going to close this _with the specific intention_ that if someone believes that it should be re-opened, they should re-open it with a comment explaining what functionality should be added.
