### ISSUE TITLE
Calendar Implementations ala Jvm  

### ISSUE THREAD

**Issue by jnorthrup** [chronotope/chrono#449]
I recently noticed this issue was brought up in the main tree and unceremoniously dumped without any follow up.  This seems unfinished and qualifies as barriers to entry in porting existing codebases to Rust language.

The issue above links to a non-issue tracking site, but this is a "chrono" external lib and seems like a good place to point to/from

https://github.com/rust-lang/rust/issues/63532

**Comment by quodlibetor** [comment]
I'm not sure what this issue is meant to say?

**Comment by jnorthrup** [comment]
it's saying there's an issue rust-lang/rust#63532, that applies to a project like this one, so ordained by the guy who closed it to avoid an RFC process and main language discussion about calendars.

**Comment by jnorthrup** [comment]
looks like i was under the misimpression the original rustlang issue-closing was referring to a different crate, and I have created a dupe.  will close this one.
