### ISSUE TITLE
NaiveDateTime::parse_from_str with format "%Y-%m-%d %I-%p" doesn't work (NotEnough)

### ISSUE THREAD

**Issue by harrisonthorne** [chronotope/chrono#451]
Is this an intentional feature or a bug? I'm trying to parse a date-time like this:

```
2020-07-08 02-PM
```

via:

```rust
            let date = match NaiveDateTime::parse_from_str(&record[0], "%Y-%m-%d %I-%p") {
                Ok(d) => d,
                Err(e) => {
                    eprintln!("{}", e);
                    return;
                }
            };
```

which is giving me:

```
input is not enough for unique date and time
```

edit: syntax formatting

**Comment by NickelCoating** [comment]
The non naive version got the same issue. I'm getting a panic:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(NotEnough)'

For my use case:
`let custom = DateTime::parse_from_str("05.08.1994", "%d.%m.%Y").unwrap();`, too.

And eve with the same formatting as yours:
`let custom = DateTime::parse_from_str("2020-07-08 02-PM", "%Y-%m-%d %I-%p").unwrap();`

**Comment by NickelCoating** [comment]
Does `parse_from_str` work at all for anybody? Because no matter what I try the NotEnough error is always there. 

The only thing that worked for me was the example's:
`let custom = DateTime::parse_from_str("5.8.1994 8:00 am +0000", "%d.%m.%Y %H:%M %P %z").unwrap();`

All these raise a NotEnough panic:
```
let custom = DateTime::parse_from_str("5.8.1994 8:00 am", "%d.%m.%Y %H:%M %P").unwrap();
let custom = DateTime::parse_from_str("07/08/01", "%D").unwrap();
let custom = DateTime::parse_from_str("2020", "%Y").unwrap();
let custom = DateTime::parse_from_str("01", "%d").unwrap();
let custom = DateTime::parse_from_str("01", "%m").unwrap();
let custom = DateTime::parse_from_str("01", "%S").unwrap();
let custom = DateTime::parse_from_str("00:34", "%R").unwrap();
let custom = DateTime::parse_from_str("01", "%M").unwrap();
```

**Comment by quodlibetor** [comment]
`DateTime::parse_from_str` requires that it successfully parse an *entire* DateTime -- full date and time and timezone. Partial items can be parsed from [`NaiveDate::parse_from_str`](https://docs.rs/chrono/0.4.13/chrono/naive/struct.NaiveDate.html#method.parse_from_str) and [`NaiveDateTime::parse_from_str`](https://docs.rs/chrono/0.4.13/chrono/naive/struct.NaiveDateTime.html#method.parse_from_str), which you could use to build parts and add other times.

I agree that those error messages are not great.

**Comment by quodlibetor** [comment]
To be clear: your first example is missing both minutes and seconds, and your last items are missing many things. I would like to add a `parse_from_str_default` method. It's not super common for folks to want to do that so it hasn't been a particularly high priority. If you're interested I'd be happy to help you implement it, I don't think it'd be particularly hard.

**Comment by quodlibetor** [comment]
Actually I take it back I always forget how complicated that code is, and there isn't a straightforward way to just add a default and have it apply everywhere. It's definitely doable, but not trivial.

**Comment by NickelCoating** [comment]
Ah, my bad. I already had a feeling... too many errors. :)

Yeah, I can make a simple hack for myself. I just add 00:00:00 to the actual date that I need in the whole string, and it works. The single picks for seconds and days, etc., that was only for testing. Thanks!

**Comment by quodlibetor** [comment]
Alright I'll close this feel free to comment on #191 if you run into something that requires defaults.

**Comment by q2p** [comment]
Parsing `Tuesday 21 October 2012 05:12:56 AM CDT` with `%A %-d %B %Y %I:%M:%S %p %Z` also doesn't work. But it has all the necessary fields. Are there any intentions on fixing this?
