### ISSUE TITLE
rfc_2822 too long error

### ISSUE THREAD

**Issue by GopherJ** [chronotope/chrono#462]
![image](https://user-images.githubusercontent.com/33961674/88464867-6ca3be80-cebe-11ea-8164-6998d83c1473.png)

```rust
  1   fn main() {   ▶︎ Run | Debug
    1     let date = chrono::DateTime::parse_from_rfc2822("Fri, 24 Jul 2020 19:28:51 +0000 (UTC)");
    2     assert!(date.is_err());
    3
    4     let date = chrono::DateTime::parse_from_rfc2822("Fri, 24 Jul 2020 19:28:51 +0000 UTC");
    5     assert!(date.is_err());
    6 }
```

**Comment by nabijaczleweli** [comment]
Unsurprisingly, [passing a valid RFC2822 date](https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=4de49725158306c0912e4be8353f20db) works:
```rust
extern crate chrono; // 0.4.13
fn main() {
    let date = chrono::DateTime::parse_from_rfc2822("Fri, 24 Jul 2020 19:28:51 +0000 (UTC)");
    assert!(date.is_err());

    let date = chrono::DateTime::parse_from_rfc2822("Fri, 24 Jul 2020 19:28:51 +0000 UTC");
    assert!(date.is_err());

    let date = chrono::DateTime::parse_from_rfc2822("Fri, 24 Jul 2020 19:28:51 +0000");
    assert!(date.is_ok());
}
```

You might be looking for something looser, like [`mailparse::dateparse()`](https://docs.rs/mailparse/0.13.0/mailparse/fn.dateparse.html).

**Comment by GopherJ** [comment]
@nabijaczleweli emm... Yes I'm parsing mail date.... thanks

**Comment by Finomnis** [comment]
@nabijaczleweli  Would you mind elaborating why this is invalid rfc2822? According to https://datatracker.ietf.org/doc/html/rfc2822#section-3.3, the string can be ended with an `CFWS`, which (to my understanding) would match `(UTC)`.
