### ISSUE TITLE
Iterating through all dates within a range

### ISSUE THREAD

**Issue by dmitriibundin** [chronotope/chrono#471]
Is there an out-of-the box way to iterate over all `NaiveDate` dates within some interval (e.g for interval 2020-05-30, 2020-06-02 there would be 2020-05-30, 2020-05-31, 2020-06-01)?

**Comment by quodlibetor** [comment]
the next release (should be this week) will include `iter_days()`, until then you can use the main branch or use the [`succ()` method](https://docs.rs/chrono/0.4.13/chrono/naive/struct.NaiveDate.html#method.succ) in a loop.
