### ISSUE TITLE
Binary assignment and other features in newer version of the `time` crate

### ISSUE THREAD

**Issue by TianyiShi2001** [chronotope/chrono#479]
The the lateset release of chrono (v0.4.15) does not support binary assignment operators such as `AddAssign` and `SubAssign` as well as other features due to its dependence on an old version of the `time` crate:

For example, this won't work:

```
let mut instant = Local::now();
let mut duration = Duration::seconds(1);
instant += duration;
duration += duration;
```

Does chrono plan to migrate to a newer version of `time`?

**Comment by benesch** [comment]
Not the maintainer, but I believe the plan is to move off the time crate entirely. See #400.

**Comment by quodlibetor** [comment]
benesch is correct, the plan is to move off the time crate. AddAssign/SubAssign will be implemented for the chrono-local versions of those structs, though.
