### ISSUE TITLE
TimeZone::datetime_from_str() fails on "2020-09-25T17:32:13.678995871+01:00"

### ISSUE THREAD

**Issue by theWebalyst** [chronotope/chrono#489]
I've been trying to parse dates of the form "2020-09-25T17:32:13.678995871+01:00" using chrono `datetime_from_str()` without success (although I can parse them using `DateTime::parse_from_rfc3339("2020-09-25T17:32:13.678995871+01:00")`.

Here's a couple of playgrounds illustrating what isn't working.

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b206641db1eb920795a17c2e9b0a1318) for:
```
use chrono::{Utc, TimeZone};

fn main()
{
    
   match Utc.datetime_from_str("2020-03-18T23:08:36.8098960+05:30", "%+") {
       Ok(time) => {
           println!("bingo: {}", time);
       }
       Err(e) => {
           println!("woops: {}", e);
       }
   };
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7d5a46d3e33b23f79ae61819cca86ad5) for:
```
use chrono::{Utc, DateTime, Local, TimeZone};

fn main()
{
    
   match Local.datetime_from_str("2020-03-18T23:08:36.8098960+05:30", "%+") {
       Ok(time) => {
       let then_utc: DateTime<Utc> = time.with_timezone(&Utc);
           println!("bingo: {}", then_utc);
       }
       Err(e) => {
           println!("woops: {}", e);
       }
   };
}
```

I'm not sure if this is a bug, but if not I'm stuck and I'm not the only one, having [posted](https://users.rust-lang.org/t/how-to-use-utc-date-from-str/49390?u=happybeing) to the community forum.

Meanwhile this [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7d5a46d3e33b23f79ae61819cca86ad5) works, using `DateTime::parse_from_rfc3339("2020-09-25T17:32:13.678995871+01:00")`.

**Comment by quodlibetor** [comment]
Ah, sorry this documentation could be improved: you want `DateTime::parse_from_str(time, "%+")`, not `<TimeZone>::datetime_from_str`: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c1a93522211ee822131f8957e65a7f98)

Parsing a timezone string from a datetime can't parse an embeded timezone. I suppose this could be altered to automatically convert into the target timezone? Honestly not sure if that would be more surprising or convenient for folks. Based on this, probably convenient.

**Comment by theWebalyst** [comment]
Thanks, my suggestion is to include at least a trivial example in documentation. It feels like I should have been able to figure that out, but its a familiar issue that when you are new, you have no idea which knobs to tweak, but an example can eliminate many of the possibilities.
