### ISSUE TITLE
#478 breaks illumos

### ISSUE THREAD

**Issue by papertigers** [chronotope/chrono#490]
After this PR was merged chorno no longer compiles on illumos:
```
error[E0425]: cannot find function `tzset` in the crate root
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.18/src/sys/unix.rs:81:15
   |
81 |             ::tzset();
   |               ^^^^^ not found in the crate root
   |
help: consider importing this function
   |
11 | use oldtime::tzset;
   |

   Compiling tempfile v3.1.0
   Compiling http-body v0.3.1
error: aborting due to previous error
```

**Comment by CryZe** [comment]
I haven't reported it yet, but I'm running into the same issue: https://github.com/LiveSplit/livesplit-core/runs/1180564388?check_suite_focus=true#step:6:255

**Comment by quodlibetor** [comment]
I see where that's coming in, it should be a straightforward fix.

**Comment by papertigers** [comment]
```diff
diff --git a/src/sys/unix.rs b/src/sys/unix.rs
index 762e234..333b198 100644
--- a/src/sys/unix.rs
+++ b/src/sys/unix.rs
@@ -44,13 +44,14 @@ fn tm_to_rust_tm(tm: &libc::tm, utcoff: i32, rust_tm: &mut Tm) {
     rust_tm.tm_utcoff = utcoff;
 }

+#[cfg(any(target_os = "nacl", target_os = "solaris", target_os = "illumos"))]
+extern "C" {
+    fn tzset();
+}
+
 #[cfg(any(target_os = "nacl", target_os = "solaris", target_os = "illumos"))]
 unsafe fn timegm(tm: *mut libc::tm) -> time_t {
     use std::env::{remove_var, set_var, var_os};
-    extern "C" {
-        fn tzset();
-    }
-
     let ret;

     let current_tz = var_os("TZ");
@@ -78,7 +79,7 @@ pub fn time_to_local_tm(sec: i64, tm: &mut Tm) {
         }
         #[cfg(any(target_os = "solaris", target_os = "illumos"))]
         let gmtoff = {
-            ::tzset();
+            tzset();
             // < 0 means we don't know; assume we're not in DST.
             if out.tm_isdst == 0 {
                 // timezone is seconds west of UTC, tm_gmtoff is seconds east
```

```
# cargo test --features unstable-locales
......snip......
test result: ok. 228 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

I have this drafted up.  If calling that tzset() is the actual intentions of this code.  I am not familiar with this crate so I didn't want to hastily file an incorrect PR

**Comment by quodlibetor** [comment]
@papertigers if it's easy enough for you to try working off of #491 it is a less drastic divergence from the legacy time v0.1 code, and so might be less likely to break other folks' APIs.

Also @CryZe it seems like you're often pretty able to check my PRs against your code, if you want to give that a shot I'd be happy to get out a 0.4.19 asap.

**Comment by papertigers** [comment]
Thanks @quodlibetor this looks good and it builds on illumos.  I can confirm all tests pass for me with the crate as well.
Blah what really tripped me up was I was looking at the wrong branch.  Thanks for the quick fix!

**Comment by quodlibetor** [comment]
> what really tripped me up was I was looking at the wrong branch

Your code looked super reasonable! I just had something else already. Hopefully 0.4.19 works well :-)
