### ISSUE TITLE
Conversion between `DateTime<Utc>` and `std::time::Instant`

### ISSUE THREAD

**Issue by zserik** [chronotope/chrono#498]
What is currently the most correct way to (fallible) way to convert a `DateTime<Utc>` (assuming it is in the future. if it isn't I won't need the result (but there are use cases where this would be needed, I think)) to an `std::time::Instant` under the assumption that the system time doesn't/hasn't changed in the interval between now and the specified time?

I think if the time is in the future, I could get away with a roundtrip through `(std:now() + (duration)(dtu - old:now()).to_std())`, which I need to be able to set a timer to updated some database entries at scheduled times, which are recorded as `UtcDateTime`'s (e.g. some database entries have a timeout which is pinned to UTC times). I'm not completely sure if thats correct tho.

**Comment by quodlibetor** [comment]
There is no way to convert a datetime to an instant. Instant's don't represent real time in any sense, from [the docs](https://doc.rust-lang.org/std/time/struct.Instant.html): 

> Instants are opaque types that can only be compared to one another. There is no method to get "the number of seconds" from an instant. Instead, it only allows measuring the duration between two instants (or comparing two instants).

Your solution seems reasonable to me.
