### ISSUE TITLE
impl Serialize/Deserialize for Date

### ISSUE THREAD

**Issue by djc** [chronotope/chrono#503]
While `DateTime` implements the serde traits, `Date` currently doesn't appear to. Would be nice to have.

**Comment by quodlibetor** [comment]
NaiveDate does, and it should be preferred to `Date` in general: https://docs.rs/chrono/0.4.19/chrono/naive/struct.NaiveDate.html#impl-Serialize

**Comment by quodlibetor** [comment]
I'm going to close this as a misunderstanding, but feel free to re-open if you truly want serde for `Date<Tz>`

**Comment by flip111** [comment]
@quodlibetor OffsetDateTime has this method https://docs.rs/time/0.2.6/time/struct.OffsetDateTime.html#method.date how to go to NaiveDate though ?
