### ISSUE TITLE
FixedOffset and more struct must be support  serde_json!!!!!

### ISSUE THREAD

**Issue by zhuxiujia** [chronotope/chrono#515]
FixedOffset and more struct must be support  serde_json!!!!!

If you don't want to support JSON serialization，
I can't add it myself！！

**Comment by quodlibetor** [comment]
You need to enable the `serde` feature.

**Comment by quodlibetor** [comment]
Also just FYI it is possible to impl derive for a remote crate, because serde is amazing: https://serde.rs/remote-derive.html
