### ISSUE TITLE
impl Serialize for Date?

### ISSUE THREAD

**Issue by loafofpiecrust** [chronotope/chrono#521]
I'm building an application which parses many dates without a specific time (birthdays, publish dates of books, etc) like so `1964-02-01`, then serializes a containing data structure to JSON. To use `chrono`, I have to artificially add a zero time `0:00:00` to these dates to deserialize them to `chrono::DateTime`. What I really want to use is `chrono::Date` in my serializable struct, but it doesn't `impl Serialize`/`impl Deserialize`. Would that be possible to add?

Thank you! I can draft up a PR but I want to make sure this doesn't conflict with current `chrono` goals first.

**Comment by robyoung** [comment]
With the `serde` feature flag [`Serialize` is implemented on `NaiveDate`](https://github.com/chronotope/chrono/blob/main/src/naive/date.rs#L1799).
See this [playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d83ee3aa99aaab0d0f3884576e4c180b)

**Comment by loafofpiecrust** [comment]
Oh I totally missed that when I last looked at the docs. Thank you very much, that should work for me!
