### ISSUE TITLE
the trait `Sub<NaiveDate>` is not implemented for `chrono::NaiveDateTime`

### ISSUE THREAD

**Issue by davidssmith** [chronotope/chrono#523]
I don't understand why you can't subtract a `NaiveDate` from a `NaiveDateTime`. Shouldn't this be possible without too much worry? I can't think of an edge case in which it isn't merely subtracting the dates and ignoring the time part.

**Comment by davidssmith** [comment]
Oh, is it because you need to yield a duration, and you need the time part for that? I guess my usage goes against the standard sense of the math operators in the crate.

I want to be able to subtract a date from a datetime and yield a shifted datetime. Is there a better way to do that?

**Comment by robyoung** [comment]
I'm struggling to understand exactly what you need. Could you give some example operations and what you would expect as the result please?

**Comment by davidssmith** [comment]
```
let datetime1 = NaiveDateTime::parse_from_str(text1, some_fmt1)?;
let date2 = NaiveDate::parse_from_str(text2, some_fmt2)?;
let diff = datetime1 - date2;
```
What should `diff` be?

Currently, I have to convert `date` to a `NaiveDateTime` in order to subtract them, which is ok and understandable, but annoying. I was wondering if we could make the user experience a little better by having a default behavior for subtracting `NaiveDate` from a `NaiveDateTime`, like a `Duration` that ignores the time part, or assumes that the time part is all zeroes?

If this answer is no, then that's ok. The issue can be closed in that case.

**Comment by robyoung** [comment]
Are you expecting `diff` to be something other than a `Duration`?

**Comment by davidssmith** [comment]
Not necessarily

**Comment by robyoung** [comment]
I'll put it another way. Is there anything other than a `Duration` that you think `diff` _could_ be? I can't think of anything, but if there is an ambiguity that I'm missing I don't want to charge in, spend a lot of effort, only to realise that it's not quite as simple as I first thought.

**Comment by davidssmith** [comment]
It could yield another date, which was my initial thought, but that doesn't make much sense after you think about it some.

**Comment by Kinrany** [comment]
Drive by comment: there are at least two possible results that make sense. The date can be interpreted as either the datetime with `NaiveTime::from_hms(0, 0, 0)` or the interval between that and the same datetime of the next date. Substitution would be either the difference between datetimes or the distance between the datetime and the interval.

**Comment by djc** [comment]
I don't think it makes sense to have this. If you want to substract a `NaiveDate` from a `NaiveDateTime`, you can just call `NaiveDate::and_hms()` on the `NaiveDate` to turn it into a `NaiveDateTime`, which would make it unambiguous what timestamp you're comparing with.
