### ISSUE TITLE
Default implementation for `Datetime<Utc>`? 

### ISSUE THREAD

**Issue by gabhijit** [chronotope/chrono#529]
Generally, whenever `Datetime<Utc>` is used as a part of any 'struct', it's not possible to `#[derive(Default)]` on that struct. Not sure, but does it make sense to have Default implementation for this particular case - Where it defaults to 0.0 seconds since Epoch UTC? 

Due to 'orphan'ing rules, it cannot be derived outside the crate and then one has to add a wrapper for that, which makes `serde` a bit involved on such `struct`s. 

If it makes sense, it's a good idea to have `Default` for this.

**Comment by malthe** [comment]
This was added in #506 (despite the title suggesting otherwise).

**Comment by gabhijit** [comment]
Implemented in #506 hence closing this issue.
