### ISSUE TITLE
chrono panics on a valid input string

### ISSUE THREAD

**Issue by omayerg** [chronotope/chrono#531]
```rust
 use chrono::format;

fn main() {
    let p = &mut format::Parsed::new();
    format::parse(p, "MONYAŽA Šander`",
    format::StrftimeItems::new("%A, %e-%h-%y %H:%M:%S"));
    
    println!("No panic");
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f184e5164c1f41834f9c122991e1932d))

Expected null result, but actually it panics.
It seems chrono parser misses the case where a string starts with a valid datetime part, e.g. SUN, MON, TUE... but then have non-ascii characters. For example, running the above string without letting it start with any three letters that represents a day of week doesn't panic.

**Comment by pitdicker** [comment]
This is fixed by https://github.com/chronotope/chrono/pull/1024.
