### ISSUE TITLE
Contra documentation, now() requires std

### ISSUE THREAD

**Issue by dfoxfranke** [chronotope/chrono#535]
The chrono documentation describes the `clock` feature as follows:

`clock`: enables reading the system time (`now`), independent of whether `std::time::SystemTime` is present, depends on having a libc.

But this is not the case: `clock` pulls in `std`, and the implementation of `Utc::now()` is just a wrapper around `std::time::SystemTime::now()`.

**Comment by pitdicker** [comment]
The current readme describes the `clock` feature as:
>  * `clock`: Enables reading the system time (`now`) and local timezone (`Local`).

And the main documentation in `lib.rs`:
> - `clock`: Enables reading the system time (`now`) that depends on the standard library for UNIX-like operating systems and the Windows API (`winapi`) for Windows.

The documentation in `lib.rs` still needs some updating, but at least we no longer it is "independent of whether `std::time::SystemTime` is present".

**Comment by pitdicker** [comment]
The documentation in `lib.rs` is updated in https://github.com/chronotope/chrono/pull/1260.
