### ISSUE TITLE
Weekday doesn't implement Step

### ISSUE THREAD

**Issue by koenichiwa** [chronotope/chrono#538]
I'm working on the cron library, and I was doing some preliminary research on how to get all types to comply with chrono's types. Currently the type of weekdays on cron's side is u32, but I would like it to be of chrono::Weekday.

Now I need to iterate over a range of weekdays. Rust is telling me that Weekday doesn't implement the Step trait though. I know that there is a related issue: https://github.com/rust-lang/rust/issues/42168

Are there plans to implement this this trait in the future? Otherwise, is there a way to work around this?

**Comment by pitdicker** [comment]
As you wrote the `Step` trait is unstable and doesn't seem to make much progress. I think it is best to close this issue, as there is nothing we can do for the foreseeable future.

https://github.com/chronotope/chrono/issues/208 also tracks the `TrustedLen` and `Step` traits.
