### ISSUE TITLE
Yank broken versions

### ISSUE THREAD

**Issue by kornelski** [chronotope/chrono#540]
chrono 0.1 predates Rust 1.x and doesn't compile any more at all.

```text
error: expected identifier, found `"time"`
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.1.18/src/lib.rs:192:14
    |
192 | extern crate "time" as stdtime;
    |              ^^^^^^ expected identifier
```

Could you yank it?

I'm testing my dependencies with `-Z minimal-versions`, and these broken chrono versions are getting picked up.

```bash
cargo yank --vers 0.1.0
cargo yank --vers 0.1.1
cargo yank --vers 0.1.2
cargo yank --vers 0.1.3
cargo yank --vers 0.1.4
cargo yank --vers 0.1.5
cargo yank --vers 0.1.6
cargo yank --vers 0.1.7
cargo yank --vers 0.1.8
cargo yank --vers 0.1.9
cargo yank --vers 0.1.10
cargo yank --vers 0.1.11
cargo yank --vers 0.1.12
cargo yank --vers 0.1.13
cargo yank --vers 0.1.14
cargo yank --vers 0.1.15
cargo yank --vers 0.1.16
cargo yank --vers 0.1.17
cargo yank --vers 0.1.18
```

**Comment by pitdicker** [comment]
Isn't it the responsibility of the crate that includes chrono to specify the correct minimum version it builds with?

**Comment by djc** [comment]
I'm confused -- presumably you depend on 0.4, so why do the 0.1 dependencies show up?

**Comment by kornelski** [comment]
They're sometimes pulled in when using `-Z minimal-versions`. 

I'm using minimal versions to detect crates' MSRV.
