### ISSUE TITLE
chrono assumes TimeZone's offset's debug format is valid RFC3339

### ISSUE THREAD

**Issue by nkovacs** [chronotope/chrono#544]
I originally opened [this issue](https://github.com/kennytm/tzfile/issues/2) in tzfile, but I think it might be a chrono issue.

[Chrono assumes that the debug format of a TimeZone's offset will be valid RFC3339](https://docs.rs/chrono/0.4.19/src/chrono/datetime.rs.html#2066), but this isn't the case for tzfile's ArcTz. Would it not make more sense to use to_rfc3339, or to use offset.fix()?

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/1035.
