### ISSUE TITLE
Unpin chrono to time 1.43, or update it to time 1.44

### ISSUE THREAD

**Issue by rodya-mirov** [chronotope/chrono#547]
Hello, no idea what the cost of this change would be, so feel free to close if it's a big problem; but I'm just trying to get clean output from `cargo outdated`, and I've found I'm loading an old version of `time` (1.43, where there is a patch update 1.44 and a possibly-breaking update to 2.26).

Any chance this could get bumped, or have the version loosened?

Thanks.

**Comment by tyranron** [comment]
Also interested in this. Is PR welcome?

**Comment by tyranron** [comment]
@rodya-mirov after tackling with it more, it seems to be not relative to this crate, as it has carret requirement already. It's some weirdness of how `cargo update` and `cargo outdated` work in Cargo workspaces. Sometimes it doesn't update dependencies declared in workspace members from the root, and you need to go exactly to the member's crate dir and run `cargo update` in there.

**Comment by TurnOfACard** [comment]
Cargo.toml has 0.1.43 explicitly referenced?
https://github.com/chronotope/chrono/blob/main/Cargo.toml#L39

**Comment by djc** [comment]
The chrono dependency requirements do not limit upgrades to time within the 0.1 version range.
