### ISSUE TITLE
Set year/month/day all at once

### ISSUE THREAD

**Issue by zyxw59** [chronotope/chrono#549]
With the `Datelike` trait, there are methods to return a new date with a different year/month/day. However, these do not provide the ability to easily set more than one of those at once, since the intermediate value might not be valid.

e.g.

```rust
let a = NaiveDate::from_ymd(2019, 1, 29);
let b = NaiveDate::from_ymd(2020, 2, 29);

fn with_year_month_1<D: Datelike>(date: &D, year: i32, month: u32) -> Option<D> {
  date.with_year(year)?.with_month(month)?
}

fn with_year_month_2<D: Datelike><date: &D, year: i32, month: u32) -> Option<D> {
  date.with_month(month)?.with_year(year)?
}

with_year_month_1(a, 2020, 2); // -> Some(2020-02-29)
with_year_month_2(a, 2020, 2); // -> None (2019-02-29 is invalid)
with_year_month_1(b, 2019, 1); // -> None (2019-02-29 is invalid)
with_year_month_2(b, 2019, 1); // -> Some(2020-01-29)
```

It would be useful to have a method which applied multiple of these methods at once, without checking for validity of intermediate dates.

**Comment by pitdicker** [comment]
If you want to replace two of the three parts of a date, is it not just as easy to create a new date?
Example:
```rust
use chrono::{NaiveDate, Datelike};

let a = NaiveDate::from_ymd(2019, 1, 29);
let b = NaiveDate::from_ymd(2020, 2, 29);

NaiveDate::from_ymd_opt(2020, 2, a.day()); // Some(2020-02-29)
NaiveDate::from_ymd_opt(2019, 1, b.day()); // Some(2019-01-29)
```

This is less tricky to get right.

**Comment by jtmoon79** [comment]
At first glance, I'm hesitant to add more API "surface area" for something that is fairly trivial for the user to do.

However, the OP makes a good point that there is this non-obvious "gotcha" occurring here. (My two cents)

**Comment by pitdicker** [comment]
Maybe we should add some documentation to `Datelike::with_month` or even to the `Datelike` trait itself on how to change multiple values at once.

**Comment by jtmoon79** [comment]
> Maybe we should add some documentation to `Datelike::with_month` or even to the `Datelike` trait itself on how to change multiple values at once.

My preference is the OPs suggestion but documentation is better than nothing.

**Comment by pitdicker** [comment]
Added some documentation in https://github.com/chronotope/chrono/pull/1199.
