### ISSUE TITLE
Inconsistency in `chrono::format::Parsed::to_naive_date` for instances with week numbers

### ISSUE THREAD

**Issue by weiznich** [chronotope/chrono#551]
The `chrono::format::Parsed::to_naive_date` method returns depending on the year (e.g. 2002) a `ParseError(Impossible)` even if the fields `year`, `week_from_mon` and `weekday` are correctly populated as described in the [documentation](https://docs.rs/chrono/0.4.19/chrono/format/struct.Parsed.html#method.to_naive_date) of the corresponding method. This does not happen for all years, for example setting the year to 2001 yields a valid date.

See [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e897f109e3810c242a8b2cb93a7dd58b) for a minimal example.

**Comment by pitdicker** [comment]
Fixed by https://github.com/chronotope/chrono/pull/966.
