### ISSUE TITLE
Unable to parse datetime timezone formatted with %Z

### ISSUE THREAD

**Issue by pkolaczk** [chronotope/chrono#566]
I'm getting `input is not enough for unique date and time` when trying to parse:

`2021-06-03 08:11:16.207 +00:00`

And format:

```const TIMESTAMP_FMT: &str = "%Y-%m-%d %H:%M:%S.%3f %Z";```

Interestingly, printing with %z and parsing back works fine.

Version 0.4.19.

**Comment by pitdicker** [comment]
It is a late reply, sorry.

There is a difference between the formatting specifiers `%Z` and `%z`:
- `%Z` expects to read a timezone abbreviation such as `GMT` (although it currently doesn't support reading these definitions and skips them instead).
- `%z` can read an UTC offset, such as `+00:00`.

So you should be able to parse your string with:
```rust
const TIMESTAMP_FMT: &str = "%Y-%m-%d %H:%M:%S.%3f %Z";
```
