### ISSUE TITLE
rkyv Support

### ISSUE THREAD

**Issue by JonahPlusPlus** [chronotope/chrono#583]
https://rkyv.org/

A zero-copy deserialization framework for rust. A sort of alternative to serde that has higher performance. chrono should add a feature gate where specifying "rkyv" will enable support for rkyv.

Types that should be serialized/deserialized should be given `#[derive(Archive, Serialize, Deserialize, PartialEq, Debug)]`.

**Comment by dovahcrow** [comment]
I have the implementation [here](https://github.com/dovahcrow/chrono/tree/rkyv) but not sure if the team wants the rkyv support.

**Comment by Mercesa** [comment]
We at Traverse Research would also like to use rkyv for Chrono datatypes, are there any plans to add rkyv support to Chrono?

**Comment by Jasper-Bekkers** [comment]
Agreed - we would love to see this in `chrono`, @dovahcrow is there a chance you can PR this at least?

**Comment by dovahcrow** [comment]
@Jasper-Bekkers #644
