### ISSUE TITLE
use edition 2018?

### ISSUE THREAD

**Issue by dovahcrow** [chronotope/chrono#585]
Since the edition 2021 will be released soon, is it time to at least switch to the 2018 edition?

**Comment by dovahcrow** [comment]
I did the migration and the commit is here: https://github.com/dovahcrow/chrono/commit/1cd1010e4754b536ef5f54cb7af718760c55e013. I can create a PR if the team wants to migrate.

**Comment by djc** [comment]
This was done in #653.
