### ISSUE TITLE
Documentation correction for `and_time`

### ISSUE THREAD

**Issue by ralpha** [chronotope/chrono#596]
The function [`Date::and_time(...)`](https://docs.rs/chrono/0.4.19/chrono/struct.Date.html#method.and_time) looks to have incorrect documentation.

This function states:
> Panics on invalid datetime.

But the function returns an `Option<...>` and it looks like it will return `None` if the datetime is invalid. (for example when in between daylight savings time)
It might still panic in other cases, but I don't know.

But I think this should be changed to:
> Returns `None` on invalid time.

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/1135.
