### ISSUE TITLE
Cannot find a way to convert from NaiveDateTime to Utc - Documentation seems to be obsolete

### ISSUE THREAD

**Issue by koalabi** [chronotope/chrono#599]
NOTE: I'm only starting to practice Rust while learning the basics of the language (and despite my vast experience (C, C++, Java, Scala, Go, TypeScript, LISP... over 25+ years), I must admit the learning curve is steep and the documentation structure needs some time to get used to but the language seems very powerful and I think I'm going to like it ;-)). This to say, I'mn not yet in state to troubleshoot it. On the other hand, this is my third program using chrono and it is the first one with which I cannot find a way out of my problem. The other two compile and run fine but I didn't have to use NaiveDateTime (here it is "imposed" by the spreadsheet_ods crate).

Chrono version 0.4.19

I'm trying to convert a NaiveDateTime from Utc and I have tried all possible examples in this sense from the "chrono" documentation but no one compiles. I keep getting messages : 

`refdt = Utc.from_local_datetime(dv.unwrap());`
    |                             ^^^^^^^^^^^^^^^^^^^ method not found in 'Utc'

`refdt = DateTime::<Utc>::from_local_datetime(dv.unwrap());`
    |                                          ^^^^^^^^^^^^^^^^^^^ function or associated item not found in 'chrono::DateTime<Utc>'

Is the documentation outdated? Am I doing or interpreting something wrong?

Thanks for any hint.

**Comment by Enet4** [comment]
Have you tried the examples in [`Utc`](https://docs.rs/chrono/0.4.19/chrono/offset/struct.Utc.html#example)?

**Comment by koalabi** [comment]
> Have you tried the examples in [`Utc`](https://docs.rs/chrono/0.4.19/chrono/offset/struct.Utc.html#example)?

Thanks for this prompt first reaction ;-).

Yes, that's the very first thing I tried. Now, just to be sure, I have just pasted the example in my code and it does not compile, with the same diagnostic:

`                let dt = DateTime::<Utc>::from_utc(NaiveDateTime::from_timestamp(61, 0), Utc);`
`                assert_eq!(Utc.timestamp(61, 0), dt);
`
error[E0599]: no method named `timestamp` found for struct `Utc` in the current scope
   --> src/main.rs:111:32
    |
111 |                 assert_eq!(Utc.timestamp(61, 0), dt);
    |                                ^^^^^^^^^ method not found in `Utc`
    | 
   ::: /home/alain/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:324:8
    |
324 |     fn timestamp(&self, secs: i64, nsecs: u32) -> DateTime<Self> {
    |        --------- the method is available for `Utc` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use chrono::TimeZone;
    |

This pointed me to a missing "TimeZone" in the use statement for "chrono". It fixed this problem (thanks!). The issue can therefore be closed.
