### ISSUE TITLE
Support for espidf target_os

### ISSUE THREAD

**Issue by jakobdalsgaard** [chronotope/chrono#601]
I've followed Sylvain Kerkours wonderfully simple guide to getting a working toolchain for the ESP32 SoC -- https://kerkour.com/blog/rust-on-esp32/ -- wonderful especially since I end up with a 'std' enabled system.

But the chrono crate does not compile as the the exempts for ISO C (I believe...) do not include the 'espidf' target_os.

I have a version of unix.rs with relevant 'cfg' statements altered to include the 'espidf' so I can easily make a PR -- would that make sense?

**Comment by pitdicker** [comment]
@jakobdalsgaard Is this something that still has your interest? And does the issue still exist in the current version of chrono?

**Comment by pitdicker** [comment]
Since chrono 0.4.20 uses no C code and compiles for an ESP32 when specified with:
```toml
chrono = { version = "0.4.20", default-features = false, features = ["std", "clock"] }
```
Although the `clock` feature will probably not work without an OS :smile:
