### ISSUE TITLE
Please consider bringing on more contributors with publish permissions

### ISSUE THREAD

**Issue by svenstaro** [chronotope/chrono#606]
Hey, this issue is by no means meant to be disrespectful but I couldn't help but notice that the last release was over a year ago and that there are quite a few open issues and pull request. It appears that @quodlibetor is the only one doing any commits in the last few months. I suggest bringing on a few more maintainers with publish permissions on crates.io.

chrono has become a very important crate in the Rust ecosystem and it'd be great if it received some more love. Please don't take this the wrong way. :)

**Comment by djc** [comment]
I have a lot of crates to maintain already, but in a pinch I might be able to help out as well.

**Comment by svenstaro** [comment]
How about a new release now that some fixes have been merged?

**Comment by svenstaro** [comment]
@Milo123459 Hey could you push a release so that we can get rid of the audit problem?

**Comment by Milo123459** [comment]
No. I don't have publish perms sadly.

**Comment by svenstaro** [comment]
@quodlibetor Any chance to give some more people publish permissions?

**Comment by svenstaro** [comment]
@Milo123459 @quodlibetor Hey, sorry to be blunt here but chrono is an important part of the Rust ecosystem and we need to start caring for it a little better. It's clear that there's currently no progress here and I don't see it improving by itself anytime soon. I don't mean to call out anyone here personally, after all we all have lives that sometimes get in the way. However, we need to bring in more people.

@djc has offered to step up to take this over and help out and he's certainly got a good history maintaining Rust stuff. How about we get that started?

**Comment by Milo123459** [comment]
Bringing in more people won't do anything, to be honest. I have spoken to Brandon to which he has said "don't make any breaking API changes" and that is proving to be a challenge in fixing the vulnerability. I have been very busy but work on my pr for fixing the vulnerability is continuing. 

I care for this project as much as I can; I know it's very important, but sadly bringing in more people probably won't help. It's the lack of communication from the true owners of this project that make it hard to maintain.

**Comment by svenstaro** [comment]
I suppose an API break should be alright especially if it means we can fix a vulnerability. This crate is also not marked as stable yet anyway. The current way (doing nothing) is possibly the worst compromise of all of them. @quodlibetor any chance we can move forward here in one way or another?

**Comment by Milo123459** [comment]
I've fixed most functions without breaking API in a PR I made but a test is failing that I'm honestly pulling my hair out on.

BTW: I don't have publish perms to the crates.io package.

**Comment by djc** [comment]
I should have crates.io permissions now (although I haven't exercised them yet), so I think this can be closed.
