### ISSUE TITLE
It is using time 0.1.44 version. Need to upgrade dependency time version.

### ISSUE THREAD

**Issue by topcoder1208** [chronotope/chrono#608]
I wanna use chrono. So, I added chrono = "0.4.19" to my Cargo.toml file.
But when I build my project, I am getting 9 errors.
![image](https://user-images.githubusercontent.com/61309193/138802487-dc488972-6ce8-4d74-a239-a927c41ab7a9.png)
what is solution?

**Comment by djc** [comment]
I don't think we'll be updating the version of time used in chrono. Since #478, chrono has a minimal dependency on time, and in the next semver-incompatible version we'll remove the dependency entirely.
