### ISSUE TITLE
Export `chrono::naive::time::M{AX,IN}_TIME`

### ISSUE THREAD

**Issue by sanmai-NL** [chronotope/chrono#610]
Without this, I have to write

```rust
let zerotime = NaiveTime::from_hms(0, 0, 0);
```

multiple times, since `NaiveTime::from_hms` isn't `const`.

**Comment by pitdicker** [comment]
`NaiveTime::MIN` was made public in https://github.com/chronotope/chrono/pull/890.

`NaiveTime::MAX` seems a bit questionable to me. For one because it does not account for leap seconds.

**Comment by yuyoyuppe** [comment]
Considering that we have this public:

```rust
/// The maximum possible `NaiveDateTime`.
    pub const MAX: Self = Self { date: NaiveDate::MAX, time: NaiveTime::MAX };
```

Wouldn't it make sense to make `NaiveTime::MAX` public too?
