### ISSUE TITLE
Is there a unified script for code checking?

### ISSUE THREAD

**Issue by retrhelo** [chronotope/chrono#615]
As the title says, I wonder if there's a unified script to run before making a PR? I noticed that there's one called `ci/github.sh`, but passing it will not get my program pass all the tests on github... I have to make more commits if my codes failed on github's test workflows.

**Comment by djc** [comment]
I'm happy to troubleshoot CI issues with you. If you get your change compiling on your local machine (and, ideally, formatted and clippy clean), just submit the PR and we'll run CI and see what happens. Sorry you're having trouble with this!
