### ISSUE TITLE
Is the epoch used in this prime epoch?

### ISSUE THREAD

**Issue by debuggerpk** [chronotope/chrono#618]
Thankyou for you wonderful work.

Quick question, the epoch used in this crate, is it a prime epoch .. e.g. since Jan 1, 1900 midnight?

Thanks?

**Comment by pitdicker** [comment]
The types in chrono don't really have a concept of epoch. Dates are encoded using a year and ordinal, with year 1 being 1 C.E (and year 0 being 1 B.C.E.).
