### ISSUE TITLE
How to get "now" with DateTime<Timezone>?

### ISSUE THREAD

**Issue by tobymurray** [chronotope/chrono#624]
Analogous to `Utc::now`, I'd like to get now as a `DateTime<Timezone>` for a given timezone, would this be the idiomatic way to do so?

```
Utc::now().with_timezone(timezone)
```

Similar to #169, I struggled a lot more than I think I ought to have to try and do some relatively straightforward seeming tasks. 

I'd love to:
- hear if there's a better way to do it
- add to the documentation (open to suggestions where would make a good fit, maybe right on [DateTime#now](https://docs.rs/chrono/0.4.19/chrono/offset/struct.Utc.html#method.now)?)
- commiserate with how hard it is to make an intuitive time library when it's so damn complicated! Thanks for all the work.

**Comment by epipheus** [comment]
I'd like to mention that many of us use DateTimeWithTimezone as DB storage by default but optionally still log UTC based date times which is just +0. The current `Utc::now().with_timezone(&FixedOffset::east(0))` feels non-obvious and verbose and isn't terribly well documented. as mentioned in #169. `Utc::now.as_fixed_offset()` or `Utc::now.as_date_with_timezone()`. Even is as verbose, feels readable and obvious.  My 2 cents.

**Comment by pitdicker** [comment]
> Analogous to `Utc::now`, I'd like to get now as a `DateTime<Timezone>` for a given timezone, would this be the idiomatic way to do so?
> 
> ```rust
> Utc::now().with_timezone(timezone)
> ```

Yes, this is the idiomatic way to do it.

https://github.com/chronotope/chrono/pull/1030 added `DateTime::fixed_offset` and https://github.com/chronotope/chrono/pull/1192 will add some examples to the documentation on using `Utc::now()` and `Local::now()`.
