### ISSUE TITLE
would it be possible to make ParseErrorKind public?

### ISSUE THREAD

**Issue by BrianHicks** [chronotope/chrono#643]
I'm parsing dates from CLI args. I'd like to accept both `%Y-%m-d` and `%Y-%m-%dT%H:%M:%S` formats. I can currently do that with this code:

```rust
Utc.datetime_from_str(input, "%Y-%m-%dT%H:%M:%S")
    .or_else(|_| Utc.datetime_from_str(&format!("{}T00:00:00", input), "%Y-%m-%dT%H:%M:%S"))
```

however, the error messages leave something to be desired. For instance, if I pass in `2022-01-01T25:00:00` I get a "trailing input" error instead of an "out of range" error since I'm only able to see that there *was* an error, not *what kind* of error I got. If `ParseErrorKind` were public, it looks like I could write code that produced better error messages on the command line. Would this be possible (or acceptable as a PR?)

**Comment by d-e-s-o** [comment]
The topic has been brought up in https://github.com/chronotope/chrono/issues/319 as well. This issue may be a duplicate.

**Comment by djc** [comment]
I'm going to close this in favor of discussion in #319 and the PR in #588.
