### ISSUE TITLE
Compilation error on wasm32-unknown-emscripten target

### ISSUE THREAD

**Issue by hoodmane** [chronotope/chrono#673]
When targeting `wasm32-unknown-emscripten` the following two `cfg` tags both pass causing a compile error:
```rust
#[cfg(any(target_arch = "wasm32", target_env = "sgx"))]
#[path = "sys/stub.rs"]
mod inner;

#[cfg(unix)]
#[path = "sys/unix.rs"]
mod inner;
```
If I delete the `sys/stub.rs` one, chrono builds successfully for `wasm32-unknown-emscripten`. It seems to work correctly at runtime too.

**Comment by alex** [comment]
I think this is a dupe of #519

**Comment by hoodmane** [comment]
Indeed. Closed as duplicate.
