### ISSUE TITLE
0.4.20 release planning

### ISSUE THREAD

**Issue by hoodmane** [chronotope/chrono#674]
Currently to build downstream packages for targets emscripten, I clone a fork of chrono with #593 backported onto v0.4.19 and patch the downstream package's `Cargo.toml` by adding
```patch
+[patch.crates-io]
+chrono = { path =  "path/to/forked/chrono" }
```
I am looking forward to not having to do this.

**Comment by djc** [comment]
We can do a beta release for now, see #676. In order to get to a 0.4.20 final release I want to merge #677 (or some other solution for #499) and ideally we'll then do some release candidate testing.

**Comment by cramhead** [comment]
I notice that version 0.4.19 is using version 0.1.43 of the time crate. I noticed https://rustsec.org/advisories/RUSTSEC-2020-0071 today via `cargo audit`. After looking into time a little I see that time is now on version 0.3.9, https://github.com/time-rs/time/blob/main/Cargo.toml. 
Could we add an upgrade to time to the next release?
I'd be happy to contribute, but I'm pretty new to rust.

**Comment by Stargateur** [comment]
@cramhead this CVE doesn't affect chrono

**Comment by krojew** [comment]
Any info when the new version will be released?

**Comment by cgorski-airtime** [comment]
Is there a preferred way to track and provide feedback for the beta release? I am interested in helping to get the beta into an official release.

**Comment by djc** [comment]
I've published 0.4.20-beta.1 to crates.io, would be happy to get everyone to test it!

**Comment by djc** [comment]
I've published an rc.1 and written up some release notes for it: https://github.com/chronotope/chrono/releases/tag/v0.4.20-rc.1. Please let me know if anything is missing/unclear (@esheppa would especially value your feedback on the release notes).

**Comment by esheppa** [comment]
@djc - the release notes look great! (However they made me realize that I probably need to document the behavior of the caching of the tzfile data)

Potentially we could add the following: 
* Rkyv support: https://github.com/chronotope/chrono/pull/644 and https://github.com/chronotope/chrono/pull/701/e920210e2f94ad85ff25c30ae902442d4e2872c2
* https://github.com/chronotope/chrono/pull/522

**Comment by djc** [comment]
rkyv support was already there, near the top of the additions. I missed #522 on my previous run, and also added #572, #588 and #609.

**Comment by djc** [comment]
0.4.20 has been released!

**Comment by Xuanwo** [comment]
[databend](https://github.com/datafuselabs/databend/) has switched it's chrono's stream back to [chronotope/chrono](https://github.com/chronotope/chrono/issues/674) in https://github.com/datafuselabs/databend/issues/6928.

No build failure, no tests broken, no performance regression.

I believe this version is good for everyone to upgrade.

Nice work @djc!
