### ISSUE TITLE
Update time crate to >=0.2.23

### ISSUE THREAD

**Issue by tbraun96** [chronotope/chrono#691]
Rust security advisory `RUSTSEC-2020-0071` while running `cargo deny check advisories` is flagged for this crate due to using the old `time` dependency (due to potential SEGFAULT). The recommendation is to upgrade to `time>=0.2.23`

**Comment by djc** [comment]
There have been many issues about this already. The current main branch does not actually use any of the vulnerable code in time 0.1.

**Comment by aeshirey** [comment]
Despite this issue being closed and also about the vulnerability (which, as you say, doesn't affect `chrono`), I notice that the current version of `time` used by this crate lacks features such as [certain const functions](https://github.com/time-rs/time/blob/aec5caa0ee23c6f33ed003714de3c2a6bf977300/src/duration.rs?q=fn+days#L254). It would be nice to be able to create a `chrono::Duration` in a `const` context.

**Comment by djc** [comment]
I'd be open to having more `const` functions if those would be helpful, though we are somewhat restricted by the current minimum supported Rust version. See also discussion in https://github.com/chronotope/chrono/pull/638.
