### ISSUE TITLE
Unable to deserialize null to Option<NaiveDateTime>

### ISSUE THREAD

**Issue by SorenHolstHansen** [chronotope/chrono#693]
I am having trouble deserializing a JSON field that is either a date or null. The file looks something like this
```json
[
    { time: "2022-05-15T22:00:00" },
    { time: null },
    { time: "2022-05-15T07:00:00" },
]
```
And my struct looks like
```rust
#[derive(Deserialize)]
struct SomeStruct {
    time: Option<NaiveDateTime>
}
```
This is a simplified version. The json has another field that is neven null, and that works fine when deserializing, but for this field, I get
```
Error: error decoding response body: input is out of range at line 1 column 4896
```
I have tried making it an `Option<String>` which works, but that is not really what i want.

Can someone help?

**Comment by SorenHolstHansen** [comment]
I think the problem is that there is a difference between the field not being there, and it being `null`

**Comment by djc** [comment]
Based on my understanding of serde (having written a few custom deserializers) I'm not sure how that could be the root cause.

https://github.com/serde-rs/json/blob/master/src/de.rs#L1657

**Comment by SorenHolstHansen** [comment]
I figured out the problem. It was because some of the dates were e.g. "2022-05-18T24:00:00", and chrono doesn't like parsing dates at 24:00:00
