### ISSUE TITLE
impl AddAssign<Duiration> for DateTime

### ISSUE THREAD

**Issue by vriesk** [chronotope/chrono#694]
... so one could write:

```
let mut dt = chrono::Utc::now();
dt += chrono::Duration::hours(11);
```

**Comment by djc** [comment]
I'd be open to a PR implementing this.

**Comment by esheppa** [comment]
Looks like https://github.com/chronotope/chrono/pull/698 closes this. @vriesk please let me know if this doesn't satisfy your use case

**Comment by vriesk** [comment]
LGTM
