### ISSUE TITLE
RFC: Timezone information lost in a myriad of places

### ISSUE THREAD

**Issue by 4e554c4c** [chronotope/chrono#699]
Hello! I have found myself here after a long, [winding](https://github.com/tokio-rs/tokio/discussions/4714) road trying to solve a [relatively simple problem](https://github.com/mfreeborn/heliocron/issues/43). This has led me to designing a library that does something very simple: one that takes a _real time_ (for the sake of the argument; a `DateTime<FixedOffset>`) and waits on it.

Ok! Lets try writing it
```rust
pub fn sleep_until(time: DateTime<FixedOffset>) {
    while time < Utc::now() {
        sleep();
    }
}
```
if we look at the source of `chrono`, it turns out that the `PartialOrd` implementation being used disregards all timezone information, and only compares the underlying `NaiveDateTime` data. Thus, this would be incorrect if the current date time is not UTC.

Ok, lets try again, this time converting first:
```rust
pub fn sleep_until(time: DateTime<FixedOffset>) {
    let time = time.with_timezone(&Utc);
    while time < Utc::now() {
        sleep();
    }
}
```
except `with_timezone` doesn't actually change the underlying date either, it just renames the timezone. So we have the same issue here.

---

This is a date-time library and when I'm writing programs/libraries/etc I expect date-times to represent _real, precise moments of time_
However `DateTime` in this library seems to be little more that `NaiveDateTime` with a very meaningless timezone component.

In my opinion, this library should use Rust's strict type system to restrict two `DateTime`s from **ever** being compared; or converted-between without considering the concrete (including timezone) moments that they represent.
This library already provides the `NaiveDateTime` interface, which can give the user liberty to convert between `DateTime` objects without considering their timezone, but this shouldn't be the primary operation that is hidden from the user.

Please let me know if this is the correct place to be having this discussion, and if this library is even correct for representing "real wall times" (but if not, what is?).

**Comment by djc** [comment]
I don't know why you closed this, but here's some thoughts from me as current maintainer: I can see an argument that a `PartialOrd` for `DateTime<Tz>` should take the timezone into account somehow. However, past the argument on `PartialOrd` I see little substantiation of the claims that information is lost in "a myriad of places" or that `DateTime` carries a "very meaningless timezone component". If you want to make constructive issue reports, it would be useful to open concrete issues (or better, PRs!) about each place in the code where you think what the code is doing is wrong.

**Comment by 4e554c4c** [comment]
I closed this because I had a misunderstanding about how the code is structured, in particular it seemed like the `NaiveDateTime` represented a local time and not UTC, which I only discovered after delving deeper into the code
so this isn't a real issue!

I think that documentation fixes could be in order to make this more explicit---but that's a different issue, and there are already some open for documentation changes.

**Comment by djc** [comment]
Thanks for reporting back, happy that the situation isn't as bad as you thought!
