### ISSUE TITLE
working with months and years in the chrono::Duration

### ISSUE THREAD

**Issue by bobi6666** [chronotope/chrono#751]
Hello, I would like to ask you to add the option to get duration from months and years to the chrono, because it often happens that I get information for my players about how long they have been inactive in my game and it would be good if there were years and months.

**Comment by djc** [comment]
There's probably not a single good way to do this: either you want to do something simple and efficient (at the expense of correctness) or you want to do something accurate but slow. But, this should be pretty easy to write yourself. For example, this is what we use in indicatif (which uses `std::time::Duration`, but the same principles apply):

https://github.com/console-rs/indicatif/blob/989321af966513e05d34f9a2460fdab26e9d8143/src/format.rs#L59

**Comment by bobi6666** [comment]
Hello, thank you for your help, but I would also like to ask you
something. When I get the time duration, is there a way in the
structure that I can make it so that the entered time is divided? for
example, I enter 100000000 and he divides it into years, months, and
weeks for example, and then I could call structure fields and display
it to players, for example, that this player's total time is 1 month
and 1 week

2022-08-02 16:29 GMT+02:00, Dirkjan Ochtman ***@***.***>:

**Comment by djc** [comment]
A `chrono::Duration` has methods like `num_weeks()` or `num_days()` which return an `i64`, which you could of course divide further.

**Comment by bobi6666** [comment]
yes and then that is connected with question. Why you didn't added
num_months and num_years? would it be slow? and i think if i would be
you i would use 128 for nanoseconds

2022-08-02 16:46 GMT+02:00, Dirkjan Ochtman ***@***.***>:

**Comment by djc** [comment]
Because a `Duration` stores seconds and nanoseconds, and seconds don't divide cleanly into months (30 or 31 days) or years (365 or 366 days).

**Comment by bobi6666** [comment]
yes that's true but when i want to calculate years difference with
good precision is there some steps or crate that was able to know how
much days was in this year?

2022-08-02 16:49 GMT+02:00, Dirkjan Ochtman ***@***.***>:

**Comment by esheppa** [comment]
If we end up going ahead with #824, both [`days_since`](https://github.com/chronotope/chrono/blob/d7fa4de7cc2b9c999de499737cbdf8d98962ec68/src/naive/date.rs#L1061) and [`months_since`](https://github.com/chronotope/chrono/blob/d7fa4de7cc2b9c999de499737cbdf8d98962ec68/src/naive/date.rs#L1112) should be useful for this

**Comment by bobi6666** [comment]
yes that can be end for this question

2022-10-11 13:25 GMT+02:00, Eric Sheppard ***@***.***>:

**Comment by esheppa** [comment]
You can use [`from_timestamp_opt`](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDateTime.html#method.from_timestamp_opt) to get a `NaiveDateTime` from a timestamp, and from there you can subtract them to get the duration, however that will be an exact duration rather than a calendar duration. Once you have those two `NaiveDateTime`s you could also then extract the `NaiveDate`s and calculate the years with [`years_since`](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#method.years_since). For month and days since there are currently no convenient APIs to do this but it would be relatively easy to calculate. We would be open to adding these APIs if shown to be generally useful

**Comment by bobi6666** [comment]
it would be very good if it were there because I will do it so that
from the player file I will find out his timestamp when he was active
and then subtract it from the current time stamp and then I would push
it to the other players so that he was active a minute ago or an hour
ago etc
or if you could show me an example on the playground that if I use
timestamp from now and timestamp from year back how can I count years
and months and maybe weeks

2022-12-15 3:36 GMT+01:00, Eric Sheppard ***@***.***>:

**Comment by djc** [comment]
If you want to show human/relative duration, I don't think chrono is the right tool to provide those. Try something like [humantime](https://docs.rs/humantime/latest/humantime/).
