### ISSUE TITLE
Consider bumping MSRV to 1.34.0 for `TryFrom`

### ISSUE THREAD

**Issue by lopopolo** [chronotope/chrono#757]
I _think_ the only dependency on `num-traits` in chrono is in the `format` module which uses `ToPrimitive` for fallible integer casts.

This functionality is provided by `core` as e.g. `i32::try_from(x)`.

I hope with the MSRV bump, the dependency on `num-traits` can be dropped.

**Comment by djc** [comment]
We're considering bumping to 1.48 soon (unless we get feedback that people still need something older), we can eliminate the num-traits usage then, too (would be nice!).

**Comment by esheppa** [comment]
MSRV is now 1.38 since #756 - but I'll leave this open so that I don't forget to remove `num-traits` as we can now use `TryFrom`

**Comment by djc** [comment]
Note that we cannot get rid of num-traits in 0.4.20, as it constitutes public API.

**Comment by pitdicker** [comment]
We now Have `TryFrom` and the MSRV is 1.56, so this issue seems completed.
