### ISSUE TITLE
"%+" documentation

### ISSUE THREAD

**Issue by MoSal** [chronotope/chrono#766]
> `%+`: Same as `%Y-%m-%dT%H:%M:%S%.f%:z`, i.e. 0, 3, 6 or 9 fractional digits for seconds and colons in the time zone offset.

But it's not really the same. `%+` parses `2022-08-10T04:51:47.282Z`, the supposed equivalent doesn't.

**Comment by djc** [comment]
Would you be able to contribute a suggestion for how to improve this?
