### ISSUE TITLE
no_std compatibility on target wasm32-unknown-unknown

### ISSUE THREAD

**Issue by kvinwang** [chronotope/chrono#772]
Hi, there

Since ver 0.4.20 (in [this commit](https://github.com/chronotope/chrono/commit/27c05589ac269596fe4b047552bc735ebe9ee44c)), chrono makes the `js-sys` a hard dependency which further depends on Rust's `libstd`.

This makes chrono no longer compatible with `no_std` while targeting `wasm32-unknown-unknown`.

We recently found it breaks our downstream project and we have to pin chrono to 0.4.19 in our Cargo.toml to get a workaround.

Should we revert the change? Thanks.

**Comment by h4x3rotab** [comment]
Does #771 solve the problem?

**Comment by kvinwang** [comment]
Yes, v0.4.22 solved the problem. Thanks.
