### ISSUE TITLE
Deserialization / Serialization with Serde docs

### ISSUE THREAD

**Issue by alextes** [chronotope/chrono#776]
It seems to do serializations with `serde` chrono requires you use the `serde` feature, also for `DateTime`, `NaiveDateTime`, and `NaiveDate`, is that correct?

```rs
/// documented at re-export site
#[cfg(feature = "serde")]
pub(super) mod serde;
```

Yet the docs still specify here and there that the `serde` feature is for "alternative" serialization options. Would maintainers be open to a PR trying to clarify this in the docs. I think the main line that could use updating is:

```
Serialize into a rfc3339 time string

See [the serde module](https://docs.rs/chrono/latest/chrono/serde/index.html) for alternate serialization.
```

Thanks for a great library! 😄

**Comment by djc** [comment]
If you can submit a PR to clarify the docs, that would be great!

**Comment by alextes** [comment]
I missed the [Features](https://docs.rs/chrono/latest/chrono/#features) section. That's already great, if I had noticed that it may have helped.

The `serde` module docs can be more explicit about containing _all_ functions you may need, and being behind the flag. There even appears to be a pretty label you can hint rustdoc to add, how cool! (I'm new to Rust).

The line I mentioned above I feel is fine all things considered. It's a bit confusing that the implementation is itself in the serde submodule but that isn't really visible to the reader.

In trying to resolve this, I also learned that the neat `Available on crate feature 'serde' only` labels I've been getting used to are unfortunately a nightly docs feature. Example below:
![Screenshot 2022-08-13 at 16 51 51](https://user-images.githubusercontent.com/2011351/184499389-d267b625-e254-47d9-ac19-6dc7f82f04a6.png)

I'm leaning that it would be overboard to add something like: _"available on crate feature 'serde' only"_ to the default implementations of Serialize and Deserialize on `DateTime`, `NaiveTime`, `NaiveDateTime`, `Month`, and `Weekday`. I'm leaving that out unless others feel strongly about it. The nice part would be that looking at the impl on `DateTime` for example wouldn't lead you astray. Perhaps adding it only on `DateTime` as that is also exposed immediately when enabling the feature could make sense?

Putting the rest into a PR, a tiny change all-in-all 👍 .

**Comment by alextes** [comment]
Mmm, also putting a little italic label explaining you need the serde feature to enable the module at all. Not 100% sure about that one. I'll put it into a separate commit so we can strip it from the PR if no one else likes it.
