### ISSUE TITLE
Bug: overflow with timestamp_nanos()

### ISSUE THREAD

**Issue by TCeason** [chronotope/chrono#782]
```toml
$ cat Cargo.toml 
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"

```

```rust
use chrono::{DateTime, Utc, Local, offset::{FixedOffset, TimeZone}, NaiveDateTime};

fn main() {

    let max_dt = chrono::MAX_DATETIME;
    println!("{:?}", max_dt);

    let ts1 = max_dt.naive_utc().timestamp_nanos();
    println!("{:?}", ts1);
}

```

```shell
$ cargo run
+262143-12-31T23:59:59.999999999Z
thread 'main' panicked at 'attempt to multiply with overflow', cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/naive/datetime.rs:351:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by djc** [comment]
This is documented behavior:

https://docs.rs/chrono/0.4.19/chrono/naive/struct.NaiveDateTime.html#panics

What's your use case for this?

**Comment by TCeason** [comment]
> This is documented behavior:
> 
> https://docs.rs/chrono/0.4.19/chrono/naive/struct.NaiveDateTime.html#panics
> 
> What's your use case for this?

I’m trying to use it calc timezone offset.

**Comment by djc** [comment]
Well, it doesn't seem to make sense that you'd need to go to the far end of the range to do that.

**Comment by TCeason** [comment]
> Well, it doesn't seem to make sense that you'd need to go to the far end of the range to do that.

Yes, in my test find this case. I think I will modify my test case and add some comments.😎
