### ISSUE TITLE
chrono breaks on Android

### ISSUE THREAD

**Issue by licy183** [chronotope/chrono#788]
Android doesn't have file like `/system/usr/share/zoneinfo/UTC`, so `chrono` will break on Android. Actually, in `/system/usr/share/zoneinfo`, it only contains a `tzdata` file.

Related: https://github.com/termux/termux-packages/issues/11664.

**Comment by djc** [comment]
You forgot to mention what version you're using. This should have been fixed in #756, released as part of 0.4.21.

**Comment by licy183** [comment]
Sorry for my mistake. It works fine after update to `0.4.21`. Thanks!
