### ISSUE TITLE
Version "0.4.22" fails to compile with Anchor

### ISSUE THREAD

**Issue by AnderUstarroz** [chronotope/chrono#808]
I have tried to add the latest version of chrono but seems to fail throwing multiple errors.

- Anchor version: `anchor-cli 0.25.0`
- Rust version: `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
- Chrono version: `0.4.22`
- Rustup toolchain (using mac with chip M1):
   ```
   stable-aarch64-apple-darwin (default)
   ```

Error log when executing `anchor build`:

```
error[E0432]: unresolved import `self::inner`
 --> src/sys.rs:3:15
  |
3 | pub use self::inner::*;
  |               ^^^^^ could not find `inner` in `self`

error[E0433]: failed to resolve: could not find `SteadyTime` in `sys`
   --> src/lib.rs:251:25
    |
251 |         SteadyTime(sys::SteadyTime::now())
    |                         ^^^^^^^^^^ could not find `SteadyTime` in `sys`

error[E0425]: cannot find function `get_time` in module `sys`
   --> src/lib.rs:153:28
    |
153 |     let (sec, nsec) = sys::get_time();
    |                            ^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `get_precise_ns` in module `sys`
   --> src/lib.rs:164:10
    |
164 |     sys::get_precise_ns()
    |          ^^^^^^^^^^^^^^ not found in `sys`

error[E0412]: cannot find type `SteadyTime` in module `sys`
   --> src/lib.rs:246:28
    |
246 | pub struct SteadyTime(sys::SteadyTime);
    |                            ^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `time_to_utc_tm` in module `sys`
   --> src/lib.rs:408:10
    |
408 |     sys::time_to_utc_tm(sec, &mut tm);
    |          ^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `time_to_local_tm` in module `sys`
   --> src/lib.rs:422:10
    |
422 |     sys::time_to_local_tm(sec, &mut tm);
    |          ^^^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `utc_tm_to_time` in module `sys`
   --> src/lib.rs:436:23
    |
436 |             0 => sys::utc_tm_to_time(self),
    |                       ^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `local_tm_to_time` in module `sys`
   --> src/lib.rs:437:23
    |
437 |             _ => sys::local_tm_to_time(self)
    |                       ^^^^^^^^^^^^^^^^ not found in `sys`

```

**Comment by djc** [comment]
What Cargo features have you specified?

**Comment by AnderUstarroz** [comment]
Hi @djc ,

This is my `Cargo.toml`:
```
[package]
name = "sol_games"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sol_games"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.25.0"
solana-program = "1.10.35"
time = "0.3.14"

[dev-dependencies]
solana-program-test = "=1.10.35"

```

**Comment by AnderUstarroz** [comment]
Hi @djc ,

This is my `Cargo.toml`:

```
[package]
name = "my_app"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "my_app"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.25.0"
solana-program = "1.10.35"
time = "0.3.14"

[dev-dependencies]
solana-program-test = "=1.10.35"
```

**Comment by djc** [comment]
That doesn't have Chrono at all... So why do you think these errors are due to Chrono?

**Comment by AnderUstarroz** [comment]
sorry, my bad. I copied my current setup. The failing one  is using `chrono = "0.4.22"` instead of `time`.

**Comment by djc** [comment]
The error messages still don't make sense. Please give us a standalone reproduction scenario so we can see what's going on.

**Comment by AnderUstarroz** [comment]
The faster way I could think of would be downloading this [sample project](https://github.com/coral-xyz/anchor-book/tree/master/programs/tic-tac-toe) and just adding the following dependency within **Cargo.toml**:

```
chrono = "0.4.22"
```

Your environment must have the [corresponding Rust and Anchor versions ](https://book.anchor-lang.com/getting_started/installation.html)installed.

**Comment by djc** [comment]
I'm sorry, but I am unlikely to install all of those dependencies on my system just to reproduce this bug which has so far not provided any clear indication the problem is with Chrono.

**Comment by AnderUstarroz** [comment]
Sure, I don't know `time="0.3.14"` package works just fine like the rest of dependencies so I thought it would have something to do with this specific library, but feel free to close the issue If you think the problem is somewhere else.

**Comment by djc** [comment]
I'm open to the idea that the problem is with Chrono but I don't have time to spend a bunch of time on verifying that the problem is with Chrono instead of some other part of your setup.

**Comment by AnderUstarroz** [comment]
Noted,  but downloading [Anchor's official sample project]([sample project](https://github.com/coral-xyz/anchor-book/tree/master/programs/tic-tac-toe))  plus just adding Chrono's dependency `chrono = "0.4.22"` into his **Cargo.toml** hardly sounds like a problem in my setup thought. 

Anyway just trying to help here, leaving this for the record in case more people are experiencing similar issues.

**Comment by djc** [comment]
From looking at the sample project, it seems like it's using some strange target that Chrono lacks support for. However, I'm suspicious of your bug report because there's also an error about `SteadyTime`, which just doesn't exist in our code base.

**Comment by AnderUstarroz** [comment]
> From looking at the sample project, it seems like it's using some strange target that Chrono lacks support for. However, I'm suspicious of your bug report because there's also an error about `SteadyTime`, which just doesn't exist in our code base.

I think you are right after all, it could be clashing with [the Chrono version already shipped by Anchor](https://github.com/coral-xyz/anchor/blob/c1c4f6c335dfc9cea374254f75d3352ed00d3fee/cli/Cargo.toml#L46).

**Comment by Eorg79** [comment]
I have the exact same problem as @AnderUstarroz using chrono in an Anchor project, with the same errors. I have tried every versions of chrono.
```Compiling time v0.1.44
error[E0432]: unresolved import `self::inner`
 --> src/sys.rs:3:15
  |
3 | pub use self::inner::*;
  |               ^^^^^ could not find `inner` in `self`

error[E0433]: failed to resolve: could not find `SteadyTime` in `sys`
   --> src/lib.rs:251:25
    |
251 |         SteadyTime(sys::SteadyTime::now())
    |                         ^^^^^^^^^^ could not find `SteadyTime` in `sys`

error[E0425]: cannot find function `get_time` in module `sys`
   --> src/lib.rs:153:28
    |
153 |     let (sec, nsec) = sys::get_time();
    |                            ^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `get_precise_ns` in module `sys`
   --> src/lib.rs:164:10
    |
164 |     sys::get_precise_ns()
    |          ^^^^^^^^^^^^^^ not found in `sys`

error[E0412]: cannot find type `SteadyTime` in module `sys`
   --> src/lib.rs:246:28
    |
246 | pub struct SteadyTime(sys::SteadyTime);
    |                            ^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `time_to_utc_tm` in module `sys`
   --> src/lib.rs:408:10
    |
408 |     sys::time_to_utc_tm(sec, &mut tm);
    |          ^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `time_to_local_tm` in module `sys`
   --> src/lib.rs:422:10
    |
422 |     sys::time_to_local_tm(sec, &mut tm);
    |          ^^^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `utc_tm_to_time` in module `sys`
   --> src/lib.rs:436:23
    |
436 |             0 => sys::utc_tm_to_time(self),
    |                       ^^^^^^^^^^^^^^ not found in `sys`

error[E0425]: cannot find function `local_tm_to_time` in module `sys`
   --> src/lib.rs:437:23
    |
437 |             _ => sys::local_tm_to_time(self)
    |                       ^^^^^^^^^^^^^^^^ not found in `sys`
```

**Comment by djc** [comment]
Again: current chrono contains neither a `sys` module nor a `SteadyTime` type. I'm happy to reopen this issue if someone can put together a minimal reproduction example that doesn't involve anchor.

**Comment by Eorg79** [comment]
Errors occurs when I add chrono in my cargo.toml as describe below, without it build correctly :
```[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
solana-program = "1.10.19"
chrono = "0.4.22"```
Indeed it is strange that it conflicts with sys module. I will investigate further. thanks @djc

**Comment by Eorg79** [comment]
solved : the error messages was related to the sys module of the time crate, which is an optional (-deprecated) dependency of chrono .  You just need to to add it: 
```chrono = {version = "0.4.22", optional = true }```

**Comment by AnderUstarroz** [comment]
This is definitely not a chrono issue, Anchor seems to have some compatibility problems, if you need to use time @Eorg79 try using [Solana's Clock](https://solanacookbook.com/references/programs.html#how-to-get-clock-in-a-program)
