### ISSUE TITLE
parsing timezone should support Unicode "MINUS SIGN" (U+2212)

### ISSUE THREAD

**Issue by jtmoon79** [chronotope/chrono#835]
According to [Wikipedia](https://en.wikipedia.org/w/index.php?title=ISO_8601&oldid=1114309368#Time_offsets_from_UTC)

> To represent a negative offset, ISO 8601 specifies using a [minus sign](https://en.wikipedia.org/wiki/Minus_sign), (`−`). If the interchange character set is limited and does not have a minus sign character, then the [hyphen-minus](https://en.wikipedia.org/wiki/Hyphen-minus) should be used, (`-`). [ASCII](https://en.wikipedia.org/wiki/ASCII) does not have a minus sign, so its hyphen-minus character (code is 45 decimal or 2D hexadecimal) would be used. If the character set has a minus sign, then that character should be used. [Unicode](https://en.wikipedia.org/wiki/Unicode) has a minus sign, and its character code is U+2212 (2212 hexadecimal); the [HTML character entity](https://en.wikipedia.org/wiki/HTML_entity) invocation is `&minus;`.

## Problem

chrono `parse_from_str` fails to parse a Unicode "minus sign" character `−` (`U+2212`).

[rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=650c8bd417e148bbda1699d24105766b)
```lang-rust
extern crate chrono;
use chrono::DateTime;

fn main() {
    let dt_pattern = r"%Y %b %d %H%M%S %:z";

    // use ASCII "hyphen-minus"
    let data = r"2019 Aug 30 125959 -07:00";
    let dt = DateTime::parse_from_str(data, dt_pattern);
    dbg!(&dt);

    // use Unicode "minus" character
    let data = r"2019 Aug 30 125959 −07:00";
    let dt = DateTime::parse_from_str(data, dt_pattern);
    dbg!(&dt);
}
```

results in output
```text
[src/main.rs:10] &dt = Ok(
    2019-08-30T12:59:59-07:00,
)
[src/main.rs:15] &dt = Err(
    ParseError(
        Invalid,
    ),
)
```

(using chrono version *0.4.22*).

In some circumstances, chrono users must manually transform a found "minus sign" character `−` to "hyphen-minus" character `-`.

## Solution

To more fully support the ISO 8601 standard, chrono should parse Unicode "minus sign" character `−` (`U+2212`) in numeric timezone offsets, e.g. `−07:00`.

**Comment by djc** [comment]
I'm open to adding support for this, want to submit a PR?

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/1087.
