### ISSUE TITLE
Add operators (add_days, add_months..)

### ISSUE THREAD

**Issue by DimitriTimoz** [chronotope/chrono#838]
Hi,  
It would be nice if `chrono` offered the possibility to add `n` days, months or years to the NaiveDate struct.
Currently, we have some tricks to apply these operations but it isn't the best thing.

Thank you

**Comment by esheppa** [comment]
Thanks for the question @DimitriTimoz - you are in luck as this has recently been added to `chrono`. You can use the [`Months`](https://docs.rs/chrono/latest/chrono/struct.Months.html) data type to add a number of calendar months to a `NaiveDate`, where adding `n` months will always increment the months by `n` (modulo 12), truncating to the last day of the month where necessary. Please note that this means that `my_date + Months::new(1) + Months::new(1)` can and often is different to, `my_date + Months::new(2)` (the `Months` type is not associative)

With regards to `n` days, this has been [added](https://github.com/chronotope/chrono/commit/181b08364774711994cb6e84befc991d4bb32c88) and will come out when version `0.4.23` is released, however you can depend on the `0.4.x` branch if you want to play around with it in the meantime. This works similarly, but uses the `Days` type. 

If you want to deal with weeks, the recommendation is to use `Days::new(7)`, and similarly for quarters - `Months::new(3)` and years - `Months::new(12)`

**Comment by pitdicker** [comment]
I would say this issue in completed.
