### ISSUE TITLE
Use SPDX Expression for License

### ISSUE THREAD

**Issue by keymandll** [chronotope/chrono#856]
To help software composition analysis it would be better to use a valid SPDX expression for the `license` in `Cargo.toml`. Instead of `license = "MIT/Apache-2.0"`, it should be `license = "MIT OR Apache-2.0"`.

**Comment by djc** [comment]
Sounds good. Would you be able to submit a PR (to the 0.4.x branch, please)?

**Comment by keymandll** [comment]
I'd love to and already tried. Unfortunately, for some reason, I was not able to. I could not figure out why. Any pointers?

**Comment by djc** [comment]
What do you mean, you were not able to?

**Comment by keymandll** [comment]
Never mind. Here it is: https://github.com/chronotope/chrono/pull/857

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/1132.
