### ISSUE TITLE
Support for ? operator (Try trait)

### ISSUE THREAD

**Issue by wcarmon** [chronotope/chrono#861]
Can we have support for the [`?`](https://doc.rust-lang.org/rust-by-example/std/result/question_mark.html) operator on [`LocalResult`](https://github.com/chronotope/chrono/blob/main/src/offset/mod.rs#L180)

I believe this means `impl Try for LocalResult`

https://doc.rust-lang.org/std/ops/trait.Try.html

**Comment by djc** [comment]
That's not stable yet, which means it would entail adding at least a Cargo feature to optionally enable this... I think it's pretty messy and there's not enough value in doing so until the trait stabilizes.

**Comment by wcarmon** [comment]
Reasonable.

**Comment by esheppa** [comment]
@wcarmon - you also probably don't want to use `?` with `LocalResult` as you will generally want to handle all the possibilities or transform it to some other type. In future we will likely change the API to have some convenience methods to get a best effort local timestamp, see: https://github.com/chronotope/chrono/issues/716
