### ISSUE TITLE
request to simplify parsing unix millis

### ISSUE THREAD

**Issue by wcarmon** [chronotope/chrono#862]
I believe the code to parse unix millis looks something like this
```rust
let nanos = ((ux_millis % 1000) * 1_000_000) as u32;
let ndt = NaiveDateTime::from_timestamp(ux_millis / 1000, nanos);
let ts = DateTime::<Utc>::from_utc(ndt, Utc);
```

can we have something like this instead?
```rust
let ndt = NaiveDateTime::from_timestamp_millis(ux_millis);
let ts = DateTime::<Utc>::from_utc(ndt, Utc);
```

**Comment by djc** [comment]
Yes, would you like to submit a PR?

**Comment by esheppa** [comment]
We already have this via #818 and #823. @wcarmon you can depend on main or 0.4.x to get this now, otherwise you'll have to wait for `0.4.23` release

**Comment by djc** [comment]
For 0.4.23 release planning, see #850.

**Comment by wcarmon** [comment]
Thanks!  I appreciate you both @esheppa & @djc
