### ISSUE TITLE
rustc-serialize is insecure

### ISSUE THREAD

**Issue by Barugon** [chronotope/chrono#865]
[deps.rs](https://deps.rs/crate/chrono/0.4.22) is claiming that rustc-serialize is insecure.

Also, [rustc-serialize](https://github.com/rust-lang-deprecated/rustc-serialize) is no longer being developed.

**Comment by djc** [comment]
You can see that rustc-serialize has been removed from the main branch already. Unfortunately for compatibility reasons we can't really remove it in the 0.4.x release series.

**Comment by Barugon** [comment]
Thanks for the reply @djc.

**Comment by aplanas** [comment]
Would make sense to drop 0.4.24 and move to 0.5.0 instead? I see this in nighty:

```
warning: the following packages contain code that will be rejected by a future version of Rust: rustc-serialize v0.3.24
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

```
The package `rustc-serialize v0.3.24` currently triggers the following future incompatibility lints:
> warning: impl method assumes more implied bounds than the corresponding trait method
>     --> /home/aplanas/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.24/src/serialize.rs:1155:41
>      |
> 1155 |     fn decode<D: Decoder>(d: &mut D) -> Result<Cow<'static, T>, D::Error> {
>      |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace this type to make the impl signature compatible: `Result<Cow<'a, T>, <D as serialize::Decoder>::Error>`
>      |
>      = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>      = note: for more information, see issue #105572 <https://github.com/rust-lang/rust/issues/105572>
>      = note: `#[allow(implied_bounds_entailment)]` on by default

```

**Comment by Barugon** [comment]
A new release would be nice.

**Comment by dtolnay** [comment]
The rustc-serialize dependency is an optional dependency. @aplanas you need to fix whatever other crate is turning on the rustc-serialize feature of chrono. Chrono releasing 0.5 will _not_ stop that other crate from pulling in 0.4 with rustc-serialize enabled. Meanwhile if the other crate drops its dependency on the rustc-serialize feature, then no code change or new release in chrono is needed. So your attention is misdirected by looking at this crate.

**Comment by djc** [comment]
We can't remove the dependency from the 0.4.x API because that would be a breaking change. We don't want to release 0.5 yet because there are more API-incompatible changes we want to make, and I don't think widely used crates like chrono should release API-incompatible versions very often.

**Comment by aplanas** [comment]
> So your attention is misdirected by looking at this crate.

Yes, you are right. I think that I understand a bit better the issue.

**Comment by Barugon** [comment]
> We can't remove the dependency from the 0.4.x API because that would be a breaking change. We don't want to release 0.5 yet because there are more API-incompatible changes we want to make, and I don't think widely used crates like chrono should release API-incompatible versions very often.

I'm using  [![Dependency status](https://deps.rs/repo/github/Barugon/cota/status.svg)](https://deps.rs/repo/github/Barugon/cota)  in my readme file in order to see when a dependency is out of date. It was telling me that chrono was insecure (because rust-deserialize is considered insecure). I switched to using the main branch of chrono instead of the current release and that satisfies deps.rs for now.

**Comment by ChrisDenton** [comment]
Hm, actually can the 0.4.x branch be updated? To quote @bjorn3

> If cargo fails to find a feature in one crate version it will look for other crate versions for one which does have the feature. So if anyone depends on the rustc-serialize feature, cargo will simply force usage of an older [version] which still supports rustc-serialize.

**Comment by djc** [comment]
@pitdicker do you want to experiment with that a bit?
