### ISSUE TITLE
Feedback: `with_ymd_and_hms` ergonomics

### ISSUE THREAD

**Issue by leontoeides** [chronotope/chrono#869]
Culprit code:
```rust
my_utc_date_time = Utc.ymd(2020, 1, 1).and_time(my_naive_time);
```

Results in compiler warning `warning: use of deprecated associated function 'chrono::TimeZone::ymd': use 'with_ymd_and_hms()' instead`

Right now it looks like changing my code to use `with_ymd_and_hms` requires me destructuring `my_naive_time` into separate hour-minutes-seconds components and sending them to `with_ymd_and_hms`. Seems really messy. What about  a `with_ymd_and_time` function? Something like...

```rust
my_utc_date_time = Utc.with_ymd_and_time(2020, 1, 1, my_naive_time);
```

**Comment by esheppa** [comment]
Would using [`NaiveDate::and_time`](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#method.and_time) also work here?

```rust
NaiveDate::ymd_opt(2020, 1, 1).unwrap().and_time(my_naive_time).and_timezone(Utc).unwrap()
```

Separately, I am interested to understand common use cases for constructing dates from parts like this, this would then allow some exploration of potentially more ergonomic APIs., for example (as a very rough idea):
```rust
Year::new(2020).start_date()
```

**Comment by leontoeides** [comment]
Ahh that works! Nice builder pattern. 

```rust
my_utc_date_time = NaiveDate::from_ymd_opt(2020, 1, 1).unwrap().and_time(my_naive_time).and_local_timezone(Utc).unwrap();
```

I had to review this old code in question to see what it was doing. Apparently the time zone was unnecessary. Maybe it hitched a ride on a copy-and-paste. Yes it seems strange to choose an arbitrary date like that. There could be a better way to do this - the function is tracking an event that might pass midnight. So it adds a duration to `my_naive_date_time`. If the event begins at 11:45 PM, the duration is 30 minutes, the resulting time should be 12:15 AM. For now, the date can't be known and is unimportant, just looking at time estimations. (I understand that this is potentially a can-of-worms.)

**Comment by esheppa** [comment]
If you are happy to paste some of the code here we can suggest alternative ways to solve it, which can assist future readers of these issues
