### ISSUE TITLE
Easy way to convert timestamp to UTC object?

### ISSUE THREAD

**Issue by rory** [chronotope/chrono#88]
As near as I can tell, the only way to convert a timestamp (i.e. number of seconds since UNIX epoch¹) is with [`NaiveDateTime::from_timestamp()`](https://lifthrasiir.github.io/rust-chrono/chrono/naive/datetime/struct.NaiveDateTime.html#method.from_timestamp), however that returns a DateTime without a timezone... but if we know the unix epoch time, then we know exactly what second it is? a timestamp of 60 is 00:01 UTC on 1st Jan 1970, it's not like it can be in a some other timezone.

How about some method that'll take a unix epoch and return a DateTime in UTC timezone?

---

¹ I'm aware of leap seconds

**Comment by lifthrasiir** [comment]
@rory Wouldn't `UTC.timestamp(secs, nanos)` be enough for your use case?

**Comment by rory** [comment]
On 06/08/16 17:27, Kang Seonghoon wrote:
> @rory <https://github.com/rory> Wouldn't |UTC.timestamp(secs, nanos)| be
> enough for your use case?

D'oh! It looks like it might. I obviously didn't find that in the docs.
I was looking for `from_timestamp`, so that didn't come up. I'll try
that out. Thanks! 👍

**Comment by lifthrasiir** [comment]
@rory Great! Please close the issue if it worked :)

> I was looking for `from_timestamp`, so that didn't come up.

Huh, that may be confusing indeed. I'll think more about that.

**Comment by lolgesten** [comment]
Cross references in the docs between `DateTime::timestamp` and `Utc::timestamp` would be gold.

**Comment by lolgesten** [comment]
uhm. strike that. can we actually go from Utc::<something> to a DateTime?

**Comment by quodlibetor** [comment]
All the methods on [`TimeZone`](https://docs.rs/chrono/0.4.0/chrono/offset/trait.TimeZone.html) are implemented on `Utc`, anything that has a type signature that ends with `-> DateTime` will convert a `Utc` to a `DateTime`. Sometimes you need to go by way of dates. So: `Utc.ymd(2018, 1, 2).and_hms(1, 1, 1)` will result in a `DateTime`.

**Comment by lolgesten** [comment]
Yes, I found it eventually. Thanks! In rust/chrono to convert millis UNIX epoch is:

```
    let millis = reader.get_time_stamp();
    let seconds = (millis / 1000) as i64;
    let nanos = ((millis % 1000) * 1_000_000) as u32;
    let time_stamp = DateTime::<Utc>::from_utc(NaiveDateTime::from_timestamp(seconds, nanos), Utc);
```

**Comment by quodlibetor** [comment]
[`TimeZone::timestamp`](https://docs.rs/chrono/0.4.0/chrono/offset/trait.TimeZone.html#method.timestamp) will also work, and be less verbose:

```
let timestamp = Utc.timestamp(seconds, nanos);
```
