### ISSUE TITLE
Provide format_localized for chrono::naive::NaiveDate

### ISSUE THREAD

**Issue by mseele** [chronotope/chrono#880]
Since [chrono](https://docs.rs/chrono/latest/chrono/index.html)::[Date](https://docs.rs/chrono/latest/chrono/struct.Date.html#) is deprecated in favor of [chrono](https://docs.rs/chrono/latest/chrono/index.html)::[naive](https://docs.rs/chrono/latest/chrono/naive/index.html)::[NaiveDate](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#), the function `format_localized` (via feature `unstable-locales`) should be provided for [chrono](https://docs.rs/chrono/latest/chrono/index.html)::[naive](https://docs.rs/chrono/latest/chrono/naive/index.html)::[NaiveDate](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#) as well.

Without a localized format we cannot switch from [chrono](https://docs.rs/chrono/latest/chrono/index.html)::[Date](https://docs.rs/chrono/latest/chrono/struct.Date.html#) to [chrono](https://docs.rs/chrono/latest/chrono/index.html)::[naive](https://docs.rs/chrono/latest/chrono/naive/index.html)::[NaiveDate](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#).

**Comment by djc** [comment]
Fair point! Would you be able to submit a PR for this?

**Comment by mseele** [comment]
> Fair point! Would you be able to submit a PR for this?

I had no time to look into it yesterday evening, I'll lock into it over the weekend and report back asap.

**Comment by djc** [comment]
Awesome, thanks! Seems like it should be straightforward...

**Comment by mseele** [comment]
PR has been created (including some tests)

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/881.
