### ISSUE TITLE
Add a feature to extend the supported range of dates

### ISSUE THREAD

**Issue by jedel1043** [chronotope/chrono#886]
At `boa` (A Javascript interpreter) we're using `chrono` to handle the Javascript `Date` builtin; we mainly use it to easily create, parse and format local and UTC datetimes. However, we discovered that several tests were failing because of the supported range of dates by chrono. The README specifies:

> Date types are limited in about +/- 262,000 years from the common epoch.

While the [ECMAScript spec](https://tc39.es/ecma262/#sec-time-values-and-time-range) mentions:

> The smaller range supported by a time value as specified in this section is approximately -273,790 to 273,790 years relative to 1970.

`chrono`'s supported range is smaller than the range specified by the spec.

The `time` crate has a feature (`large-dates`) to extend the allowed range of dates, so we would be very glad to see a similar feature in `chrono` that extended its supported range.

Thanks!

**Comment by esheppa** [comment]
this could be supported by the work in #882, just by swapping out the i16 year for i32. This might be better as a seperate type rather than a feature flag such that both types could be used in a single project

**Comment by pitdicker** [comment]
We have no spare bits left in the internal representation of our `NaiveDate` type (the time crate did have some). Our current representation includes 4 bits to cache whether the year is a leap year and what is the first weekday of the year. Those are used in *many* of the operations chrono supports on `NaiveDate`s, including conversion to timestamps and formatting.

So this feature either needs a substantial change to chrono's internals and performance characteristics, or it needs the backing type to switch from `i32` to `i64`.

I don't think a `large-dates` feature is going to be a good fit for chrono. As the time crate already supports this use case, maybe it is best to that library instead.
