### ISSUE TITLE
You should have bumped to 0.5 when you made the change that caused Alex-PK/chrono-locale#5

### ISSUE THREAD

**Issue by ctrlcctrlv** [chronotope/chrono#899]
FYI. Patched by Alex-PK/chrono-locale#6 but @alex-pk hasn't merged anything since 2018 so maybe you want to review this.

**Comment by djc** [comment]
Hmm, that's a tricky one. There's an `Internatl` variant that tries to make it clear that this is intended to be non-exhaustive, but clearly it's not entirely effective. Given that this hasn't been much of an issue, I don't think we're going to go back and fix the semver issue here now. We should start by making some types explicitly non-exhaustive now that we've bumped the MSRV on main.

Are you aware with the built-in localization support that chrono offers?

**Comment by ctrlcctrlv** [comment]
Well, it broke one of my font editor's core libraries, `ipc.rlib`. From its name, you can assume that that library is included in every binary in the MFEK org pretty much.

Regarding `unstable-locales`, no, was not aware of it, and `ipc.rlib` far predates it. But I can look into changing to it when it's stabilized, my patch Alex-PK/chrono_locale#6 fixes the problem for me and the MFEK org can just maintain that library for as long as it takes to stabilize.
