### ISSUE TITLE
`NaiveDateTime::from_timestamp_millis(-1000)` does not compare equal to `NaiveDateTime::from_timestamp_opt(-1, 0)`

### ISSUE THREAD

**Issue by umanwizard** [chronotope/chrono#903]
Title says it all. This seems to be because the former gets interpreted as -2 seconds and 1 billion nanoseconds, whereas the latter gets interpreted as -1 seconds and 0 nanoseconds.

These feel to me like they should be equal, but I might be missing some subtlety.

**Comment by esheppa** [comment]
This has been fixed by: https://github.com/chronotope/chrono/pull/885 but is yet to be released. If possible do you mind testing against the HEAD of the `0.4.x` branch?
