### ISSUE TITLE
Feature request: `NaiveDateTime::from_timestamp_micros`

### ISSUE THREAD

**Issue by umanwizard** [chronotope/chrono#904]
There is already `NaiveDateTime::from_timestamp_millis`, which uses some non-trivial logic to convert properly to seconds and nanoseconds when dealing with pre-1970 timestamps.

When instantiating one from a timestamp in _microseconds_ (which we have seen in the wild from some of our customers), it's necessary to duplicate that logic; see e.g. https://github.com/MaterializeInc/materialize/pull/16609 .

It would be really nice if Chrono had a `from_timestamp_micros` feature for this case.

**Comment by esheppa** [comment]
Thanks for this @umanwizard - would you be willing to do a PR to implement this?

**Comment by umanwizard** [comment]
Yes, I can submit something today or tomorrow.

Btw, do you have an estimate on when the next release will be?

**Comment by umanwizard** [comment]
Also, should I send the PR against 0.4.x or against devel?

**Comment by djc** [comment]
If it's a compatible API addition, just submit it as a PR against 0.4.x and we'll merge it into main later.

**Comment by umanwizard** [comment]
PR has been submitted.

**Comment by umanwizard** [comment]
This is implemented in #906.
