### ISSUE TITLE
add serialization/deserialization for Date<UTC>

### ISSUE THREAD

**Issue by mathstuf** [chronotope/chrono#92]
It'd be nice to be able to just use `Date<UTC>` with serde where only a date is given (no time).

**Comment by lifthrasiir** [comment]
@mathstuf Is there any particular reason that you cannot use `NaiveDate` instead? `Date` is already a bit ambiguous type, being unable to pin the exact offset down. A specialized implementation for `Date<UTC>` will work but I think it is very a niche requirement.

**Comment by mathstuf** [comment]
Oh, I didn't realize that was an option. The docs could probably be improved to indicate that `NaiveDate` is best for serialization in cases like this.
