### ISSUE TITLE
Local timezones broken on Android

### ISSUE THREAD

**Issue by dae** [chronotope/chrono#922]
Unfortunately it seems like #756 did not fix timezone determination on Android - UTC is being returned instead.

Part of the problem might be the leading space in the filename:

https://github.com/chronotope/chrono/pull/756/files#diff-568a8cdf0e0b7a4922b13d27771df35ac8e561ac9f25c5229263120edc171486R100

A bigger problem though is that individual files don't appear to be available - `/system/usr/share/zoneinfo` appears to have all data packed into a binary tzdata file, so Chrono will presumably need to be able to parse it. Some Googling reveals the format: https://android.googlesource.com/platform/libcore/+/jb-mr2-release/luni/src/main/java/libcore/util/ZoneInfoDB.java#38, https://go.dev/src/time/zoneinfo_android.go

**Comment by talhazengin** [comment]
The problem still continues. Is there a plan to make a fix for this?

**Comment by djc** [comment]
There is not, but we'd love if someone wants to contribute code to make it work.

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/978.
