### ISSUE TITLE
0.4.24 release planning

### ISSUE THREAD

**Issue by djc** [chronotope/chrono#929]
I think we have a few important fixes in the 0.4.x branch, we should probably get them out soon.

@esheppa is there anything else that we should get in? I think #921 would be nice.

**Comment by djc** [comment]
- #874 
- #879 
- #881 
- #878 
- #890 
- #885 
- #897 
- #905 
- #906 
- #909 
- #912

**Comment by esheppa** [comment]
I think just #921 is good - will get it reviewed shortly. Most of the other remaining PRs are against `main`, and there have been some fresh comments on https://github.com/chronotope/chrono/pull/883 which could be worth implementing more so no reason to delay `0.4.24` for that

**Comment by yanns** [comment]
any update on a release?

**Comment by djc** [comment]
#921 is being continued in #966. We should also get #942, #938, #926 in, but would be good to get a review from @esheppa.

**Comment by djc** [comment]
It's done: https://github.com/chronotope/chrono/releases/tag/v0.4.24.
