### ISSUE TITLE
Deprecated `from_timestamp` method used in example for `DateTime`

### ISSUE THREAD

**Issue by greg-el** [chronotope/chrono#931]
The example given in https://docs.rs/chrono/latest/chrono/struct.DateTime.html#example appears to use the deprecated `from_timestamp`:

```
warning: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp`: use `from_timestamp_opt()` instead
  --> src/main.rs:60:60
   |
60 |             date: DateTime::<Utc>::from_utc(NaiveDateTime::from_timestamp(61, 0), Utc),
   |                                                            ^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
```

I figure this should be as simple as replacing `NaiveDateTime::from_timestamp(61, 0)` with `NaiveDateTime::from_timestamp_opt(61, 0).unwrap()`, happy to open a PR to do so!

**Comment by djc** [comment]
Would be great to have a PR for this! Be sure to target the 0.4.x branch, thanks!

**Comment by pitdicker** [comment]
This issue is fixed by https://github.com/chronotope/chrono/pull/939.
