### ISSUE TITLE
Weird min/max constants

### ISSUE THREAD

**Issue by petar-dambovaliev** [chronotope/chrono#932]
Hey there, i needed min and max constants for UTC timezone and i was a little confused by the API.

```
error[E0283]: type annotations needed
   --> workspace/backend/src/lib.rs:397:27
    |
397 |             let mut min = DateTime::MAX_UTC;
    |                           ^^^^^^^^^^^^^^^^^ cannot infer type of the type parameter `Tz` declared on the struct `DateTime`
    |
    = note: cannot satisfy `_: chrono::TimeZone`
note: required by a bound in `chrono::DateTime::<Tz>::MAX_UTC`
```

Why do i need to write
```
let mut min = DateTime::<Utc>::MAX_UTC;
```
When you read this code, it suggests that there might be a non UTC constant `MAX_UTC`.

It looks like these constants should not be associated or they should be specialized with the same name.

```
DateTime::<Utc>::MAX
```

**Comment by djc** [comment]
The consts are independent of the timezones you pass. Unfortunately I don't think it's possible to elide the type argument when referencing the associated const, even though the const value does not depend on it. Given those constraints, I think this is the best we can do?

**Comment by petar-dambovaliev** [comment]
> If you think there is a better solution, feel free to submit a PR.

Okay, cool. I will.

**Comment by pitdicker** [comment]
Fixed on main with https://github.com/chronotope/chrono/pull/1303.
