### ISSUE TITLE
MIN_UTC's timestamp_millis is too large to be converted back into datetime.

### ISSUE THREAD

**Issue by init-js** [chronotope/chrono#934]
This is arguably an edge case, but it seems that the number of milliseconds produced by `DateTime::<Utc>::MIN_UTC.timestamp_millis();` cannot be converted back into a NaiveDateTime.

I.e. the following panics:

`NaiveDateTime::from_timestamp_millis(DateTime::<Utc>::MIN_UTC.timestamp_millis()).unwrap();`

The minimum datetime is `-262144-01-01T00:00:00.000Z` and lands precisely on a second boundary. Negative millisecond timestamps that fall exactly on the second boundary (i.e. 0 nsecs) end up being represented using a smaller second count (-1), but with nsecs==1_000_000_000. e.g. -3000ms would result in `from_timestamp_opt(seconds=-4, nsecs=1_000_000_000)`.

Is that only done in the interest of simplifying control flow for both positives and negatives?

**Comment by djc** [comment]
This sounds like just an oversight/bug in `from_timestamp_unit()`. Want to submit a PR to improve it?

**Comment by init-js** [comment]
sure!

**Comment by pitdicker** [comment]
This was fixed in https://github.com/chronotope/chrono/pull/885.
