### ISSUE TITLE
Years greater than `9999` require a `+` at the beginning in `NaiveDateTime::parse_from_str`

### ISSUE THREAD

**Issue by ethowitz** [chronotope/chrono#947]
**Description**
When calling [`NaiveDateTime::parse_from_str`](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDateTime.html#method.parse_from_str), years greater than 9999 require a `+` sign at the beginning. I didn't see this in the documentation for that function or in the documentation for [`chrono::format::strftime`](https://docs.rs/chrono/latest/chrono/format/strftime/index.html), though I do see that it's documented for [`Numeric::Year`](https://docs.rs/chrono/latest/chrono/format/enum.Numeric.html#variant.Year), which `strftime` appears to use internally. I wasn't sure if this was expected behavior, but I wanted to bring it to your attention. Thanks!

**Minimal example**
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ecc55c3483a582e866c5bf5ae51d8325
```rust
use chrono::NaiveDateTime;

const FORMAT_STRING: &str = "%Y-%m-%d %H:%M:%S%.f";

fn main() {
    assert!(NaiveDateTime::parse_from_str("9999-01-01 12:34:56", FORMAT_STRING).is_ok());
    assert!(NaiveDateTime::parse_from_str("10000-01-01 12:34:56", FORMAT_STRING).is_err());
    assert!(NaiveDateTime::parse_from_str("+10000-01-01 12:34:56", FORMAT_STRING).is_ok());
}
```

**Versions**
* `rustc 1.64.0-nightly`
* `chrono` 0.4.21

**Comment by esheppa** [comment]
Thanks for the question @ethowitz - this is intended behaviour to [conform with](https://github.com/chronotope/chrono/blob/6684a470abcd037aeffcde7177128c40e9740f26/src/lib.rs#L7) ISO8601 - essentially the standard primarily supports years 1583 through 9999, but wider ranges can be used, however five-digit and above years require either a `-` or `+` prefix. There is further detail at https://en.wikipedia.org/wiki/ISO_8601#Years

**Comment by c-git** [comment]
> Thanks for the question @ethowitz - this is intended behaviour to [conform with](https://github.com/chronotope/chrono/blob/6684a470abcd037aeffcde7177128c40e9740f26/src/lib.rs#L7) ISO8601 - essentially the standard primarily supports years 1583 through 9999, but wider ranges can be used, however five-digit and above years require either a `-` or `+` prefix. There is further detail at https://en.wikipedia.org/wiki/ISO_8601#Years

Would it be ok to just add a note to the docs for this function as well to help future users?

**Comment by djc** [comment]
Yeah, documentation improvements for this would be great, thanks!

**Comment by c-git** [comment]
Ok submitted a [PR](https://github.com/chronotope/chrono/pull/949) for the docs, happy to add or remove as you see fit. Added the (+/-) for consistency with what I added to the format information. Can remove both if it is not desirable.

**Comment by c-git** [comment]
Closed the old pull request and create a [new one](https://github.com/chronotope/chrono/pull/950) because I needed to target 0.4.x and had originally started from main.
