### ISSUE TITLE
`DateTime::with_unit()` methods fail during DST transition

### ISSUE THREAD

**Issue by ilammy** [chronotope/chrono#955]
When `DateTime` is constructed from unambiguous timestamp for a moment when an hour is repeated due to DST, it is impossible to use modifier methods to adjust the DateTime.

Failing test code:

```rust
use chrono::{TimeZone, Timelike};

#[test]
fn america_new_york_dst_fall_back() {
    // 2022-11-06 01:23:45.678 -04:00
    let time = chrono_tz::America::New_York
        .timestamp_millis_opt(1667712225678)
        .unwrap();

    let time_second = time.with_nanosecond(0).expect("valid second");
    assert_eq!(time_second.timestamp_millis(), 1667712225000); // 2022-11-06 01:23:45 -04:00

    let time_minute = time_second.with_second(0).expect("valid minute");
    assert_eq!(time_minute.timestamp_millis(), 1667712180000); // 2022-11-06 01:23:00 -04:00

    let time_hour = time_minute.with_minute(0).expect("valid hour");
    assert_eq!(time_hour.timestamp_millis(), 1667710800000); // 2022-11-06 01:00:00 -04:00

    let time_day = time_hour.with_hour(0).expect("valid midnight");
    assert_eq!(time_day.timestamp_millis(), 1667707200000); // 2022-11-06 00:00:00 -04:00

    let time_noon = time_day.with_hour(12).expect("valid noon");
    assert_eq!(time_noon.timestamp_millis(), 1667754000000); // 2022-11-06 12:00:00 -05:00
}
```

America/New_York rolls local time back one hour on 2022-11-06 02:00 -04:00 making it 2022-11-06 01:00 -05:00.

I believe that these cases have unambiguous interpretation and the time is actually representable in the time zone.

However, for example, this case should—and currently does—fail to set the hour:

```rust
#[test]
fn america_new_york_dst_spring_forward() {
    // 2023-03-12 03:00:00 -04:00
    let time = chrono_tz::America::New_York
        .timestamp_millis_opt(1678604400000)
        .unwrap();

    // On 2023-03-12 there is no 02:00:00 in America/New_York
    assert!(time.with_hour(2).is_none());
}
```

chrono 0.4.23
chrono_tz 0.8.1

**Comment by djc** [comment]
Can you show where/how it fails exactly? Would you be able to contribute a fix?

**Comment by ilammy** [comment]
> Can you show where/how it fails exactly?

`map_local()` expects a single LocalResult after fiddling with time components:

https://github.com/chronotope/chrono/blob/a892fcc7c26a2a0e626cb027d3079419d2bbd8a0/src/datetime/mod.rs#L514-L520

`chrono` correctly computes two possible DateTime values, but `single()` is unable to choose between them.

> Would you be able to contribute a fix?

Sure. I don't have a patch at hand, but I'll give it a go.

Intuitively I *think* that it should always be possible to disambiguate the result in cases like this by choosing the time closest to `self`. But this requires more thinking to check that I don't miss any funny edge cases.

**Comment by ilammy** [comment]
I think I have managed to formalize my expectations for disambiguation here:

---

If an operation results in ambiguous time, choose the one that has the same time zone offset from UTC as the original DateTime instance.

---

With America/New_York as an example, if you take `2022-11-06 01:23:45.678 -04:00` and do `with_nanosecond(0)` on it, then the valid choices are:

- `2022-11-06 01:23:45.000 -04:00`
- `2022-11-06 01:23:45.000 -05:00`

Here, the result should unambiguously be `2022-11-06 01:23:45.000 -04:00`, retaining the same offset.


### Unresolved questions

However, the aforementioned rule does not _always_ produce “unambiguous” results.

True, `with_nanosecond`, `with_second`, `with_minute` operations in America/New_York can never change the UTC offset of an instant, and thus their result is unambiguous. But it’s not the case for other modifiers working on bigger time units, or for time zones in general.

For example, if you take `2022-01-06 01:23:45.678 -05:00` and do `with_month(11)`, should it *really* produce `-05:00` offset? Or maybe `-04:00` since it’s closer to the original instant? Keeping the same offset is... reasonable, but still an arbitrary decision.

Arguably, the operations should fail in this case since for bigger time units it is genuinely ambiguous and not well defined. Similarly to how `chrono` does not automagically fixup the date if the new month does not have a corresponding day.

Unfortunately, other time zones have other rules. For example, a number of time zones are offset by 30 minutes from UTC (e.g., India) and some of them used to observe DST (e.g., Iran), or shifted backwards (e.g., Sri-Lanka), or still observe DST (e.g., Newfoundland). Thus, `with_minute` is not guaranteed to never cross the offset boundaries and stops being well-defined.

While my use case requires only `with_nanosecond`, `with_second`, `with_minute` to work in a time zone will full-hour offset, I don’t think there is a good reason to arbitrarily decide that some modifiers resolve ambiguity in a particular way, while other methods give up. Making only `with_nanosecond` and `with_second` work feels silly.

What do you think, @djc?

**Comment by ilammy** [comment]
> If you agree, let's close this?

Yes. I think this change does not belong in `chrono` proper.

It's fairly straightforward to work around in applications that need this specific behavior. For example, one of the use cases that I need is "shift DateTime to the start of the hour", which I've implemented like this:

```rust
fn start_of_hour(dt: DateTime<Tz>) -> Option<DateTime<Tz>> {
    map_local(dt, |dt| {
        let time = NaiveTime::from_hms_opt(dt.hour(), 0, 0)?;
        Some(NaiveDateTime::new(dt.date(), time))
    })
}
```

using this utility:

```rust
fn map_local<F>(dt: DateTime<Tz>, mut f: F) -> Option<DateTime<Tz>>
where
    F: FnMut(NaiveDateTime) -> Option<NaiveDateTime>,
{
    f(dt.naive_local()).and_then(|datetime| {
        match dt.timezone().from_local_datetime(&datetime) {
            LocalResult::None => None,
            LocalResult::Single(dt) => Some(dt),
            LocalResult::Ambiguous(dt1, dt2) => {
                if dt1.offset().fix() == dt.offset().fix() {
                    return Some(dt1);
                }
                if dt2.offset().fix() == dt.offset().fix() {
                    return Some(dt2);
                }
                None
            }
        }
    })
}
```

Works it specific cases like this – since if you're in a middle of an hour, you know that its first second must exist – but not in all cases in general utilities like `with_minute() `.

It might be something fitting for `chronoutil`, if it's useful to anybody else. But not here at the base layer, I think.
