### ISSUE TITLE
%Z can't print the timezone abbreviation

### ISSUE THREAD

**Issue by howjmay** [chronotope/chrono#960]
Hi I am having a use case that I need to generate formatted time, and the text should contain the abbreviation of the timezone.
I am using `format_with_items()`, and a format string `"%a %b %d %I:%M:%S  '%Z' %p %Y"`. However, `%Z` doesn't return the abbreviation. What should I do?

**Comment by djc** [comment]
This issue doesn't come with a reproducible example, nor does it show the actual output. Please extend your bug report.

**Comment by howjmay** [comment]
@djc An example is like following 
```rust
use chrono::{format::StrftimeItems, Local};

fn main() {
    let now = Local::now();
    now.with_timezone(now.offset());
    let formatted = now
        .format_with_items(StrftimeItems::new("%a %b %d %I:%M:%S '%Z' %Y"))
        .to_string();
    println!("{formatted}");
}
```

expected result
```
Tue Feb 14 00:55:01 'CET' 2023
```

actual result
```
Tue Feb 14 12:56:24 '+08:00' 2023
```

The expected abbreviation `CET` is replaced by `+08:00`. Or I should use other escape character then I can get the abbreviation of timezone?

**Comment by djc** [comment]
chrono itself doesn't know timezones beyond their offsets, so I don't think it can do what you want. Maybe look at the chrono-tz crate and see if it can help with this?

**Comment by esheppa** [comment]
@howjmay - please see also this issue: https://github.com/chronotope/chrono/issues/749.

`chrono-tz` should do this correctly as per [here](https://github.com/chronotope/chrono-tz/blob/b1104001236cecc51123f857d91519f2afc2b08e/chrono-tz/src/timezone_impl.rs#L29) as the display implementation of the `TimeZone` type is called. You can use `chrono-tz` and `iana-time-zone` (a dependency of `chrono`) together to have behaviour equivalent to local. First use `iana-time-zone` to get the name of the locally set timezone, then you can parse that into a `chrono_tz::Tz`, as per the [example](https://docs.rs/iana-time-zone/latest/iana_time_zone/):

```rust
let tz_str = iana_time_zone::get_timezone()?;
let tz: chrono_tz::Tz = tz_str.parse()?;
```

There is also a partially complete PR to solve this https://github.com/chronotope/chrono/pull/750 and we would appreciate any thoughts or comments you have on it.

**Comment by howjmay** [comment]
Hi @esheppa the method you provided is good. 
However, I found a problem when I checkout the list in chono_tz. The abbreviations of the timezones in chrono_tz seems not complete. 
See the wiki https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
Most of the abbreviation doesn't exist in the list in chono_tz. Or I misunderstand the way to use it?

**Comment by djc** [comment]
chrono-tz includes data from the IANA database. It's definitely possible that this doesn't encompass all abbreviations listed on Wikipedia. I think it is reasonable to consider the IANA database authoritative in this regard.

**Comment by howjmay** [comment]
thanks!

**Comment by campbellcole** [comment]
While this being an issue is understandable, the documentation makes it seem like `chrono` should be able to do this:

https://docs.rs/chrono/latest/chrono/format/strftime/index.html

There are even footnotes for this specifier but none that say it isn't supported for formatting. If possible, I would love the documentation to reflect this. Thanks for your time.

**Comment by pitdicker** [comment]
@campbellcole Would you be willing to make a PR?

**Comment by campbellcole** [comment]
Sure! Will do that tomorrow evening if that’s alright with you.

**Comment by campbellcole** [comment]
For anyone finding this issue from the documentation, you can accomplish this using two additional crates (`chrono-tz` and `iana-time-zone`):
```rs
use chrono::{TimeZone, Utc};
use chrono_tz::{OffsetName, Tz};
use iana_time_zone::get_timezone;

let tz_str = get_timezone().unwrap();
let tz: Tz = tz_str.parse().unwrap();
let offset = tz.offset_from_utc_date(&Utc::now().date_naive());
let abbreviation = offset.abbreviation();
println!("{abbreviation}");
```

**Comment by djc** [comment]
Better documented in #1051.

**Comment by drinkcat** [comment]
Faced this issue as well in `coreutils`. What @campbellcole did looks ok, but has 2 downsides:
 - `chrono_tz` is big (about 2 megabytes added to binary size)
 - `iana_time_zone::get_timezone` does not handle `TZ` environment variable that's commonly available on Linux system.

Came up with something much more complicated here: https://github.com/uutils/coreutils/pull/7849

Slightly simplified below:

```
use chrono::Local;
use iana_time_zone::get_timezone;

#[cfg(embed_tz)]
use chrono_tz::{ParseError, Tz};
#[cfg(not(embed_tz))]
use tzfile::Tz;

#[cfg(embed_tz)]
fn str_to_timezone(str: &str) -> Result<Tz, ParseError> {
    str.parse()
}

#[cfg(not(embed_tz))]
fn str_to_timezone(str: &str) -> Result<Tz, std::io::Error> {
    Tz::named(str)
}

/// Get the alphabetic abbreviation of the current timezone.
///
/// For example, "UTC" or "CET" or "PDT"
fn timezone_abbreviation(timezone: Option<&str>) -> String {
    let utc = str_to_timezone("Etc/UTC").unwrap();
    // We need this logic as `iana_time_zone::get_timezone` does not look
    // at TZ variable: https://github.com/strawlab/iana-time-zone/issues/118.
    let tz = match timezone.or(std::env::var("TZ").as_deref().ok()) {
        // TODO: This is not fully exhaustive, we should understand how to handle
        // invalid TZ values and more complex POSIX-specified values:
        // https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
        Some(s) if s == "UTC0" || s.is_empty() => utc,
        Some(s) => str_to_timezone(s).unwrap_or(utc),
        _ => match get_timezone() {
            Ok(tz_str) => str_to_timezone(&tz_str).unwrap_or(utc),
            Err(_) => utc,
        },
    };

    #[cfg(not(embed_tz))]
    let tz = &tz;

    Local::now().with_timezone(&tz).format("%Z").to_string()
}
```

**Comment by djc** [comment]
@drinkcat sorry that this is messy, it's an interesting set of constraints. Is there a chance chrono's embedded tz_info module could help? Could probably make some of that API publicly accessible if that helps.

https://github.com/chronotope/chrono/tree/main/src/offset/local/tz_info

**Comment by drinkcat** [comment]
Oh interesting, yeah I think that code looks like what we'd need, hard to tell without testing though.

Or, basically, a way to get the timezone abbreviation formatted properly with `%Z` without jumping though many hoops (just FYI, played with `jiff` and that part worked out of the box -- there are other issues though)
