### ISSUE TITLE
Change any combination of y, m or d at the same time

### ISSUE THREAD

**Issue by omid** [chronotope/chrono#962]
Imagine I have a `Date` for this date: `2023-2-1` (Y-M-D)
And I want to change the day to 31 and month to January.

AFAIK, I can use the `DateLike` methods, like `with_month` and `with_day`.
And also if I'm not mistaken, there is no `with_md`, `with_ymd` or any other combination.

The problem is that the order of `with`s will be important in this case.

If first I change month, then day, it will be OK.
If first I change day, then month, it will not be OK.

In this example, I know the order, easy. But in most cases those numbers are dynamic.

The same can happen to `TimeLike` methods.

Code-wise, it will be like the code below:

```
use chrono::*;

fn main() {
    let date = NaiveDate::from_ymd_opt(2023, 2, 1).unwrap();
    println!("{}", date.with_month(1).unwrap().with_day(31).unwrap()); // prints `2000-01-31`
    println!("{}", date.with_day(31).expect("wrong day").with_month(1).unwrap()); // panics with `wrong day`
}
```

**Comment by djc** [comment]
Why can't you simply always change the month first? That seems like a pretty bulletproof strategy?

**Comment by omid** [comment]
@djc, not always.

This code, which is so similar to the code above, fails in the first case:

```
use chrono::*;

fn main() {
    let date = NaiveDate::from_ymd_opt(2023, 1, 31).unwrap();
    println!("{}", date.with_month(2).unwrap().with_day(15).unwrap());
    println!("{}", date.with_day(15).unwrap().with_month(2).unwrap());
}
```

**Comment by djc** [comment]
Ah, that's fair. Okay, feel free submit a PR with an additional `with_month_and_day()` method for `Datelike`.

**Comment by omid** [comment]
I think it should be a more generic function, like `with_ymd` with optional inputs.
Also, another similar method for `TimeLike`, like `with_hms`.
wdyt?

**Comment by djc** [comment]
Do you have a use case for such a `Timelike` method? I don't want to add API based on some theoretical applicability.

**Comment by omid** [comment]
No, not anything I can think of.
I was thinking to have a consistent behavior here.

**Comment by djc** [comment]
Feel free to contribute a `with_ymd()` with `Option` arguments then, please add a bunch of tests to make sure the behavior is correct.

**Comment by omid** [comment]
Which way do you think we should go?

1. `fn with_ymd(&self, year: impl Into<Option<i32>>, month: impl Into<Option<u32>>, day: impl Into<Option<u32>>) -> Option<Self>`
2. `fn with_ymd(&self, year: Option<i32>, month: Option<u32>, day: Option<u32>) -> Option<Self>`

In the first one, we can call `date.with_ymd(None, 3, 31)`. It's a bit nicer API, but can be a bit slower in compile and run times!

**Comment by djc** [comment]
Let's do the simple version (2).

**Comment by pitdicker** [comment]
In the PR related to this issue (https://github.com/chronotope/chrono/pull/965) the conclusion was adding these methods is not worth it.

Similar to https://github.com/chronotope/chrono/issues/549.
