### ISSUE TITLE
Adding a segement of time to a DateTime

### ISSUE THREAD

**Issue by MisterEggnog** [chronotope/chrono#973]
I would like to add 11 hours, 11 minutes, & 11 seconds to the current DateTime.

Currently I have
```rust
let start_time = Utc::now();
let time_offset = start_time + NaiveTime::from_hms_opt(11, 11, 11).unwrap();
```
I have also tried 
```rust
let time_offset = start_time.and_hms_opt(11, 11, 11);
```
Neither of these worked & looking through the documentation I have not found the preferred way of doing this.

How do I do this?

**Comment by esheppa** [comment]
Thanks for the question @MisterEggnog - the best option here is likely to use the `Duration`, you could use for example:

```rust
let time_offset = start_time + chrono::Duration::seconds(11 * 60 * 60 + 11 * 60 + 11);
```

or 

```rust
let offset = chrono::Duration::hours(11) + chrono::Duration::minutes(11) + chrono::Duration::seconds(11);
let time_offset = start_time + offset;
```

**Comment by MisterEggnog** [comment]
That's exactly what I needed, thank you for your help.
