### ISSUE TITLE
[Documentation] Citing this Crate

### ISSUE THREAD

**Issue by kevinmatthes** [chronotope/chrono#981]
First of all, thank you for this Rust crate!

In order to enhance the documentation of a project applying this library, I would like to add information on `chrono` to the list of references.  Are there any citation preferences for this crate?  The target format of the list of references is [CFF](https://github.com/citation-file-format/citation-file-format), but a BibTeX database entry or just a list of plain text information would suffice, as well.

As CFF is GitHub's default format for making software citable, I can also submit you the citation information in a PR, if you are interested in providing them in this repository for future reference.

**Comment by djc** [comment]
I really have no clue about BibText/scientific references/CFF or even what information is generally included when referencing an open source software package. Maybe you can propose something? A PR sounds great.

(I'd be curious to hear more about what you used chrono for.)

**Comment by kevinmatthes** [comment]
Alright, I will prepare an initial setup for the citation metadata.

The project I use `chrono` for is a WIP time tracking and report generation CLI, [`aeruginous`](https://github.com/kevinmatthes/aeruginous-rs).
