### ISSUE TITLE
Invalid datetime format for korean(`ko_KR`)

### ISSUE THREAD

**Issue by scarf005** [chronotope/chrono#985]
# Summary

South korea uses [`Year-Month-Day`](https://en.wikipedia.org/wiki/Date_format_by_country)  date format like rest of east asia. however, it's invalidly rendered as `Month-Day-Year` with `%c`.

```
$ date '+%c
2023년 03월 09일 (목) 오전 11시 59분 40초
$ cargo run # chrono +%c
03/09/23 (목) 11:59:36 오전
```

## To reproduce
(tested in `0.4.23`)
```rs
use chrono::{Local, Locale};

fn main() {
    let time = Local::now();
    let display = |fmt: &str| {
        let localized = time.format_localized(fmt, Locale::ko_KR);
        println!("{fmt}: {localized}");
    };
    display("%c");
    display("%r");
}
```
```
%c: 03/09/23 (목) 11:59:36 오전
%r: 11:59:36 오전
 ~/repo   …  locale  date '+%c'
2023년 03월 09일 (목) 오전 11시 59분 40초
 ~/repo   …  locale  date '+%r'
오전 11시 59분 42초
```

**Comment by djc** [comment]
I think you'll need to file an issue against https://github.com/cecton/pure-rust-locales.

**Comment by djc** [comment]
Maybe it doesn't? Unfortunately I don't have much time to investigate right now. Would be happy to review a PR if you're able to figure it out!

**Comment by scarf005** [comment]
https://github.com/chronotope/chrono/blob/43579a5304f9433ce42614e200b554ea8e0361cc/src/format/strftime.rs#L259-L269

alright, i'm investigating, and i think i found the cause: `with_remainer` does not take d_fmt into account.  `d_t_fmt` in ko_KR depends on `d_fmt`, so it was failing. 

for verification, when i changed `with_remainers` into this, test passes:
```rs
    #[cfg(feature = "unstable-locales")]
    fn with_remainer(s: &'a str) -> StrftimeItems<'a> {
        println!("with remainer s: {:?}", s);
        StrftimeItems {
            remainder: s,
            recons: Vec::new(),
            // d_fmt: D_FMT.to_vec(),
            d_fmt: StrftimeItems::new(locales::d_fmt(Locale::ko_KR)).collect(),
            d_t_fmt: D_T_FMT.to_vec(),
            t_fmt: T_FMT.to_vec(),
        }
    }
```

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/1165.
