### ISSUE TITLE
moving to with_ymd_and_hms - mismatched types: expected struct `DateTime`, found enum `LocalResult`

### ISSUE THREAD

**Issue by nbari** [chronotope/chrono#990]
Hi, I am currently [using](https://github.com/nbari/cron-parser/blob/master/src/lib.rs#L119-L129):

    let tz = dt.timezone();
    let mut next = Utc.from_local_datetime(&dt.naive_local()).unwrap() + Duration::minutes(1);

And then

    next = Utc
         .ymd(next.year(), next.month(), next.day())
         .and_hms(next.hour(), next.minute(), 0);

But when trying to use `with_ymd_and_hms` with something like:

    next = Utc.with_ymd_and_hms(
         next.year(),
         next.month(),
         next.day(),
         next.hour(),
         next.minute(),
         0);    

I am getting: 

    mismatched types: expected struct `DateTime`, found enum `LocalResult`

Any ideas on how to upgrade/use `with_ymd_and_hms`?

**Comment by djc** [comment]
Call `unwrap()` on it, like you used to do for `from_local_datetime()`?

**Comment by nbari** [comment]
hi @djc thanks it is working, I found out also that `timestamp` is not `timestamp_opt` the idea is to have ways to handle the possible error? if yes any example of how to clean deal with it instead of an unwrap ?

**Comment by djc** [comment]
I'm not sure what you mean. In general there are currently a lot of places where chrono does not expose a `Result` enum with an error value but only `Option::None` in case the input is invalid. For timezone conversions the `LocalResult` type has a number of helper methods to help you deal with the different scenarios -- how you want to deal with an invalid value is generally application-specific.
